### DISCUSSION TITLE
[SAML] Logout using Keycloak

### DISCUSSION THREAD

**Discussion by hakoerber** [kimai/kimai#2270] [Questions & Answers]
I'm currently setting up Kimai, using Keycloak as the SAML Identity Provider.

Login works perfectly. But I can't for the life of me get a logout configuration working.

Here are some relevant snippets from my `local.yaml`:

```yaml
security:
  firewalls:
    secured_area:
      kimai_saml: ~
[...]
kimai:
  saml:
    [...]
    connection:
      idp:
        [...]
        singleLogoutService:
          url: '{{ samlEndpoint }}'
          binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
      sp:
        [...]
        singleLogoutService:
          url: 'https://kimai.example.com/auth/saml/logout'
          binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
```

When trying to log out, I get the following error: 

```
RuntimeException:
You must configure the logout path in your firewall.

  at src/Saml/Controller/SamlController.php:84
  at App\Saml\Controller\SamlController->logoutAction()
     (vendor/symfony/http-kernel/HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:32)                
```

The thing it, the logout actually works. I have to reauthenticate with Keycloak when I reload. So it seems that only the post-logout redirect breaks.

---

I tried updating the `security` settings to include an explicit logout statement:

```yaml
security:
  firewalls:
    secured_area:
      kimai_saml: ~
      logout:
        path: /auth/saml/logout
        target: homepage
        invalidate_session: true
```

This leads to the exact same error message, but does **not** actually log me out.

Does anyone have any tips?

**Comment by kevinpapst** [comment]
If you reach this code:
https://github.com/kevinpapst/kimai2/blob/master/src/Saml/Controller/SamlController.php#L84

Then the SAML code is not triggered, but the regular controller action. Normally the SAML auth provider should take over f the URL is called.

What is `{{ samlEndpoint }}`?

**Reply by hakoerber** [reply]
Hey, thank you for the fast response!

`{{ samlEndpoint }}` is `https://keycloak.example.com/auth/realms/realm/protocol/saml`, which is the only valid SAML endpoint for Keycloak according to [the docs](https://www.keycloak.org/docs/latest/server_admin/#keycloak-server-saml-uri-endpoints). Weirdly enough, this part of the logout process actually works. I see a valid logout in Keycloak's log and have to re-authenticate in Kimai.

Keycloak reports `https://kimai.example.com/auth/saml/logout` as the `redirect_uri` for the logout, this is correct, right?

---

One thing I forgot to mention that might affect this: I had to set `kimai.saml.connection.baseurl` to `https://kimai.example.com/auth/saml` in `local.yaml`. I had to set this explicitly because autodetection does not work with my reverse proxy setup. Not setting `baseurl` leads to an error like this during login: `The response was received at http://kimai.example.com:8001/auth/saml/acs instead of https://kimai.example.com/auth/saml/acs`.

Also, the `/auth/saml` path is required to prevent the following error: `The response was received at https://kimai.example.com/acs instead of https://kimai.example.com/auth/saml/acs`. I think this relates to [this issue in onelogin/php-saml](https://github.com/onelogin/php-saml/issues/249), which I found via [this issue in hslavich/OneloginSamlBundle](https://github.com/hslavich/OneloginSamlBundle/issues/88).

I don't know whether setting `baseurl` might have to do with initial problem.

**Reply by kevinpapst** [reply]
Sorry, I have no clue. I never tested Keycloak with Kimai and don't have access to one for testing.
Maybe try to change the logout URL to https://kimai.example.com/en/logout and see what happens.

**Reply by hakoerber** [reply]
Wow, that actually did it!

Using `/en/logout` in Keycloak and in `kimai.saml.connection.sp.singleLogoutService` did the trick. Single Sign-Out now works perfectly.

Thank you very much for your support!

P.S.: Would it make sense to document this somewhere? It's quite a special setup, but if you want I could add a "Kimai with Keycloak" section to the SAML documentation.

**Reply by kevinpapst** [reply]
Yes please, sharing that info would be awesome 👍 

You could add it right after the Azure part here: https://github.com/kimai/www.kimai.org/blob/master/_documentation/saml.md#azure
And you can add a link to this discussion as well, so people can find it easily.

**Comment by dhufnagel** [comment]
Hi @hakoerber 
I have problems configuring saml with keycloak. Is it possible to share your settings? I always get an 500 error ant the following log.


    [2021-04-07 07:48:46] request.INFO: Matched route "saml_acs". {"route":"saml_acs","route_parameters":{"_route":"saml_acs","_controller":"App\\Saml\\Controller\\SamlController::assertionConsumerServiceAction"},"request_uri":"http://zeit.yoshteq.de/auth/saml/acs","method":"POST"} []
    [2021-04-07 07:48:46] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"secured_area","authenticators":1} []
    [2021-04-07 07:48:46] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"secured_area","authenticator":"App\\Security\\TokenAuthenticator"} []
    [2021-04-07 07:48:46] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"secured_area","authenticator":"App\\Security\\TokenAuthenticator"} []
    [2021-04-07 07:48:46] php.WARNING: Warning: sprintf(): Too few arguments {"exception":"[object] (ErrorException(code: 0): Warning: sprintf(): Too few arguments at /var/www/kimai2/vendor/onelogin/php-saml/src/Saml2/ValidationError.php:96)"} []
    [2021-04-07 07:48:46] security.ERROR:  [] []
    [2021-04-07 07:48:46] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException(code: 0):  at /var/www/kimai2/vendor/hslavich/oneloginsaml-bundle/Security/Firewall/SamlListener.php:41)"} []
    [2021-04-07 07:48:46] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"saml_login"} []
    [2021-04-07 07:48:46] request.INFO: Matched route "saml_login". {"route":"saml_login","route_parameters":{"_route":"saml_login","_controller":"App\\Saml\\Controller\\SamlController::loginAction"},"request_uri":"http://zeit.yoshteq.de/auth/saml/login","method":"GET"} []
    [2021-04-07 07:48:46] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"secured_area","authenticators":1} []
    [2021-04-07 07:48:46] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"secured_area","authenticator":"App\\Security\\TokenAuthenticator"} []
    [2021-04-07 07:48:46] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"secured_area","authenticator":"App\\Security\\TokenAuthenticator"} []
    [2021-04-07 07:48:46] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
    [2021-04-07 07:48:46] request.CRITICAL: Uncaught PHP Exception RuntimeException: "" at /var/www/kimai2/src/Saml/Controller/SamlController.php line 52 {"exception":"[object] (RuntimeException(code: 0):  at /var/www/kimai2/src/Saml/Controller/SamlController.php:52)"} []


My config looks like this:

    kimai:
        saml:
            activate: true
            title: Login with yyyyy
            mapping:
                - { saml: $email, kimai: email }
                - { saml: $firstName $lastName, kimai: alias }
            roles:
                attribute: Roles
                mapping:
                    - { saml: Admins, kimai: ROLE_ADMIN }
            connection:
                idp:
                    entityId: 'https://yyyyyyyy.de/auth/realms/DMZ%20Rheinzabern/protocol/saml'
                    singleSignOnService:
                        url: 'https://yyyyyyy.de/auth/realms/DMZ%20Rheinzabern/protocol/saml'
                        binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                    x509cert: 'xxxxxxxxxxx'
                sp:
                    entityId: 'https://xxxxx.de/auth/saml/metadata'
                    assertionConsumerService:
                        url: 'https://xxxxxx.de/auth/saml/acs'
                        binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
                baseurl: 'https://xxxxxx.de/auth/saml/'
                strict: true
                debug: true
                security:
                    nameIdEncrypted:       false
                    authnRequestsSigned:   false
                    logoutRequestSigned:   false
                    logoutResponseSigned:  false
                    wantMessagesSigned:    false
                    wantAssertionsSigned:  false
                    wantNameIdEncrypted:   false
                    requestedAuthnContext: true
                    signMetadata: false
                    wantXMLValidation: true
                    signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
                    digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
                contactPerson:
                    technical:
                        givenName: 'yyy Admin'
                        emailAddress: 'it@yyyyy.de'
                    support:
                        givenName: 'yyy Support'
                        emailAddress: 'it@yyy.de'
                organization:
                    en:
                        name: 'yyy'
                        displayname: 'yyy'
                        url: 'https://www.yyy.de'


I have created mappings for the keycloak attributes and I am getting a saml response with all declared attributes.

**Reply by hakoerber** [reply]
Sure, here is my config  (redacting domains, and leaving out stuff like `mapping` and `roles`:

```yaml
kimai:
  saml:
    activate: true
    title: MyRealm Single Sign-On
    connection:
      idp:
        entityId: 'https://keycloak.example.com/auth/realms/myrealm'
        singleSignOnService:
          url: 'https://keycloak.example.com/auth/realms/myrealm/protocol/saml'
          binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        singleLogoutService:
          url: 'https://keycloak.example.com/auth/realms/myrealm/protocol/saml'
          binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        x509cert: 'XXX'
      sp:
        entityId: 'kimai'
        assertionConsumerService:
          url: 'https://kimai.example.com/auth/saml/acs'
          binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
        singleLogoutService:
          url: 'https://kimai.example.com/en/logout'
          binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        x509cert: 'XXX'
        privateKey: 'XXX'
      # This is important! See:
      #
      # https://github.com/onelogin/php-saml/issues/249
      # https://github.com/hslavich/OneloginSamlBundle/issues/88
      baseurl: 'https://kimai.example.com/auth/saml'
      strict: true
      debug: true
      security:
        nameIdEncrypted:       false
        authnRequestsSigned:   true
        logoutRequestSigned:   true
        logoutResponseSigned:  true
        wantMessagesSigned:    true
        wantAssertionsSigned:  false
        wantNameIdEncrypted:   false
        requestedAuthnContext: true
        signMetadata: false
        wantXMLValidation: true
        signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
        digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
```

Note the differences:

* `kimai.saml.connection.idp.entityId`: Remove `/protocol/saml` at the end
* `kimai.saml.connection.sp.entityId`: It's not a URL. I put the keycloak ClientID there.
---

About the config in keycloak:

The only valid redirect URI necessary is `https://kimai.example/auth/saml/acs`. A few other settings (I'm honestly not sure whether they are defaults or whether I configured them explicitly):

![image](https://user-images.githubusercontent.com/3748696/114062401-c3f48e00-9897-11eb-88ba-53f464349061.png)

---

I hope this helps. Let me know if it works for you! I can also dig deeper into my configuration if you need more help.
