### DISCUSSION TITLE
Docker: 500 error on new installation

### DISCUSSION THREAD

**Discussion by cianiandreadev** [kimai/kimai#2518] [On-Premise: Installation & Updates]
Hi all.
I used the docker-compose template to build a production system, that works behind a reverse proxy I already have (haproxy).

When I run the system I always get a 500 error:

<img width="684" alt="Screenshot 2021-04-21 at 09 31 52" src="https://user-images.githubusercontent.com/1215511/115515824-c981a900-a285-11eb-9f7a-e3ac075dd4d7.png">

Here is my docer-compose file:

```yml
version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./volumes/db:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    networks:
      - kimai-internal

  kimai:
    image: kimai/kimai2:apache-debian-master-prod
    environment:
      - APP_ENV=prod
      - TRUSTED_HOSTS=localhost,192.168.0.30,reverse-proxy # <=== Not sure about this.
      - ADMINMAIL=${ADMINMAIL}
      - ADMINPASS=${ADMINPASS}
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@sqldb/kimai
    container_name: "kimai"
    volumes:
      - ./volumes/kimai/public:/opt/kimai/public2 # << You must use a named volume, see note below
      - ./volumes/kimai/var:/opt/kimai/var
    restart: unless-stopped
    networks:
      - kimai-internal
      - nginx

  postfix:
    image: catatnight/postfix:latest
    networks:
      - kimai-internal
    environment:
      - maildomain=${MAIL_DOMAIN}
      - smtp_user=${SMTP_USER}
    restart: unless-stopped

volumes:
    var:
    public:

networks:
  nginx:
    external:
      name: nginx
  kimai-internal:
```

Can someone tell me please why this? Am I missing some concept?

The docker is running on a i3 Mac Mini, 32GB RAM.
Docker version 20.10.5, build 55c4c88
