### DISCUSSION TITLE
Kimai on Diskstation -> SSO

### DISCUSSION THREAD

**Discussion by ldvs12** [kimai/kimai#3198] [Questions & Answers]
Hi Folks,

I`m looking for help to use the Synology Diskstation SSO-Server for Kimai2.

The Kimai2 installation on the diskstation is running well, but at the moment the users of diskstation needs a separate login for Kimai. My idea is to use the SSO-Server of diskstation in Kimai, so the users can use the same user/password for both.

unfortunately I can't find any how-tos...

Any ideas?

Thanks

**Comment by kevinpapst** [comment]
An "SSO-Server" is highly unspecific. It just means Single-Sign-On and there are dozens technologies out there supporting SSO.
We need to talk protocol here: Kimai supports LDAP and OAuth and both is in the documentation.
I have no Synology, so I unfortunately cannot help any further on that topic without more input.

**Comment by BeckeBauer** [comment]
I would like such a solution as well but have no idea how. Any input were appreciated.

**Comment by troubleshootme** [comment]
You have the option of running LDAP server or AD server on a synology device, Kimai has ldap support. 
You also have the option of running authentik, authelia, etc in docker (most models) on the NAS and authenticating via SAML.

The synology SSO server is very limited and I ended up abandoning that rather quickly once I realized it has little to no support outside of Synology ecosystem.

I use authentik via docker and it has documentation on deploying SAML integration to Kimai,  so while there is a learning curve with authentik or SSO in general, getting Kimai set up with SAML was rather simple. 

I've come to realize that self-hosting is a constant learning experience driven by our own use cases and deploying SSO with something like authentik is one of the more rewarding self-hosting adventures I have been on to be honest.

**Reply by BeckeBauer** [reply]
@troubleshootme
Can you explain a little more about how you set up authentik in order to authenticate users (domain users?) created at the DS to login at kimai?

**Reply by troubleshootme** [reply]
I can point you in the right direction.

I would install Portainer for easier docker management. There are very useful synology docker guides here:
[https://mariushosting.com](https://mariushosting.com)

Portainer guide is here:
[https://mariushosting.com/synology-30-second-portainer-install-using-task-scheduler-docker/](https://mariushosting.com/synology-30-second-portainer-install-using-task-scheduler-docker/)

You should be able to use the built in Synology Reverse Proxy in Control Panel > Login Portal -> advanced
If you are not familiar with that, check marius hosting guides for more details. 

You will want to add a wildcard certificate to your nas, synology makes it easy for synology.me ddns users

After that, create a stack for authentik, there are tutorials online.
I recommend deploying authentik at root of your domain ie. apps.mydomain.com

my apps are reverse proxied from apps.mydomain.com to appname.apps.mydomain.com

I am using synology directory server, but should be similar for synology ldap server.
You will add the ldap server connection under Directory -> Federation & Social login -> LDAP Source
follow these instructions: 
[https://goauthentik.io/integrations/sources/ldap/](https://goauthentik.io/integrations/sources/ldap/)

That will sync authentik with your user directory on the synology ldap server.

From this point on, you can implement any of the integrations that are documented that you wish. You can also integrate with undocumented apps and sites once you are more familiar with the process.

The instructions for kimai are here: [https://goauthentik.io/integrations/services/kimai/](https://goauthentik.io/integrations/services/kimai/)

I knew very little of docker, reverse proxy, sso, etc 6 months ago and I have come a long way just from trying new things constantly.  It can be very frustrating but I enjoy this method over structure-based learning of principles and such but you may be different. 

Best of luck!

Edit: Fixed links, I hope.

**Comment by BeckeBauer** [comment]
Thank you for the hint. I was able to set-up authentik with portainer. Unfortunately, the documentation at [https://goauthentik.io/integrations/sources/active-directory/](https://goauthentik.io/integrations/sources/active-directory/) is not really helpful (I've been using syno directory server as well). 

In authentik, I created a new LDAP Source in Directory -> Federation & Social login (as required for Active Directory)
However, the dialog requires a name for "slug" (which is not mentioned in the documents). What did you use here?

There also seems to be an issue with the username for the domain user to be created for authentic. According to the documentation, it should be `_service_authentik`   Did you created a user with this name (or are the underscores irrelevant)? What rights did you give this users?

So far, I get the following error which indicates that there is something wrong with my choice of user / username:
```
Sync status

ldap_sync_service_authentik_user

Task finished with errors
LDAPInvalidCredentialsResult - 49 - invalidCredentials - None - 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1 - bindResponse - None
```
```

**Reply by BeckeBauer** [reply]
Found the problem. I followed the documents which in step 3 said `Give the User a password, generated using for example pwgen 64 1 or openssl rand -base64 36.` It seems that such a password is way to long. After I shortened the password to "only" 20 random digits, it worked. I agree that it is very frustrating - and really hope that the documentation about how to integrate Kimai is better

**Reply by kevinpapst** [reply]
Sharing is caring.

We can add a page to the docs with all of your findings.

**Reply by BeckeBauer** [reply]
Even though I managed to set up authentik on my Synology NAS, I never set up Kimai  nor started using  authentik. Reason is that I realised when dealing with authentik that I can use Synology AD with Kimai (not as comfortable as SSO but only one password for all user for windows and Kimai login). How to use AD is in your documentation though. If you want, I can share nevertheless my specific Synology settings used to authenticate domain users in Kimai (but it got nothing to do with authentic)!?

**Reply by kevinpapst** [reply]
Having a small chapter in the Synology docs, cross-referencing the SSO docs would be helpful I guess.
Most users are not nerdy enough to find it out by themselves 😄

**Reply by BeckeBauer** [reply]
here is how you could do it:

1. Prerequisite 
Synology Directory Server App installed on your NAS

2. Preparation
open Synology Directory Server App
- Domain Tab: write down:
    Domain name, e.g. your.domain
    Domain NetBios name, e.g. your
    address of Domain Controller, e.g. dc.your.domain
    "DC" part of Distiguished name (DN), e.g. DC=your,DC=domain (everything after OU=Domain Controllers)

- Users & Computers Tab create user: 
    Add - Username 
        User Login name: kimai (can be freely chosen)
        Password: your-password
        Confirm Password: your-password
        Untick "Force this account to change password at next login"
    confirm next windows (it is sufficient if user just belongs to the group 'domain users'

3. local.yaml
create the file local.yaml or add the 'ldap part' to your local.yaml and upload it to kimai2\config\packages

```
kimai:
    ldap:
        activate: true
        connection:
            host: "ldaps://dc.your.domain" <-- change to address of Domain Controller as recorded in first step)
            port: 636 
            useSsl: true
            username: CN=kimai,CN=Users,DC=your,DC=domain <--- the created user, amend the DC information as recorded in the first step
            password: your-password <-- the password for the created user          
            accountFilterFormat: (&(objectClass=Person)(sAMAccountName=%s))
            accountDomainName: your.domain <-- your domain name as recorded in first step
            accountDomainNameShort: your <-- Domain NetBios name as recorded in first step 

        user:
            baseDn: DC=your,DC=domain <--- amend the DC information as recorded in the first step
            usernameAttribute: samaccountname
            filter: (&(objectClass=Person))
            attributesFilter: (objectClass=Person)
            attributes:
                - { ldap_attr: samaccountname,  user_method: setUsername }
                - { ldap_attr: mail, user_method: setEmail }
                - { ldap_attr: displayname, user_method: setAlias }

        role:
            baseDn: DC=your,DC=domain <--- amend the DC information as recorded in the first step
            filter: (&(objectClass=group))
            groups:
                - { ldap_value: Domain Admins, role: ROLE_SUPER_ADMIN } 
                - { ldap_value: management, role: ROLE_ADMIN } <-- assumes that you have created a Domain Group 'management' in your Active Directory App; if not, delete this line
                - { ldap_value: Users, role: ROLE_USER }
```

3. installation
SSH into your Synology NAS, navigate to your Kimai intallation (probably volume1\web\kimai2\) and run the following command
`php80 /usr/local/bin/composer require laminas/laminas-ldap --optimize-autoloader`

Remark: 
use the correct php version that you have installed, e.g. php74
change the path to composer if you have not created a link to your composer.phar under /usr/local/bin/

@kevinpapst : Is there a command to update Kimai that would include the laminas? So far, I am using the command from your documents `composer install --no-dev --optimize-autoloader -n` which deletes laminas and afterwards I have to install it separately (maybe, there is a command to do both in one step)?
