### DISCUSSION TITLE
SAML Logout Error

### DISCUSSION THREAD

**Discussion by ballj** [kimai/kimai#3206] [General] [answered]
**Describe the bug**
When logging out using the default [SAML config with keycloak IDP](https://www.kimai.org/documentation/saml.html#keycloak), when logging out of Kimai it throws a PHP exception in the logs.

The user appears to be logged out of Kimai and IDP but gets a error page on logout.

**To Reproduce**
1. Configure basic SAML login
2. Login to Kimai
3. Logout of Kimai

**Logfile**
```
[2022-03-18 00:46:54] request.CRITICAL: Uncaught PHP Exception RuntimeException: "You must configure the logout path in your firewall." at /opt/kimai/src/Controller/Auth/SamlController.php line 103 {"exception":"[object] (RuntimeException(code: 0): You must configure the logout path in your firewall. at /opt/kimai/src/Controller/Auth/SamlController.php:103)"} []
```

**Additional context**
 - Kimai version: 1.18.2 (docker image apache-1.18.2-prod)
 - PHP version: 8.0.14
 - Device: Windows 11
 - Browser: Firefox 97

**Comment by kevinpapst** [comment]
Misconfiguration? Impossible to help without more information.  Please share at least your config.

**Comment by ballj** [comment]
SAML login works fine, with groups. Just logout that seems to fail.

Config below (slightly redacted):

```
cat /opt/kimai/config/packages/local.yaml
kimai:
  user:
    registration: false
    password_reset: false
  saml:
    activate: true
    title: Keycloak
    mapping:
      - { saml: $Email, kimai: email }
      - { saml: $FirstName $LastName, kimai: alias }
    roles:
      attribute: Roles
      mapping:
        - { saml: Admins, kimai: ROLE_SUPER_ADMIN }
        - { saml: Management, kimai: ROLE_TEAMLEAD }
    connection:
      idp:
        entityId: 'https://${KEYCLOAK_FQDN}/auth/realms/${KEYCLOAK_REALM}'
        singleSignOnService:
          url: 'https://${KEYCLOAK_FQDN}/auth/realms/${KEYCLOAK_REALM}/protocol/saml'
          binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        singleLogoutService:
          url: 'https://${KEYCLOAK_FQDN}/auth/realms/${KEYCLOAK_REALM}/protocol/saml'
          binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        x509cert: '${CERT_DATA}'
      sp:
        entityId: 'https://${KIMAI_FQDN}/auth/saml/metadata'
        assertionConsumerService:
          url: 'https://${KIMAI_FQDN}/auth/saml/acs'
          binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
        singleLogoutService:
          url: 'https://${KIMAI_FQDN}/auth/saml/logout'
          binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
      strict: true
      debug: true
      security:
        nameIdEncrypted: false
        authnRequestsSigned: false
        logoutRequestSigned: false
        logoutResponseSigned: false
        wantMessagesSigned: false
        wantAssertionsSigned: false
        wantNameIdEncrypted: false
        requestedAuthnContext: true
        signMetadata: false
        wantXMLValidation: true
        signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
        digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
      contactPerson:
        technical:
          givenName: 'Kimai Admin'
          emailAddress: '${ADMIN_EMAIL}'
        support:
          givenName: 'Kimai Support'
          emailAddress: '${ADMIN_EMAIL}'
      organization:
        en:
          name: 'Kimai'
          displayname: 'Kimai'
          url: 'https://www.kimai.org'
```
Keycloak config:
![image](https://user-images.githubusercontent.com/38097813/159190958-9e97b140-18c6-4d24-adc2-0f9f131bbd8a.png)

**Reply by kevinpapst** [reply]
I have no experience with the combination of Keycloak and Kimai. But the [Keycloak docs](https://www.kimai.org/documentation/keycloak.html) do not mention the `connection.idp. singleLogoutService`. Did you try to remove that one?

**Comment by ballj** [comment]
Without that line it will not send the user to the IDP to perform the SSO.
It does log the user out of Kimai without the error, but as the user is still logged into the IDP, then they can simply click login again and will login without user/pass.

I have had some luck setting the `Logout Service Redirect Binding URL` to `https://${KIMAI_FQDN}/en/logout` in keycloak, however I think this is more of a workaround than a solution. It does not seem to be calling the SAML logout action.

Just checked the general [SAML config](https://www.kimai.org/documentation/saml.html) and it looks like single logout is not yet supported by Kimai.

```
# the "single logout" feature was not yet tested, if you want to help, please let me know!
```

Happy to help test if you need, although im not too familiar with symfony etc.

**Reply by kevinpapst** [reply]
Kimai is utilizing an API for the SAML connection and this supports single logout. 
Thats why I wrote `not yet tested` which is different from `not yet supported `.

IMO a SSO enabled software should not logout a user from the IDP. 
If I logout of my Kimai I do not expect to be logged out of Youtube or Google.

But if you think different you have to test and debug it yourself, because I have no IDP to test logout:
https://github.com/kevinpapst/kimai2/blob/master/src/Saml/Logout/SamlLogoutHandler.php#L50

You can read more about the used API here, maybe that helps: 
https://github.com/onelogin/php-saml

**Comment by stefankuehnel** [comment, marked as answer]
Hey, I encountered the same issue you described while using [Auth0](https://auth0.com) and [Zitadel](https://zitadel.com) and Kimai `v2.25.0`.

### Error

This is the error in `var/log/prod.log`:

```log
[2024-12-06 19:58:45] [request] CRITICAL: Uncaught PHP Exception RuntimeException: "You must configure the logout path in your firewall." at SamlController.php line 104 {"exception":"[object] (RuntimeException(code: 0): You must configure the logout path in your firewall. at /home/www/kimai.example.com/src/Controller/Auth/SamlController.php:104)"} []
```

### Solution

To resolve this issue, you need to configure the logout path in your `config/packages/local.yaml` file under the security settings. Add the following configuration to enable the correct logout URL for your SAML integration:

> [!CAUTION]
> This change appears to also override the logout URL when you click "Log out" within Kimai itself. I'm not sure if that will cause any problems.

```yaml
security:
    firewalls:
        secured_area:
            logout:
                path: /auth/saml/logout
                target: homepage
                enable_csrf: false
```

### Additional Configuration

Little bit off topic and not related to Keycloak, but if you are using Auth0 as your IdP, the following configuration should also be applied to your `config/packages/local.yaml` file:

```yaml
kimai:
    saml:
        provider: auth0
        activate: true
        title: SAML Login
        mapping:
            - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress, kimai: email }
            - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name, kimai: alias }
        roles:
            resetOnLogin: true
            attribute: Groups
            mapping:
                # Insert your role-mapping here (ROLE_USER is added automatically)
                # WARN: This is the default role mapping from the Kimai docs. This is not the role mapping for Auth0!
                - { saml: Admin, kimai: ROLE_SUPER_ADMIN }
                - { saml: Manager, kimai: ROLE_ADMIN }
                - { saml: Teamlead, kimai: ROLE_TEAMLEAD }
        connection:
            idp:
                entityId: 'urn:example.us.auth0.com'
                singleSignOnService:
                    url: 'https://example.us.auth0.com/samlp/<AUTH0_CLIENT_ID>'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
                singleLogoutService:
                    url: 'https://example.us.auth0.com/samlp/<AUTH0_CLIENT_ID>/logout'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
                x509cert: '<AUTH0_X509_CERT>'
            # Your Kimai: replace https://www.example.com with your base URL
            sp:
                entityId: 'https://kimai.example.com/auth/saml/metadata'
                assertionConsumerService:
                    url: 'https://kimai.example.com/auth/saml/acs'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
                singleLogoutService:
                    url: 'https://kimai.example.com/auth/saml/logout'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                #privateKey: ''
            # only set baseurl, if auto-detection doesn't work
            #baseurl: ''
            strict: true
            debug: true
            security:
                nameIdEncrypted: false
                authnRequestsSigned: false
                logoutRequestSigned: false
                logoutResponseSigned: false
                wantMessagesSigned: false
                wantAssertionsSigned: false
                wantNameIdEncrypted: false
                requestedAuthnContext: true
                signMetadata: false
                wantXMLValidation: true
                signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
                digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
            contactPerson:
                technical:
                    givenName: 'Kimai Admin'
                    emailAddress: 'admin@kimai.example.com'
                support:
                    givenName: 'Kimai Support'
                    emailAddress: 'support@kimai.example.com'
            organization:
                en:
                    name: 'Kimai'
                    displayname: 'Kimai'
                    url: 'https://kimai.example.com'

security:
    firewalls:
        secured_area:
            logout:
                path: /auth/saml/logout
                target: homepage
                enable_csrf: false
```

> [!NOTE]
> Don't forget to reload the cache with `$ bin/console kimai:reload --env=prod`.

You'll need to reference the following details:

- **Kimai Instance URL**: Replace `https://kimai.example.com` with your own Kimai instance URL.
- **Auth0 Tenant FQDN**: Replace `example.us.auth0.com` with your Auth0 tenant's fully qualified domain name (FQDN).
- **Auth0 Client ID**: Replace `<AUTH0_CLIENT_ID>` with your Auth0 Client ID for the Kimai app.
- **Auth0 X509 Certificate**: Replace `<AUTH0_X509_CERT>` with your Auth0 X509 certificate.

> [!NOTE]
> You can also extract all necessary details from the Auth0 IdP metadata URL: `https://example.us.auth0.com/samlp/metadata/<AUTH0_CLIENT_ID>`.

You can find the Auth0 Client ID in your Auth0 Dashboard. Below is an example of where you can locate it:

![Auth0 Client ID in the Auth0 Dashboard](https://github.com/user-attachments/assets/816b7b79-a39a-4f5e-9106-29f997d7f4d9)

#### SAML2 Web App Addon Settings

Make sure that the SAML2 Web App Addon in Auth0 is configured correctly. Here's an example of the settings page for the SAML2 Web App Addon:

![Addon: SAML2 Web App Addon Configuration](https://github.com/user-attachments/assets/90670131-c6d0-42ca-b13b-600c93d2c461)

### References

Auth0. (n.d.). _Enable SAML2 Web App Addon_. Auth0 Docs. Retrieved December 6, 2024, from https://auth0.com/docs/authenticate/protocols/saml/saml-sso-integrations/enable-saml2-web-app-addon
