### DISCUSSION TITLE
Kimai docker compose with nginx proxy manager as reverse proxy

### DISCUSSION THREAD

**Discussion by remus-selea** [kimai/kimai#3548] [On-Premise: Installation & Updates] [answered]
[The official one didn't work for me](https://github.com/tobybatch/kimai2/blob/main/docker-compose.yml).

I'll share below what worked though.

In Nginx Proxy Manager add  `services.kimai.example.com`  as Forward Hostname / IP but replace it with your domain name. The Port is 8001.  You also have to add the domain in `TRUSTED_HOSTS`.

```
version: '3.5'
services:

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    volumes:
      - mysql:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    networks:
      - internal

  kimai:
    image: kimai/kimai2:apache
    container_name: services.kimai.example.com
    restart: unless-stopped
    environment:
      - ADMINMAIL=admin@kimai.local
      - ADMINPASS=changemeplease
      - DATABASE_URL=mysql://kimaiuser:kimaipassword@mysql/kimai
      - TRUSTED_HOSTS=localhost,127.0.0.1,kimai.example.com
    volumes:
      - public:/opt/kimai/public
    networks:
      - internal
      - proxy-network


volumes:
    public:
    mysql:
    

networks:
  internal:
  proxy-network:
    external: true
````

This may be closed.
