### DISCUSSION TITLE
Problem with the redirect on an Univention (UCS) Server

### DISCUSSION THREAD

**Discussion by raywitzel** [kimai/kimai#3550] [On-Premise: Installation & Updates]
Hallo
I'm not sure if I'm on the right place here.
However, I have installed a kimai-docker with with the following docker-compose.yml on our UCS-Server: 
```
version: "3.5"

services:
  app:
    container_name: kimai
    image: kimai/kimai2:apache
    restart: always
    ports:
      - 40801:8001
    volumes:
       - ./html/kimai:/opt/kimai/public
       - ./apache2:/etc/apache2
    depends_on:
        - db
    environment:
      - DATABASE_URL=mysql://kimai:${DATABASE_PASSWORD}@db:3306/kimai
      - TRUSTED_HOSTS=localhost,10.50.24.11,127.0.0.1,app.omicloud.org,213.183.76.224
  db:
    image: mysql:8
    container_name: db_kimai
    restart: always
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimai
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=1

volumes:
  mysql-data:
    driver: local
```
Afterwards I added an admin-user:
```        
EMAIL="xyz@gmx.de"
USERNAME="admin"
docker exec -it kimai    /opt/kimai/bin/console kimai:create-user $USERNAME $EMAIL ROLE_SUPER_ADMIN
```
The internal IP-Adress of the UCS-Server is 10.50.24.11
And there was no problem to start kimai with a terminal-browser (e.g. lynx):
```
lynx 10.50.24.11:40801 
```
The login window appears and I can login. Great. 

Starting kimai via Internetbrowser should be done with 
https://app.omicloud.org/kimai
In the result the browser get the error 404 "The requested URL was not found on this server." 
and the URL adress bar shows: https://app.omicloud.org:8001/kimai/

**Note:** An Apache2 Server runs on the UCS. 
To redirect the URL the configfile  **_/etc/apache2/sites-enabled/default-ssl.conf_** contains the following section
```  
...
 ProxyPass /kimai http://127.0.0.1:40801 retry=0
 ProxyPassReverse /kimai http://127.0.0.1:40801
...
```
We use a dokuwiki container in a same way, and ist works fine. 
However, calling Kimai doesn't work. 

Could it be, that we have a redirect problem with **_/opt/kimai/public/.htaccess_** ?
```
DirectoryIndex index.php
...
<IfModule mod_rewrite.c>
    RewriteEngine On
...
    RewriteCond %{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$
    RewriteRule ^(.*) - [E=BASE:%1]
...
    RewriteCond %{ENV:REDIRECT_STATUS} ^$
    RewriteRule ^index\.php(/(.*)|$) %{ENV:BASE}/$2 [R=301,L]

    # If the requested filename exists, simply serve it.
    # We only want to let Apache serve files and not directories.
    RewriteCond %{REQUEST_FILENAME} -f
    RewriteRule .? - [L]

    # Rewrite all other queries to the front controller.
    RewriteRule .? %{ENV:BASE}/index.php [L]
</IfModule>

<IfModule !mod_rewrite.c>
    <IfModule mod_alias.c>
        # When mod_rewrite is not available, we instruct a temporary redirect of
        # the start page to the front controller explicitly so that the website
        # and the generated links can still be used.
        RedirectMatch 302 ^/$ /index.php/
        # RedirectTemp cannot be used instead
    </IfModule>
</IfModule>
```
It would be nice if anybody could help me. 
Thanks a lot.
