### DISCUSSION TITLE
SAML AzureAD Constant redirect when logging in

### DISCUSSION THREAD

**Discussion by kanonfodda** [kimai/kimai#3557] [Questions & Answers] [answered]
Hi,

I'm trying to get SAML login working within our organisation but i'm having a problem with the login process.  Whe the user clicks "Login with Azure", they are taken to Azure to authenticate as expected.  However once they complete authentication Azure AD seems to get stuck in a loop and constantly reloads the https://login.microsoft.com site with new SAML requests.

I logged a ticket with Microsoft support, but the issue appears to be that Kimai is redirecting back to Azure AD rather than taking the user into the application.

If I open a new tab and load Kimai, it logs in without an issue.  so the login process is working, but from an end user perspective they are left with a constantly looping login page.

I've attached the SAML config from Azure AD and the local.yaml config is below.  any help anyone can offer is greatly appreciated.
```yaml
kimai:
    saml:
        activate: true
        title: Office365
        mapping:
            - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name, kimai: username }
            - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress, kimai: email }
            - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname, kimai: alias }
            - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/jobtitle, kimai: title }
            #- { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/employeeid, kimai: accountNumber }
        roles:
            attribute: groups
            mapping:
                - { saml: ********-****-****-****-************, kimai: ROLE_SUPER_ADMIN }   
                - { saml: ********-****-****-****-************, kimai: ROLE_SUPER_ADMIN }   
        connection:
            idp:
                entityId: 'https://sts.windows.net/********-****-****-****-************/'
                singleSignOnService:
                    url: 'https://login.microsoftonline.com/********-****-****-****-************/saml2'
                binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                singleLogoutService:
                    url: 'https://login.microsoftonline.com/********-****-****-****-************/saml2'  # Logout URL
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'					
                x509cert: '**************'
            sp:
                entityId: 'https://timetrack.***/auth/saml/metadata'
                assertionConsumerService:
                    url: 'https://timetrack.***/auth/saml/acs'
                singleLogoutService:
                    url: 'https://timetrack.***/auth/saml/logout'					
```
![kimai-SAML-1](https://user-images.githubusercontent.com/36201768/192300736-c37a0a03-8a9f-41da-8f2c-0b904e9ce756.PNG)
![kimai-SAML-2](https://user-images.githubusercontent.com/36201768/192300735-08b419a1-ef12-4441-bfd0-faa9aa78d14e.PNG)

**Comment by Trinity99999** [comment]
Hi,
anyone ever solved this problem? I´m having the exact same issue. 
Kimai v. 2.0.2

Thanks in advance.

**Comment by Trinity99999** [comment]
One more remark:

The SAML login works for the first login (when user don´t exist in Kimai yet). 
As soon I logout and try to login again the authentication loop starts.

Kimai access log when the loop starts:
![image](https://user-images.githubusercontent.com/126317006/221350546-d09d1d95-692f-47d3-b097-2d3388f94779.png)


Would really appreciate if someone have a solution for this.

Thanks

**Reply by kanonfodda** [reply]
No solution to this so far.  Microsoft were unable to find any issues on the Azure side, so looks to be somewhere in the Kimai code.

If I find a solution I'll post it here

Tim

**Comment by kevinpapst** [comment]
All I can share is that there are dozens of working AD SAML setups, I have some of my own for testing.
I have never seen that llop. I do believe that it is there, I just don't see why..

**Reply by kanonfodda** [reply]
If there is anyone who has a working azure SAML and can share it for comparison I can see if there is anything obvious that I may have gotten wrong

**Comment by kevinpapst** [comment]
This works for me:
```yaml
        saml:
            activate: true
            title: Login with Azure AD
            provider: microsoft
            mapping:
                - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name, kimai: username }
                - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress, kimai: email }
                - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/displayname, kimai: title }
                - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname, kimai: alias }
            roles:
                attribute: http://schemas.microsoft.com/ws/2008/06/identity/claims/groups
                mapping:
                    - { saml: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx, kimai: ROLE_ADMIN }
                    - { saml: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx, kimai: ROLE_TEAMLEAD }
            connection:
                idp:
                    entityId: 'https://sts.windows.net/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/'
                    singleSignOnService:
                        url: 'https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/saml2'
                    x509cert: '...'
                sp:
                    entityId: 'https://127.0.0.1:8016/auth/saml/metadata'
                    assertionConsumerService:
                        url: 'https://127.0.0.1:8016/auth/saml/acs'
                    singleLogoutService:
                        url: 'https://127.0.0.1:8016/auth/saml/logout'
                strict: false
                debug: true
                security:
                    requestedAuthnContext: false
                contactPerson:
                    technical:
                        givenName: 'Kimai Admin'
                        emailAddress: 'kimai-tech@example.com'
                    support:
                        givenName: 'Kimai Support'
                        emailAddress: 'kimai-support@example.com'
                organization:
                    en:
                        name: 'Kimai'
                        displayname: 'Kimai'
                        url: 'https://www.kimai.org'
```
