### DISCUSSION TITLE
Azure AD groups when using SAML

### DISCUSSION THREAD

**Discussion by DarrinSalt** [kimai/kimai#3560] [Questions & Answers] [answered]
I was really pleased to get Kimai working immediately following the Ubuntu 20.x guide (running on Ubuntu 22 here), and then get SAML login working with the documentation found online, and some of my own knowledge around SAML and Azure.

However, I'm unable to get groups (roles) working at all between Azure and Kimai2 - and wondered if anyone else has cracked this and hopefully seek some guidance.

As a background,  I'm not getting any errors in prod.log, and logging into Kimai2 with even a new user (exists in Azure, not in Kimai) works, with the user being given the default User role in in Kimai. But it doesn't matter what groups the user is a member of in AD, they don't seem to be setting in Kimai.

I can set the users groups manually (and as a side note, they do not appear to be resetting when logging back in, despite having the "  resetOnLogin: true" setting in my local.yaml file), but nor are they being set initially.

I think the attribute is being set correctly, it's being ignored at the web server side of things.

In Azure, I have the following claim:

http://schemas.microsoft.com/ws/2008/06/identity/claims/groups |   |   | user.groups [All]

The users logging in are members of the groups I wish to use, and the start of my local.yaml file contains:

```
kimai:
    saml:
        activate: true
        title: Login with 365
        mapping:
            - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name, kimai: username }
            - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress, kimai: email }
            - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname
            - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname, kimai: alias }
            - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/displayname, kimai: title }
            - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/employeeid, kimai: accountNumber }
        roles:
            resetOnLogin: true
            attribute: Groups
            mapping:
                - { saml: 0b31be02-9ab7-4c6b-b1e7-************, kimai: ROLE_ADMIN }
                - { saml: 9d67a877-8470-42e0-b385-************, kimai: ROLE_TEAMLEAD }
```

                
"Groups" comes from the documentation, but I've tried "groups" - i.e. lower case "g" as well and it makes no difference.

I can confirm that the two group-id's shown above have been double-checked, only redacted here for security. The test users I'm using are members of the respective groups in Azure.

I've not listed the rest of my local.yaml file, as the SAML login is working, so I know the remainder of the file (e.g. the certificate) is all OK.

Has anyone got this working/got any thoughts?

Thanks in advance.
