### DISCUSSION TITLE
Dashboard don't have good hours for week or month

### DISCUSSION THREAD

**Discussion by IT-Pagecran** [kimai/kimai#3930] [Questions & Answers] [answered]
### Describe the issue

Hello,
i passe my kimai to the V2 :), and on the dashboard the hours isn't not good,
i have entered 25h for this week and i have 127h for the week in the dashboard.
it's the same problem for month, 
i start with a clean install for my V2

I join a screenshot

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.0

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.1

### Screenshots

![image](https://user-images.githubusercontent.com/107268149/224009495-de437ba0-0df8-4581-a17e-9ad85c8973e2.png)

**Comment by kevinpapst** [comment]
Can you switch to english and add screenshots from the previous week as well please

**Comment by IT-Pagecran** [comment]
this week
![image](https://user-images.githubusercontent.com/107268149/224033522-b1ef6b56-7f39-4763-8d8a-1071b48480bc.png)
Previous week
![image](https://user-images.githubusercontent.com/107268149/224033620-ce0327c6-8661-4059-8f24-f355ec1fd559.png)

**Comment by kevinpapst** [comment, marked as answer]
Thanks 👍 

You are currently seeing totals for all users, not just your own.
Edit the Dashboard and replace the "Working hours ..." widgets with the ones called "My working hours ...".

**Comment by IT-Pagecran** [comment]
Ooupss, Ok, cool options ;)

**Comment by pgassmann** [comment]
@kevinpapst What is the replacement for the removed dashboard configuration options in local.yml?

The Help (?) button at the bottom right of the dashboard links to https://www.kimai.org/documentation/dashboard.html
Where can this configuration be put now?

We had widgets configured to display the hours of the previous period.

```yaml
kimai:
    widgets:
        userDurationLastWeek: { title: 'Working hours last week', query: duration, user: true, begin: 'monday last week 00:00:00', end: 'sunday last week 23:59:59', icon: duration, color: blue }
        userDurationLastMonth: { title: 'Working hours last month', query: duration, user: true, begin: 'first day of last month 00:00:00', end: 'last day of last month 23:59:59', icon: duration, color: purple }
        userDurationLastYear: { title: 'Working hours last year', query: duration, user: true, begin: '01 january last year 00:00:00', end: '31 december last year 23:59:59', icon: duration, color: yellow }

    dashboard:
        user_old_duration:
            title: 'Last working hours'
            order: 15
            permission: view_own_timesheet
            widgets: [userDurationLastWeek, userDurationLastMonth, userDurationLastYear]
```

Is the only available option now to build a custom plugin for that? 
https://www.kimai.org/documentation/developers.html#extending-the-dashboard-with-widgets
