### DISCUSSION TITLE
Sync Github issues to Kimai activities?

### DISCUSSION THREAD

**Discussion by samuelT2** [kimai/kimai#3982] [General]
Does anybody know a workaround to sync Github issues to the Kimai activities?

Use case: Our activities on projects are based on Github issues. Currently this is a manual process - a new issue triggers a new activity by hand. Would be useful, if we could somehow automate this step.

Thank you for any hint in that direction.

**Comment by kevinpapst** [comment]
You could create a GitHub action that triggers the Kimai API to create a new activity.

Actually that took me less about 10 minutes to create...

Find the code at https://github.com/kevinpapst/demo-github-kimai-api/blob/main/.github/workflows/activity-on-issue.yaml

For docs see:
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issues
- https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#issues

**Reply by kevinpapst** [reply]
Obviously you need to use GitHub Secrets for username and password and somehow map project to issue... but the demo should be a good starting point. Please share your final solution, so others can benefit from it.

**Comment by samuelT2** [comment]
Perfect, thank you very much for your swift reply! I'll take your action as a start and post my final solution here, once I got it working (though, this will take some time).

**Comment by samuelT2** [comment]
Used your workflow as a start and this is the result so far. It does:
1. Creating the activity
2. Updating the rate based on GH issue title
3. Add a team
4. Add a comment to the GH issue

There's probably lots to improve, but so far this is a working file.
Next, I'll create a workflow which sets ```"visible"``` to false once the GH issue gets closed. Will post it here as well.
```
name: Automated Kimai activity creation

on:
  issues:
    types: [opened]

jobs:
  create-activity:
    runs-on: ubuntu-latest
    steps:
    - name: Create Kimai activity
      if: contains(github.event.issue.title, 'Support') || contains(github.event.issue.title, 'Entwicklung')
      run: |
        curl --output data.json --location 'https://stunden.domain.com/api/activities' --header 'X-AUTH-USER: username' --header 'X-AUTH-TOKEN: ${{ secrets.KIMAI_API_PASSWORD }}' --header 'Content-Type: application/json' --data '{"name": "project#${{ github.event.issue.number }} | ${{ github.event.issue.title }}", "comment": "https://github.com/user/project/issues/${{ github.event.issue.number }}", "project": 1, "color": "#ffff00", "visible": true, "billable": true}'

    - name: Parse curl response
      id: parse_data
      run: echo '::set-output name=id::'$(jq -r '.id' data.json)

    - name: Update activity rate (200 rate)
      if: contains(github.event.issue.title, 'Entwicklung')
      run: |
        curl --location 'https://stunden.domain.com/api/activities/${{ steps.parse_data.outputs.id }}/rates' --header 'X-AUTH-USER: username' --header 'X-AUTH-TOKEN: ${{ secrets.KIMAI_API_PASSWORD }}' --header 'Content-Type: application/json' --data '{"rate": 200}'

    - name: Update activity rate (100 rate)
      if: contains(github.event.issue.title, 'Support')
      run: |
        curl --location 'https://stunden.domain.com/api/activities/${{ steps.parse_data.outputs.id }}/rates' --header 'X-AUTH-USER: username' --header 'X-AUTH-TOKEN: ${{ secrets.KIMAI_API_PASSWORD }}' --header 'Content-Type: application/json' --data '{"rate": 100}'

    - name: Update activity team
      if: contains(github.event.issue.title, 'Support') || contains(github.event.issue.title, 'Entwicklung')
      run: |
        curl --request POST --location 'https://stunden.domain.com/api/teams/8/activities/${{ steps.parse_data.outputs.id }}' --header 'X-AUTH-USER: username' --header 'X-AUTH-TOKEN: ${{ secrets.KIMAI_API_PASSWORD }}'

    - name: Create GH comment - Success 1
      if: contains(github.event.issue.title, 'Support') || contains(github.event.issue.title, 'Entwicklung')
      uses: peter-evans/create-or-update-comment@v3.0.0
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          Kimai activity created, ID-${{ steps.parse_data.outputs.id }}

    - name: Create GH comment - Success 2
      if: contains(github.event.issue.title, 'Support') || contains(github.event.issue.title, 'Entwicklung')
      uses: peter-evans/create-or-update-comment@v3.0.0
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          Link: [Kimai activity #${{ steps.parse_data.outputs.id }}](https://stunden.domain.com/de_CH/admin/activity/${{ steps.parse_data.outputs.id }}/details)

    - name: Create GH comment - Failure
      if: (!contains(github.event.issue.title, 'Support')) && (!contains(github.event.issue.title, 'Entwicklung'))
      uses: peter-evans/create-or-update-comment@v3.0.0
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          Kimai activity *NOT* created, keyword 'Support' or 'Entwicklung' is missing in title. Please create the activity manually.
```
([fjogeleit/http-request-action](https://github.com/fjogeleit/http-request-action) provides requests with a GH action, but I don't like having another third party dependency - but I'm sure, this would also work just fine.)

**Comment by samuelT2** [comment]
This is the workflow which sets the visible = false based on the activity ID added as a comment beforehand:
```
name: Automated Kimai activity closure

on:
  issues:
    types: [closed]

jobs:
  close-activity:
    runs-on: ubuntu-latest
    steps:
    - name: Find Comment
      uses: peter-evans/find-comment@v2.3.0
      id: fc
      with:
        issue-number: ${{ github.event.issue.number }}
        comment-author: github-actions[bot]
        body-includes: Kimai activity created, ID-

    - name: Set comment env
      if: ${{ steps.fc.outputs.comment-id != 0 }}
      run: |
        echo "COMMENT=${{ steps.fc.outputs.comment-body }}" >> $GITHUB_ENV
    
    - name: Find activity ID
      if: ${{ env.COMMENT != 0 }}
      run: |
        echo Relevant comment: ${{ env.COMMENT }}
        echo "ACTIVITY_ID=$(echo ${{ env.COMMENT }} | grep -Po '\d+$')" >> $GITHUB_ENV

    - name: Update activity, set visible=false
      if: ${{ env.ACTIVITY_ID != 0 }}
      run: |
        echo Activity ID: ${{ env.ACTIVITY_ID }}
        curl --request PATCH --location 'https://stunden.domain.com/api/activities/${{ env.ACTIVITY_ID }}' --header 'X-AUTH-USER: user' --header 'X-AUTH-TOKEN: ${{ secrets.KIMAI_API_PASSWORD }}' --header 'Content-Type: application/json' --data '{"visible": false}'

    - name: Create GH comment - Success
      if: ${{ env.ACTIVITY_ID != 0 }}
      uses: peter-evans/create-or-update-comment@v3.0.0
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          Kimai activity ID-${{ env.ACTIVITY_ID }} updated, set visible = false

    - name: Create GH comment - Failure
      if: ${{ env.ACTIVITY_ID == 0 }}
      uses: peter-evans/create-or-update-comment@v3.0.0
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          Nothing to update in Kimai, no relevant activity found
```
