### DISCUSSION TITLE
LDAP authentication impossible

### DISCUSSION THREAD

**Discussion by Jeromesdis81** [kimai/kimai#4067] [On-Premise: Installation & Updates]
Hello,

I try to use Kimai on premise in order to do time tracking.
The product seems to be very nice.
My organisation has an ldap server.
I can't make users authentication on this server.
I'm using php 8.1 with the latest version of Kimai.
In a first tilme, I just try to make a simple connexion to the LDAP just in order to test the fonctionnality.
I read the documentation and tried to make a local.yalm file very simple.
Here is the content of my local.yalm file :

```
security:
    providers:
     chain_provider:
         chain:
            providers: [kimai_ldap]
    firewalls:
         secured_area:
            kimai_ldap: ~
kimai:
    ldap:
        activate: true
        connection:
          host: "@lP of ldap server"
          username: uid="user for the bind",dc=sdis81,dc=fr
          password: "password"
        user:
          baseDN: dc=sdis8,dc=fr
          usernameAttribute: cn
```
Kimai never try to use LDAP.
It always search the user in the internal data base.
I'm in dev mode and the log file simply indicate a authentication error (withou any reference to LDAP search) :
[2023-05-29T11:23:53.245331+00:00] security.INFO: Authenticator failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\UserNotFoundException(code: 0): There is no user with identifier \"toto.toto\". at /var/www/kimai/vendor/symfony/security-core/User/ChainUserProvider.php:67)","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []

Can some one help me to activate the LDAP authentication ?
The sotfware is realy good and hope to use it but it's impossible without the LDAP connexion.

Tanks a lot.
