### DISCUSSION TITLE
Ldap Authenticaten: Login with cn as Username not with Email

### DISCUSSION THREAD

**Discussion by Borega** [kimai/kimai#4083] [On-Premise: Installation & Updates]
So I run Kimai in a docker and have added SAML and LDAP as Auth methodes. SAML works fine (not topic of discussion here), Ldap as well -- but ONLY if you use the Email as Username for the Login on consecutive logins. 
The problem is as follows:
When logging in the first time with ldap, you can use the cn (firstname.lastname in this case) as login username. This is the custom way my users (students) use all ower services. 
On the second try it then only works when entering the Email as login username. Using the cn results in the following error:
An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'CN-here' for key 'UNIQ_LONGNUMBER'

Using SAML to login into a ldap created account works fine.

from my local.yaml:

```
ldap:
        activate: true
        connection:
          host: ldaps://MYHOST
          username: cn=USER,ou=ldap,dc=dc,dc=tld
          password: PASSWORD
        user:
          baseDn: ou=users, dc=DC, dc=tld
          usernameAttribute: uid
          filter: (&(objectClass=uuidObject))
          attributes:
            - { ldap_attr: cn,  user_method: setUsername }
            - { ldap_attr: gecos, user_method: setAlias }
            - { ldap_attr: mail, user_method: setEmail }
```

I was hoping, that mapping setUsername to cn would allow me to login with cn, as it does for the first time. It seems after that it is not recognised anymore and therefore Kimai tries to create a new account, which ofc results in an error.

So my question is: can I change the login username to cn in any way?

**Comment by kevinpapst** [comment]
Everyone has another setup, which does or does not stick to the none-existing best practices  ... I really hate LDAP server and cannot give support for free. Yes, because I hate them.

And unfortunately I cannot really answer your question, because I simply don't know. Did you read the docs for every single config attribute? Did you try `usernameAttribute: cn` ?

**Reply by Borega** [reply]
Thank you for your answer. I can fully understand your hate towards LDAP. 
I read the docs, I tried all the single config attributes. usernameAttribute: cn unfortunately does not change anything. 
Maybe someone has another idea?

**Reply by kevinpapst** [reply]
Sorry for the unexpected rant yesterday. But ever since my first contact with LDAP 20+ years ago they are still one of those products that just can't work out of the box.

**Comment by BeckeBauer** [comment]
my settings for ldap authentication is 
```
        user:
            baseDn: DC=dc,DC=tdl
            usernameAttribute: samaccountname
            filter: (&(objectClass=Person))
            attributesFilter: (objectClass=Person)
            attributes:
                - { ldap_attr: samaccountname,  user_method: setUserIdentifier }
                - { ldap_attr: mail, user_method: setEmail }
                - { ldap_attr: displayname, user_method: setAlias }
```
login with user name works for me with these settings
