### DISCUSSION TITLE
SAML support

### DISCUSSION THREAD

**Discussion by BeckeBauer** [kimai/kimai#4101] [On-Premise: Installation & Updates]
I managed to set up SSO with SAML - however, after the first user uses SAML to log in, the email address of this user is deleted  from the database (in the profile page, there is no email shown anymore; I checked also the database and it's gone). 

When the second user logs in, the error message is that there is already an empty email address so that "creating or hydrating" of this user fails. After manually adding the email address of the first user to the database, the second user can log in via SAML but the email address of the second user gets lost in the process and so on

My local.yaml is:

```
    saml:
        provider: Synology
        activate: true
        title: Login with SAML
        mapping:
            - { saml: $Email, kimai: email }       
        connection:
            idp:
                entityId: 'https://my.synology.domain/sso/webman/sso/SSOOauth.cgi'
                singleSignOnService:
                    url: 'https://my.synology.domain/sso/webman/sso/SSOOauth.cgi'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                x509cert: 
                ......
            sp:
                entityId: 'https://my.kimai.domain/auth/saml/metadata'
                assertionConsumerService:
                    url: 'https://my.kimai.domain/auth/saml/acs'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
            baseurl: 'https://my.kimai.domain/auth/saml/'
```

Synology SAML settings are
![image](https://github.com/kimai/kimai/assets/51003649/722ac09f-9971-4503-b0bd-7af1bf11aa3a)

I have no idea what causes the deletion - maybe someone has faced the same / a similar situation?
