### DISCUSSION TITLE
Problem using SSO with Authentik

### DISCUSSION THREAD

**Discussion by chriscroome** [kimai/kimai#4113] [On-Premise: Installation & Updates]
I have just setup a Kimai site running on Debian Bullseye with PHP 8.2 from Sury, Composer 2.5.8 and the latest version of Kimai, 2.0.26 and we are trying to get it working with Authentik.

In `var/log/prod.log` we have this error:

```
[2023-06-15T13:53:02.164328+01:00] request.CRITICAL: Uncaught PHP Exception TypeError: "App\Configuration\SamlConfiguration::getProvider(): Return value must be of type string, null returned" at /home/time/sites/kimai/src/Configuration/SamlConfiguration.php line 30 {"exception":"[object] (TypeError(code: 0): App\\Configuration\\SamlConfiguration::getProvider(): Return value must be of type string, null returned at /home/time/sites/kimai/src/Configuration/SamlConfiguration.php:30)"} []
```

This is a (edited, x509 cert omitted etc) version of `config/packages/local.yaml`:

```yaml
kimai:
    defaults:
        user:
            timezone: Europe/London
            language: en
            currency: GBP
        customer:
            timezone: Europe/London
            country: GB
            currency: GBP
    calendar:
        businessHours:
            begin: '09:00'
            end: '17:00'
    user:
        registration: false
    saml:
        provider: authentik
        activate: true
        title: Login with Authentik
        mapping:
            - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress, kimai: email }
            - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name, kimai: alias }
        roles:
            resetOnLogin: true
            attribute: http://schemas.xmlsoap.org/claims/Group
            mapping:
                - { saml: admin.group, kimai: ROLE_ADMIN }
        connection:
            idp:
                entityId: "https://authentik.example.org"
                singleSignOnService:
                    url: "https://authentik.example.org/application/saml/time-tracking/sso/binding/redirect/"
                    binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                singleLogoutService:
                    url: "https://authentik.example.org/if/session-end/time-tracking/"
                    binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                x509cert: "" # ommitted
            sp:
                entityId: "https://kimai.example.org"
                assertionConsumerService:
                    url: "https://kimai.example.org/auth/saml/acs"
                    binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                singleLogoutService:
                    url: "https://kimai.example.org/auth/saml/logout"
                    binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                #privateKey: ''
            baseurl: "https://kimai.example.org/auth/saml/"
            strict: false
            debug: true
            security:

                nameIdEncrypted: false
                authnRequestsSigned: false
                logoutRequestSigned: false
                logoutResponseSigned: false
                wantMessagesSigned: false
                wantAssertionsSigned: false
                wantNameIdEncrypted: false
                requestedAuthnContext: true
                signMetadata: false
                wantXMLValidation: true
                signatureAlgorithm: "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"
                digestAlgorithm: "http://www.w3.org/2001/04/xmlenc#sha256"
            contactPerson:
                technical:
                    givenName: "Kimai Admin"
                    emailAddress: "admin@example.org"
            organization:
                en:
                    name: "Kimai"
                    displayname: "Kimai"
                    url: "https://kimai.example.org"

```

Does anyone have a suggestion for us (myself and @mbh-dev) regarding further debugging and solving this?

**Comment by mbh-dev** [comment]
As a follow up from the Authentik end of things, it would appear that everything is working as expected:

Authorized application:
UID
547**********************2
Name
Time Tracking
App
authentik_core
Model Name
application
Using flow
[Authorize Application](https://authentik.company/if/admin/#/flow/flows/default-provider-authorization-explicit-consent)

Show less
Context
{
    "flow": "a3*******************44",
    "http_request": {
        "args": {
            "query": "SAMLRequest=fVN******************************D&RelayState=https%3A%2F%2Fkimai.company%2Fauth%2Fsaml%2Flogin"
        },
        "path": "/api/v3/flows/executor/default-provider-authorization-explicit-consent/",
        "method": "GET"
    },
    "authorized_application": {
        "pk": "547**************2",
        "app": "authentik_core",
        "name": "Time Tracking",
        "model_name": "application"
    }
}
User
{
    "pk": 1,
    "email": "user@authentik.company",
    "username": "user"
}

**Reply by chriscroome** [reply]
However the Kimai login fails with:

> An authentication exception occurred.

**Comment by kevinpapst** [comment]
This message means that 
```
    saml:
        provider: authentik
```

is not there. Your local.yaml looks interesting. Did you upgrade from some ancient Kimai version?
Why do you have all these settings in there, which you can configure using the System > Settings UI?
Reload the cache, I doubt that your visible config here is the same that Kimai sees.

**Reply by mbh-dev** [reply]
Hi @kevinpapst 

We've used the template found here: https://www.kimai.org/documentation/saml-authentik.html

I cannot see an option for SAML/SSO/Authentication in system → settings apart from enabling/disabling the login form and password reset.

We're running the latest version of Kimai.

Thanks
Liam

**Comment by chriscroome** [comment]
Thanks for your assistance @kevinpapst.

> Did you upgrade from some ancient Kimai version?

No but an old Ansible role was used for the initial install and this is the source of the  `local.yaml`, I hadn't realised that a `local.yaml` isn't needed for those setting in the latest Kimai, I've deleted them now.

> This message means that
>
> ```yaml
>    saml:
>        provider: authentik
> ```
> is not there.

Sorry I don't understand, the YAML above does contain this YAML, but perhaps I have misunderstood what exactly you mean by _"is not there"_?

We have reloaded the cache after each edit to `local.yaml`:

```bash
console kimai:reload --env=prod
```

We do have a link to login using Authentik but after the redirect back to Kimai there is this error:

> An authentication exception occurred.

And there is nothing in the PHP, Apache or Kimai log, but perhaps @mbh-dev might be able to find something in the Authentik log tomorrow.

Any other debugging suggestions?

**Reply by kevinpapst** [reply]
> Sorry I don't understand, the YAML above does contain this YAML, but perhaps I have misunderstood what exactly you mean by "is not there"?

You posted a log
> SamlConfiguration::getProvider(): Return value must be of type string, null returned

Which 100% clearly indicates that this piece of information is NOT in the YAML.
So either you posted an old and irrelevant log entry or there is some problem with the YAML that I do not understand.

Try debugging with this: 
https://github.com/kimai/kimai/pull/4107/files#diff-2d0942cde63447a6c4cbde096505c831a401f80b60ca612d2b2d2bf02be60116R82

**Reply by chriscroome** [reply]
Thanks @kevinpapst, sorry I guess the `config/packages/local.yaml` was updated after that log was posted, the file starts like this:

```yaml
---
kimai:
    saml:
        provider: authentik
        activate: true
```

After adding the the following to `src/Saml/SamlAuthenticator.php`:

```php
        file_put_contents(__DIR__ . '/../../var/log/saml.xml', $oneLoginAuth->getLastResponseXML());
```

The log file at `var/log/saml.xml` looks OK but the `<ds:X509Certificate>` field contains a truncated value compared with the `config/packages/local.yaml` file (should the `kimai.saml.connection.idp.x509cert` variable in `local.yaml` contain a pair of concatenated public keys? Because this is what it look like we have @mbh-dev ?)

After uncommenting the following in `src/Saml/SamlAuthenticator.php`:

```php
        $this->logger->debug('Received SAML response: ' . $oneLoginAuth->getLastResponseXML());
```

Attempts to login using Authentik return a HTTP 500 error and this message:

> Unable to extract public key
