### DISCUSSION TITLE
kimai2 on DSM 7.2

### DISCUSSION THREAD

**Discussion by manuxi** [kimai/kimai#4142] [General]
Hi all,

the day before yesterday I stupidly updated my Synology from 7.1 to 7.2. it seems that the nginx config was damaged. I can not get into kimai anymore.

Nearly the whole day I tried to get it to run again, because I need to log my work for my customers there. But it keeps redirecting me to /de/homepage and throws a 404 (older version). I've already installed the 2.036 in another folder, but the error is similar. In the logs of the webportal I see an error (not sure whether it's from kimai2 or webportal itself):  

"open() /volume1/web/timetracker/public/missing failed (2: No such file or directory)". Of course that dir/file does not exist.

I went through the docs (https://www.kimai.org/documentation/synology.html) to modify the nginx config again with no success. At the moment I'm getting a 502. It seems that the config is not correct. "nginx -t" works fine though.

Is it possible that I missed something? I put the "location"-directives at the top under index index.php, left the old "location"-directive there.

I'm stuck and in panic. Is there anyone who can give me a hint how to access my worklog again? It would be gladly appreciated.

**Comment by BeckeBauer** [comment]
The update caused me some trouble as well. You need to ssh into your server and go to `/usr/local/etc/nginx/conf.d`
there, you will find all the webservices you have created with the Web Station App.
find the service you created for Kimai (starting with .service.xxxxxx - maybe, the date helps) and open it
it should start with
```

    root    "/volume1/web/timetracker/public"; 
    index    index.php index.htm index.html;
```
At the end, you will find a line like

`    include /usr/local/etc/nginx/conf.d/3544rt23-822d-4e0e-966b-609b4e4573eb/user.conf*;`

create this folder, in my example `3544rt23-822d-4e0e-966b-609b4e4573eb`

put your nginx user.conf there, e.g. `user.conf.kimai` 

restart nginx `sudo nginx -s reload` and you should be good and running again

**Comment by manuxi** [comment]
Thank you for that answer! I'll give it a try!

**Comment by manuxi** [comment]
Getting a 500 now. Not sure what config I should use. nginx config is new for me. I'm referring to https://www.kimai.org/documentation/synology.html.
I found that config before and already made some changes. At least I got a white screen without an error, but haven't gotten it to work again. I exchanged "fastcgi_pass unix:/run/php/php8.1-fpm.sock;" with "fastcgi_pass unix:/run/php-fpm/php-2b0603b9-5db2-487d-8da6-a7451fab384f.sock;", added the fastcgi.conf-include. Don't know what to add to that config...

**Comment by BeckeBauer** [comment]
I am using the following user.conf

```
access_log off;
log_not_found off;

location ~ /\.ht {
    deny all;
}

location / {
    try_files $uri /index.php$is_args$args;
}

location ~ \.php$ {
    return 404;
}
```
maybe that helps

**Reply by manuxi** [reply]
no :'(
Thank you so much for your help! Since I urgently need that tool, I've installed it locally now with apache pointing to c:/web/tools/kimai2/public. Seems to run, time entries are there, but I have to check what causes JS errors. Some integrity problems, noone of the buttons is working...

**Reply by manuxi** [reply]
ok, yarn install + yarn build did the trick. Again, thank you for your support!

**Comment by manuxi** [comment]
With your nginx config it's working half now!! Thank you again!
Hopefully last thing: css is missing. Playing around with nginx didn't solve it so far:

```
location /bundles {
        try_files $uri $uri/ /index.html =404;
    }
```

![image](https://github.com/kimai/kimai/assets/11303615/e129bf44-2803-48ab-951e-92f18d7a4030)

**Reply by kevinpapst** [reply]
Kimai does not support running in subdirectories, as written in all requirement sections.

**Reply by BeckeBauer** [reply]
Sorry for my ignorance: What is meant by "subdirectories"? 
On my Synology server, the kimai files are stored under /volume1/web/kimai (which I though is a subdirectory) and everything is running smoothly (at least until the next update ;-)

**Reply by manuxi** [reply]
Yes, I read this many times. nginx root poits to "[...]/public".
![image](https://github.com/kimai/kimai/assets/11303615/ae99932f-2ab7-4bf6-9a7c-263cdacfabbd)

**Reply by manuxi** [reply]
![image](https://github.com/kimai/kimai/assets/11303615/cbd039ce-ab64-4a8f-9964-ec755d727d49)

**Reply by manuxi** [reply]
So, build/...css works, bundles/...css not. The folder bundles does not exist there...

**Reply by kevinpapst** [reply]
Run `bin/console assets:install`, seems you installation was only half baked.

**Reply by manuxi** [reply]
Thanks for that hint. I'll try that.

**Comment by 82280zx** [comment]
Here is what I did in my YAML in docker. Make sure to map your volumes correctly, mine live in /volume2/docker/ I made a folder in there called Kimai then mapped it accordingly like below.
```
version: '3.5'
services:

  sqldb:
    image: mysql:latest
    volumes:
      - /volume2/docker/Kimai/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=changeme
    ports:
      - 3399:3306

    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2:apache
    volumes:
      - /volume2/docker/Kimai/data:/opt/kimai/var/data
      - /volume2/docker/Kimai/plugins:/opt/kimai/var/plugins
    ports:
      - 8001:8001
    extra_hosts:
        - "host.docker.internal:host-gateway"
    environment:
      - ADMINMAIL=Put your Email Address Here
      - ADMINPASS=Put your Admin Pass here
      - "DATABASE_URL=mysql://kimaiuser:kimaipassword@host.docker.internal:3399/kimai"
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1
    restart: unless-stopped

volumes:
  data:
  mysql:
  plugins: 
```

**Reply by ChangeTheCode** [reply]
@82280zx I have the isse that my "mysql" container always crash on my synology NAS (DS218) . with your provided docker compose file (I adjusted the paths). 

Error message is 
`
[Server] MySQL Server Initialization - end.
[ERROR] [MY-010119] [Server] Aborting
[ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
[ERROR] [MY-010460] [Server] --initialize specified but the data directory exists and is not writable. Aborting.
[System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 9.3.0) initializing of server in progress as process 81
[System] [MY-015017] [Server] MySQL Server Initialization - start.
`

Do you have any idea?

**Reply by 82280zx** [reply]
> @82280zx I have the isse that my "mysql" container always crash on my synology NAS (DS218) . with your provided docker compose file (I adjusted the paths).
> 
> Error message is `[Server] MySQL Server Initialization - end. [ERROR] [MY-010119] [Server] Aborting [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it. [ERROR] [MY-010460] [Server] --initialize specified but the data directory exists and is not writable. Aborting. [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 9.3.0) initializing of server in progress as process 81 [System] [MY-015017] [Server] MySQL Server Initialization - start.`
> 
> Do you have any idea?

When you mapped your paths, did you make sure those folders was pre created in the pathway on your nas?

In the MySQL spot this is probably where your hang up is.
volumes:
      - /volume2/docker/Kimai/mysql:/var/lib/mysql

On my synology I have a folder called docker, inside that is Kimai and inside that another folder called mysql, it needs to be mapped to a folder that docker can write to.

**Reply by ChangeTheCode** [reply]
looked like this was related to the missing directories. 

I used this docker-compose file and with this it works fine on my synology NAS, with ARM CPU Architecture
```yml
version: '3.5'
services:

  sqldb:
    image: mysql:latest
    #volumes:
    #  - /volume1/docker/Kimai/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=REPLACE-WITH-CORRECT-PW
      - MYSQL_ROOT_PASSWORD=REPLACE-WITH-CORRECT-PW
    ports:
      - 3399:3306
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2:apache-2.37.0
    volumes:
      - /volume1/docker/Kimai/data:/opt/kimai/var/data
      - /volume1/docker/Kimai/plugins:/opt/kimai/var/plugins
    ports:
      - 8001:8001
    extra_hosts:
        - "host.docker.internal:host-gateway"
    environment:
      - ADMINMAIL=admin-mail@test.de
      - ADMINPASS=REPLACE-WITH-CORRECT-PW
      - "DATABASE_URL=mysql://kimaiuser:kimaipassword@host.docker.internal:3399/kimai"
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1
    restart: unless-stopped
    
volumes:
  data:
  mysql:
  plugins: 
  ```
