### DISCUSSION TITLE
How to extend CustomerRepository?

### DISCUSSION THREAD

**Discussion by simonschaufi** [kimai/kimai#4375] [Plugins]
I would like to create some custom queries for the CustomerRepository and I'm struggling extending it. What I have is this:

```php
namespace KimaiPlugin\MyBundle\Repository;

use App\Repository\CustomerRepository;

class ExtendedCustomerRepository extends CustomerRepository
{
}
```

And in my Symfony Command I inject the `ExtendedCustomerRepository` like so:

```php
class MyCommand extends Command implements ContainerAwareInterface
{
    use ContainerAwareTrait;

    public function __construct(
        private ExtendedCustomerRepository $extendedCustomerRepository
    ) {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        // Here the extendedCustomerRepository is an instance of CustomerRepository which is wrong!
        $customers = $this->extendedCustomerRepository->customQuery();
    }
}
```

and in my `plugins/MyBundle/Resources/config/services.yaml` I'm struggling with the right config:

```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KimaiPlugin\MyBundle\:
        resource: '../../*'
        exclude: '../../{Model,DependencyInjection,Resources}'

    KimaiPlugin\MyBundle\Repository\ExtendedCustomerRepository:
        class: KimaiPlugin\CustomerEmailReportBundle\Repository\ExtendedCustomerRepository
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments: ['App\Entity\Customer']

    App\Repository\CustomerRepository:
        class: KimaiPlugin\MyBundle\Repository\ExtendedCustomerRepository
```

I found https://symfony.com/doc/current/service_container/service_decoration.html but this doesn't work for me. Now I'm stuck.

The problem is that for some reason I always get the `CustomerRepository` injected instead of my own `ExtendedCustomerRepository`.

Can anyone help me please?
