### DISCUSSION TITLE
Setting up Kimai issues - Base install + Logging

### DISCUSSION THREAD

**Discussion by acseven** [kimai/kimai#4409] [On-Premise: Installation & Updates] [answered]
Hi,

I would like to ask some help on figuring out some issues I'm having with setting up Kimai. Kimai FPM in running on Docker (Debian) and according to "Doctor" (screenshot below), it should be ok. 

However the logfile is not created or modified if created manually. I've checked permissions and used recommendation to fix permissions in the documentation here:
    https://www.kimai.org/documentation/docker-troubleshooting.html#permissions
The log file only exists on the screenshot after I created it but it doesn't make a difference.

Within the docker container:
```
4aa957a5fd27:~# ls -l /opt/kimai/var/
total 20
drwxrwxr-x 4 www-data www-data 4096 Nov  5 17:54 cache
drwxrwxr-x 2 www-data www-data 4096 Nov  5 11:57 data
-rw-rw-r-- 1 www-data www-data    6 Nov  5 17:53 installed
drwxrwxr-x 2 www-data www-data 4096 Nov  5 22:41 log
drwxrwxr-x 4 www-data www-data 4096 Nov  5 09:58 plugins
4aa957a5fd27:~# ls -l /opt/kimai/var/log/
total 0
-rw-rw-r-- 1 www-data www-data 0 Nov  5 15:37 prod.log
```

Doctor:
![image](https://github.com/kimai/kimai/assets/1176371/701d5006-bae7-4b9b-81e2-0806df2d2a7e)

Portainer stack:
```
version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=SomePassword
    #ports:
    #  - 3336:3306
    volumes:
      - mysql:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  nginx:
    image: tobybatch/nginx-fpm-reverse-proxy
    ports:
      - 8001:80
    volumes:
      - public:/opt/kimai/public:ro
    restart: unless-stopped
    depends_on:
      - kimai
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai: # This is the latest FPM image of kimai
    image: kimai/kimai2:fpm
    environment:
      - ADMINMAIL=webadmin@mymail.local
      - ADMINPASS=ThisAndThat
      - DATABASE_URL=mysql://kimaiuser:kimaipassword@sqldb/kimai?charset=utf8&serverVersion=5.7
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1,192.168.3.4,192.168.3.6
      - MAILER_URL=smtps://(redacted)
      - MAILER_FROM=webmail.notifications@mymail.local
    volumes:
      - /_BASE/docker/kimai/v/public:/opt/kimai/public
      - /_BASE/docker/kimai/v/kimai/var:/opt/kimai/var
      - /_BASE/docker/kimai/v/conf/local.yaml:/opt/kimai/config/packages/local.yaml
      #- /_BASE/docker/kimai/v/conf/ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    restart: unless-stopped

#  phpmyadmin:
#   image: phpmyadmin
#   restart: always
#   ports:
#      - 8081:80
#    environment:
#      - PMA_ARBITRARY=1

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    volumes:
      - ./swagger.json:/swagger.json
    environment:
      - SWAGGER_JSON=/swagger.json

  mailer:
    image: schickling/mailcatcher
    ports:
      - "${MAILER_SMTP_PORT:-1025}:1025"
      - "${MAILER_ADMIN_PORT:-1080}:1080"


volumes:
    var:
    public:
    mysql:
```
