### DISCUSSION TITLE
User registration - Symfony error with configuration provided

### DISCUSSION THREAD

**Discussion by AsP3X** [kimai/kimai#4630] [Questions & Answers] [answered]
Hello Kimai Community and Devs

I have following issue:
After i've configured the MAILER_URL and MAILER_FROM i receive following error message when trying to register a new user:
```
[2024-02-12T12:27:40.172854+00:00] request.INFO: Matched route "registration_register". {"route":"registration_register","route_parameters":{"_route":"registration_register","_controller":"App\\Controller\\Security\\SelfRegistrationController::registerAction","_locale":"de"},"request_uri":"http://DOMAIN_FOR_SERVICE/de/register/","method":"POST"} {"channel":"request"}
[2024-02-12T12:27:40.488287+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Mailer\Exception\TransportException: "Expected response code "250" but got code "550", with message "550-Requested action not taken: mailbox unavailable 550 Sender address is not allowed."." at SmtpTransport.php line 338 {"exception":"[object] (Symfony\\Component\\Mailer\\Exception\\TransportException(code: 550): Expected response code \"250\" but got code \"550\", with message \"550-Requested action not taken: mailbox unavailable\r\n550 Sender address is not allowed.\". at /opt/kimai/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php:338)"} {"channel":"request"}
```

My docker-compose configuration:
```yaml
version: '3.5'
services:

  kimai-db:
    image: mariadb:10.5
    restart: unless-stopped
    container_name: kimai-db
    networks:
      - kimai-internal
    environment:
      MYSQL_DATABASE: DATABASENAME
      MYSQL_USER: DATABASEUSER
      MYSQL_ROOT_PASSWORD: DATABASE_ROOT_PASSWORD
      MYSQL_PASSWORD: DATABASE_PASSWORD
    volumes:
      - /path/to/database:/var/lib/mysql
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai-service:
    image: kimai/kimai2:apache
    container_name: kimai-service
    volumes:
      - /path/to/config/local.yaml:/opt/kimai/config/packages/local.yaml
    ports:
      - 8001:8001
    environment:
      - ADMINMAIL=ADMIN_MAIL
      - ADMINPASS=ADMIN_PASSWORD
      - DB_TYPE=mysql
      - DB_USER=DATABASEUSER
      - DB_PASS=DATABASE_PASSWORD
      - DB_HOST=DATABASE_HOST
      - DB_PORT=3306
      - DB_BASE=DATBASE_NAME
      - MAILER_URL=smtp://noreply%40domain.de:password@smtp.ionos.de:587?encryption=tls&auth_mode=true
      - MAILER_FROM=noreply@domain.de
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1
    restart: unless-stopped
```

This configuration works with Mastodon and nextcloud so the credentials and noreply config can't be the issue.

What can i do to fix this, i've google quite a lot and wasn't able to find a solution to it.
