### DISCUSSION TITLE
Google SAML - error "empty URL" on access through App icon

### DISCUSSION THREAD

**Discussion by seleondevel** [kimai/kimai#4756] [Plugins]
Hello.

After setting up Google SAML local.yaml, you can log in, but if you click the kimai icon created in workspace on the Google app,

It goes to https://www.example.com/auth/saml/acs , but it cannot be redirected to an empty URL as shown below. An error appears.

How can I solve this problem?

Help me!

![스크린샷 2024-04-09 104409](https://github.com/kimai/kimai/assets/165639563/008b935a-6c26-4bbc-9324-8c99b028be69)
![스크린샷 2024-04-09 104958](https://github.com/kimai/kimai/assets/165639563/e62239e4-3a50-4521-a00f-59cdbc386d30)

**Comment by seleondevel** [comment]
/kimai/config/packages/local.yaml

The local.yaml file is configured as follows. There is no problem with spacing. The comment registration is not spacing out.
```yaml
kimai:    
    saml:
        provider: google
        activate: true
        title: Login with SAML
        mapping:
            - { saml: $Email, kimai: email }
            - { saml: $FirstName $LastName, kimai: alias }
        roles:
            resetOnLogin: true
            attribute: Groups
            mapping:
                - { saml: Admin, kimai: ROLE_SUPER_ADMIN }
                - { saml: Manager, kimai: ROLE_ADMIN }
                - { saml: Teamlead, kimai: ROLE_TEAMLEAD }
        connection:
            idp:
                entityId: 'https://accounts.google.com/o/saml2?idpid=hidden_id'
                singleSignOnService:
                    url: 'https://accounts.google.com/o/saml2/idp?idpid=hidden_id'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                #singleLogoutService:
                #    url: 'https://www.example.com/logout'
                #    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                x509cert: '-----BEGIN CERTIFICATE-----
                           ...
                           ...
                           ...
                           ...
                           ...
                           ...
                           ...
                           ...
                           ...
                           ...
                           -----END CERTIFICATE-----'
            # Your Kimai: replace https://www.example.com with your base URL
            sp:
                entityId: 'https://www.example.com/auth/saml/metadata'
                assertionConsumerService:
                    url: 'https://www.example.com/auth/saml/acs'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
                singleLogoutService:
                    url: 'https://www.example.com/auth/saml/logout'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                #privateKey: ''
             # only set baseurl, if auto-detection doesn't work
            #baseurl: ''
            strict: true
            debug: true
            security:
                nameIdEncrypted: false
                authnRequestsSigned: false
                logoutRequestSigned: false
                logoutResponseSigned: false
                wantMessagesSigned: false
                wantAssertionsSigned: false
                wantNameIdEncrypted: false
                requestedAuthnContext: true
                signMetadata: false
                wantXMLValidation: true
                signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
                digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
            contactPerson:
                technical:
                    givenName: 'Kimai Admin'
                    emailAddress: 'admin@example.com'
                support:
                    givenName: 'Kimai Support'
                    emailAddress: 'support@example.com'
            organization:
                en:
                    name: 'Kimai'
                    displayname: 'Kimai'
                    url: 'https://www.example.com'
```
For security purposes, I wrote www.example.com arbitrarily. Please understand. Access is no problem.
