### DISCUSSION TITLE
"output_path" under "webpack_encore"

### DISCUSSION THREAD

**Discussion by aruznieto** [kimai/kimai#4893] [Docker]
### Describe the problem

[php:error] [pid 61] [client 127.0.0.1:33536] PHP Fatal error:  Uncaught Symfony\\Component\\Config\\Definition\\Exception\\InvalidConfigurationException: The child config "output_path" under "webpack_encore" must be configured: The path where Encore is building the assets - i.e. Encore.setOutputPath() in /opt/kimai/vendor/symfony/config/Definition/ArrayNode.php:233\nStack trace:\n#0 /opt/kimai/vendor/symfony/config/Definition/BaseNode.php(421): Symfony\\Component\\Config\\Definition\\ArrayNode->finalizeValue()\n#1 /opt/kimai/vendor/symfony/config/Definition/Processor.php(36): Symfony\\Component\\Config\\Definition\\BaseNode->finalize()\n#2 /opt/kimai/vendor/symfony/config/Definition/Processor.php(46): Symfony\\Component\\Config\\Definition\\Processor->process()\n#3 /opt/kimai/vendor/symfony/dependency-injection/Extension/Extension.php(109): Symfony\\Component\\Config\\Definition\\Processor->processConfiguration()\n#4 /opt/kimai/vendor/symfony/webpack-encore-bundle/src/DependencyInjection/WebpackEncoreExtension.php(35): Symfony\\Component\\DependencyInjection\\Extension\\Extension->processConfiguration()\n#5 /opt/kimai/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(76): Symfony\\WebpackEncoreBundle\\DependencyInjection\\WebpackEncoreExtension->load()\n#6 /opt/kimai/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(42): Symfony\\Component\\DependencyInjection\\Compiler\\MergeExtensionConfigurationPass->process()\n#7 /opt/kimai/vendor/symfony/dependency-injection/Compiler/Compiler.php(80): Symfony\\Component\\HttpKernel\\DependencyInjection\\MergeExtensionConfigurationPass->process()\n#8 /opt/kimai/vendor/symfony/dependency-injection/ContainerBuilder.php(767): Symfony\\Component\\DependencyInjection\\Compiler\\Compiler->compile()\n#9 /opt/kimai/vendor/symfony/http-kernel/Kernel.php(506): Symfony\\Component\\DependencyInjection\\ContainerBuilder->compile()\n#10 /opt/kimai/vendor/symfony/http-kernel/Kernel.php(763): Symfony\\Component\\HttpKernel\\Kernel->initializeContainer()\n#11 /opt/kimai/vendor/symfony/http-kernel/Kernel.php(185): Symfony\\Component\\HttpKernel\\Kernel->preBoot()\n#12 /opt/kimai/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\\Component\\HttpKernel\\Kernel->handle()\n#13 /opt/kimai/vendor/autoload_runtime.php(29): Symfony\\Component\\Runtime\\Runner\\Symfony\\HttpKernelRunner->run()\n#14 /opt/kimai/public/index.php(5): require_once('...')\n#15 {main}\n  thrown in /opt/kimai/vendor/symfony/config/Definition/ArrayNode.php on line 233

### Describe your setup and add your Docker compose file (redact your credentials)

Linux
- Docker: 26.1.3 
- Compose:  v2.27.0

```
networks:
  backend:
    external: true
  frontend:
    external: true
services:

  sqldb:
    container_name: db-kimai-prod-1
    image: mysql:8.3
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    networks:
      - backend

  kimai:
    container_name: apache-kimai-prod-1
    image: kimai/kimai2:apache
    volumes:
      - ./data:/opt/kimai/var/data
      - ./config:/opt/kimai/config/packages
    environment:
      - ADMINMAIL=${ADMINMAIL}
      - ADMINPASS=${ADMINPASS}
      - "DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@sqldb/${MYSQL_DATABASE}?charset=utf8mb4&serverVersion=8.3.0"
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1
    networks:
      - frontend
      - backend
    labels:
      traefik.enable: "true"
      traefik.http.services.kimai-prod-1.loadbalancer.server.port: "8001"
      traefik.http.services.kimai-prod-1.loadbalancer.server.scheme: "http"
      traefik.http.routers.kimai-prod-1-http.entrypoints: "web"
      traefik.http.routers.kimai-prod-1-http.rule: "Host(`xxxxxx `)"
      traefik.http.routers.kimai-prod-1-https.entrypoints: "websecure"
      traefik.http.routers.kimai-prod-1-https.rule: "Host(`xxxxxx`)"
      traefik.http.routers.kimai-prod-1-https.tls: "true"
      traefik.http.routers.kimai-prod-1-https.tls.certresolver: "cloudflare"
    restart: unless-stopped

```

### Command used to run the container

docker compose up -d
