### DISCUSSION TITLE
kimai2 with SAML for keycloak SSO

### DISCUSSION THREAD

**Discussion by nbaud** [kimai/kimai#4942] [On-Premise: Installation & Updates]
### Describe the issue

I tried several (a lot of) different settings and followed the documentation (not sure if the documentation is still uptodate with Keycloak as the interface looks quite different now).

Still, I could not get it to work. It goes to Keycloak, does the SSO login process, then it's redirected to https://kimai2.xxx.xx/auth/saml/acs and a POST occurs with a subsequent redirect to https://kimai2.xxx.xx/en/login seems not responsive. There I simply get an error from `nginx` like this URL does not exist. But if I go to https://kimai2.xxx.xx/index.php/en/login I get the message "An authentication exception occurred."

I installed the firefox extension SAML tracer to try to track down the issue and it seems to me that the ACS part with `/auth/saml/acs` is fine but the redirection after that is having an issue. Also, I could see through that firefox extension that all the information required is being passed on by keycloak back to kimai2 (including the roles and attributes).

```
Page not found
We could not find the page you were looking for. Please return to your dashboard and start over. 
```

My local.yaml file looks like this:

```yaml
kimai:
    saml:
        provider: keycloak
        activate: true
        title: Keycloak
        mapping:
            - { saml: $Email, kimai: email }
            - { saml: $FirstName $LastName, kimai: alias }
        roles:
            resetOnLogin: true
            attribute: Roles
            mapping:
                - { saml: XXX, kimai: ROLE_ADMIN }
                - { saml: admin, kimai: ROLE_TEAMLEAD }
        connection:
            idp:
                entityId: 'https://sso.xxx.xx/realms/master'
                singleSignOnService:
                    url: 'https://sso.xxx.xx/realms/master/protocol/saml/clients/ssokimai'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                x509cert: 'XXXXXXX'
            sp:
                entityId: 'Kimai2'
                assertionConsumerService:
                    url: 'https://kimai2.xxx.xx/auth/saml/acs'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
                singleLogoutService:
                    url: 'https://kimai2.xxx.xx/auth/saml/logout'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                #privateKey: ''
            # only set baseurl, if auto-detection doesn't work
            baseurl: 'https://kimai2.xxx.xx/auth/saml/'
            strict: true
            debug: true
            security:
                nameIdEncrypted: false
                authnRequestsSigned: false
                logoutRequestSigned: false
                logoutResponseSigned: false
                wantMessagesSigned: false
                wantAssertionsSigned: false
                wantNameIdEncrypted: false
                requestedAuthnContext: true
                signMetadata: false
                wantXMLValidation: true
                signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
                digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
            contactPerson:
                technical:
                    givenName: 'Admin'
                    emailAddress: 'admin@xxx.xx'
                support:
                    givenName: 'Support Team'
                    emailAddress: 'admin@xxx.xx'
            organization:
                en:
                    name: 'XXX'
                    displayname: 'XXX'
                    url: 'https://xxx.xx'
```

I also noticed an annoying thing, that after (almost) each reset of the cache with:

```sh
bin/console cache:clear --env=prod
```

I had to manually change back the ownership of the directory with:

```sh
chown -R www-data:www-data /var/www/kimai2/var/cache/prod
```

Any help would be welcome!

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.18

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2
