### DISCUSSION TITLE
Can't change "Cookie Lifetime" with "local.yaml"

### DISCUSSION THREAD

**Discussion by Rudiberto** [kimai/kimai#5005] [Questions & Answers] [answered]
Hi, 
being really happy with Kimai, I tried now to get a longer session time by creating the local.yaml file with the following content:

```
framework: 
   session:
       gc_maxlifetime: 44000
       cookie_lifetime: 44000
```

I cleared the cache after that, but in Firefox it still shows 7 days session remember time and users connecting after being absent for more than 7 days are still locked out.
![grafik](https://github.com/user-attachments/assets/2db76240-fe87-4f67-a5ea-e882e737d4b7)

What am I doing wrong, or isn't that possible?

I also tried to edit the php.ini, but with no result. Can anyone explain to me, where I'm failing?
I only want to achieve that the users do not have to fill in their username and password after holidays. Since that happens all in their own session and I do not want to give the password to the users, a longer session acceptance would be perfect for my needs.

**Comment by Rudiberto** [comment, marked as answer]
With a little bit of help I figured out a Solution.
```
framework:
    session:
        gc_maxlifetime: 144000  
        cookie_lifetime: 144000

security:
    firewalls:
        secured_area:
            remember_me:
                lifetime: 144000
```
Now I have to wait 7+ days, to see if the shown REMEMBERME value will be respected by the browser.
So, crossing fingers.
