### DISCUSSION TITLE
Docker secrets seemingly not applied

### DISCUSSION THREAD

**Discussion by Thalley** [kimai/kimai#5056] [Docker]
### Describe the problem

When setting up `kimai` with `docker` and supplying the initial `ADMINMAIL` and `ADMINPASS` as per https://www.kimai.org/documentation/docker-compose.html then I'd expect to be able to do 

```
    environment:
      FILE__ADMINMAIL: /run/secrets/kimai_admin_mail
      FILE__ADMINPASS: /run/secrets/kimai_admin_pass
    secrets:
      - kimai_admin_mail
      - kimai_admin_pass

secrets:
  kimai_admin_mail:
    file: docker_secrets/kimai_admin_mail.txt
  kimai_admin_pass:
    file: docker_secrets/kimai_admin_pass.txt
```

It doesn't really matter if `kimai` use the commonly used `FILE__` prefix or something else, but it should support Docker secrets for secret information such as passwords and emails (especially for an admin account). 

See also https://github.com/linuxserver/docker-kimai?tab=readme-ov-file#environment-variables-from-files-docker-secrets (I do realize it's a different image, but I would expect it to also work for the official image). 

### Describe your setup and add your Docker compose file (redact your credentials)

OS: Linux
Docker version: 27.2.0
Docker compose version: 2.29.2
