### DISCUSSION TITLE
Not accepting connections for no appearent reason

### DISCUSSION THREAD

**Discussion by yuri-becker** [kimai/kimai#5082] [Docker] [answered]
Hi there, first of all thanks for all the work you put into the project.

I just tried to set it up with docker+caddy. When trying to access the site, i just get a 502.
Here are the startup logs:

<details>
<p>

```
kimai-mysql  | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
kimai-mysql  | 2024-09-26T10:34:19.037090Z 0 [System] [MY-015015] [Server] MySQL Server - start.
kimai-mysql  | 2024-09-26T10:34:19.271180Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.4.2) starting as process 1
kimai-mysql  | 2024-09-26T10:34:19.272740Z 0 [Warning] [MY-010122] [Server] One can only use the --user switch if running as root
kimai-mysql  | 2024-09-26T10:34:19.276521Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
kimai-kimai  | + php /dbtest.php mysql kimai 3306 <redacted> <redacted>
kimai-kimai  | + echo Checking DB: 10
kimai-kimai  | + sleep 3
kimai-kimai  | Testing DB:** new \PDO(mysql:host=mysql;dbname=kimai;port=3306, <redacted>, <redacted>,[ \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ]);*SQLSTATE[HY000] [2002] Connection refused (?)Checking DB: 10
kimai-mysql  | 2024-09-26T10:34:22.276164Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
kimai-mysql  | 2024-09-26T10:34:23.616453Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
kimai-mysql  | 2024-09-26T10:34:23.616521Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encryptedconnections are now supported for this channel.
kimai-mysql  | 2024-09-26T10:34:23.705076Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
kimai-mysql  | 2024-09-26T10:34:23.863080Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
kimai-mysql  | 2024-09-26T10:34:23.863286Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.4.2'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
kimai-kimai  | + php /dbtest.php mysql kimai 3306 <redacted> <redacted>
kimai-kimai  | + echo 'Connection established'
kimai-kimai  | Testing DB:** new \PDO(mysql:host=mysql;dbname=kimai;port=3306, <redacted>, <redacted>,[ \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ]);*Connection established
kimai-kimai  | + handleStartup
kimai-kimai  | + sed -i 's/memory_limit.*/memory_limit=1G/g' /usr/local/etc/php/php.ini
kimai-kimai  | + cp /assets/monolog.yaml /opt/kimai/config/packages/monolog.yaml
kimai-kimai  | + tar -zx -C /opt/kimai -f /var/tmp/public.tgz
kimai-kimai  | + '[' -z 1944 ']'
kimai-kimai  | + '[' -z 100 ']'
kimai-kimai  | + grep -w 100 /etc/group
kimai-kimai  | + echo Group already exists
kimai-kimai  | + id 1944
kimai-kimai  | Group already exists
kimai-kimai  | + echo User already exists
kimai-kimai  | + '[' -e /use_apache ']'
kimai-kimai  | User already exists
kimai-kimai  | + '[' -e /use_fpm ']'
kimai-kimai  | + sed -i 's/user = .*/user = 1944/g' /usr/local/etc/php-fpm.d/www.conf
kimai-kimai  | + sed -i 's/group = .*/group = 100/g' /usr/local/etc/php-fpm.d/www.conf
kimai-kimai  | + echo 'Setting fpm to run as 1944:100'
kimai-kimai  | Setting fpm to run as 1944:100
kimai-kimai  | + exec /service.sh
kimai-kimai  | + waitForDB
kimai-kimai  | + '[' '!' -z 'mysql://<redacted>:<redacted>@mysql/kimai?charset=utf8mb4&serverVersion=8.3.0' ']'
kimai-kimai  | ++ awk -F '[/:@]' '{print $1}'
kimai-kimai  | + DB_TYPE=mysql
kimai-kimai  | ++ awk -F '[/:@]' '{print $4}'
kimai-kimai  | + DB_USER=<redacted>
kimai-kimai  | ++ awk -F '[/:@]' '{print $5}'
kimai-kimai  | + DB_PASS=<redacted>x
kimai-kimai  | ++ awk -F '[/:@]' '{print $6}'
kimai-kimai  | + DB_HOST=mysql
kimai-kimai  | ++ awk -F '[/:@]' '{print $7}'
kimai-kimai  | + DB_PORT='kimai?charset=utf8mb4&serverVersion=8.3.0'
kimai-kimai  | ++ awk -F '[/?]' '{print $4}'
kimai-kimai  | + DB_BASE=kimai
kimai-kimai  | + re='^[0-9]+$'
kimai-kimai  | + [[ kimai?charset=utf8mb4&serverVersion=8.3.0 =~ ^[0-9]+$ ]]
kimai-kimai  | + DB_PORT=3306
kimai-kimai  | Wait for MySQL DB connection ...
kimai-kimai  | + echo 'Wait for MySQL DB connection ...'
kimai-kimai  | + php /dbtest.php mysql kimai 3306 <redacted> <redacted>
kimai-kimai  | + echo 'Connection established'
kimai-kimai  | Testing DB:** new \PDO(mysql:host=mysql;dbname=kimai;port=3306, <redacted>, <redacted>,[ \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ]);*Connection established
kimai-kimai  | + handleStartup
kimai-kimai  | + /opt/kimai/bin/console -n kimai:install
kimai-kimai  |
kimai-kimai  | Kimai installation running ...
kimai-kimai  | ==============================
kimai-kimai  |
kimai-kimai  | Database `kimai` for connection named default already exists. Skipped.
kimai-kimai  |
kimai-kimai  |  [OK] Already at the latest version ("DoctrineMigrations\Version20240920105524")
kimai-kimai  |
kimai-kimai  |
kimai-kimai  |  Rebuilding your cache, please be patient ...
kimai-kimai  |
kimai-kimai  |  // Clearing the cache for the prod environment with debug false
kimai-kimai  |
kimai-kimai  | [2024-09-26T10:34:25.130077+00:00] deprecation.INFO: User Deprecated: Since doctrine/doctrine-bundle 2.13: Enablingthe controller resolver automapping feature has been deprecated. Symfony Mapped Route Parameters should be used as replacement. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since doctrine/doctrine-bundle 2.13: Enabling the controller resolver automapping feature has been deprecated. Symfony Mapped Route Parameters should be used as replacement. at /opt/kimai/vendor/doctrine/doctrine-bundle/src/DependencyInjection/DoctrineExtension.php:533)"} {"channel":"deprecation"}
kimai-kimai  | [2024-09-26T10:34:32.365908+00:00] deprecation.INFO: User Deprecated: Since twig/twig 3.12: Twig Filter "spaceless"is deprecated in /opt/kimai/vendor/kevinpapst/tabler-bundle/templates/components/button.html.twig at line 4. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since twig/twig 3.12: Twig Filter \"spaceless\" is deprecated in /opt/kimai/vendor/kevinpapst/tabler-bundle/templates/components/button.html.twig at line 4. at /opt/kimai/vendor/twig/twig/src/ExpressionParser.php:830)"} {"channel":"deprecation"}
kimai-kimai  | [2024-09-26T10:34:32.398744+00:00] deprecation.INFO: User Deprecated: Since twig/twig 3.12: Twig Filter "spaceless"is deprecated in /opt/kimai/vendor/kevinpapst/tabler-bundle/templates/components/actions.html.twig at line 19. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since twig/twig 3.12: Twig Filter \"spaceless\" is deprecated in /opt/kimai/vendor/kevinpapst/tabler-bundle/templates/components/actions.html.twig at line 19. at /opt/kimai/vendor/twig/twig/src/ExpressionParser.php:830)"} {"channel":"deprecation"}
kimai-kimai  |  [OK] Cache for the "prod" environment (debug=false) was successfully cleared.
kimai-kimai  |
kimai-kimai  |
kimai-kimai  |  // Warming up the cache for the prod environment with debug false
kimai-kimai  |
kimai-kimai  |  [OK] Cache for the "prod" environment (debug=false) was successfully warmed.
kimai-kimai  |
kimai-kimai  |
kimai-kimai  |  [OK] Congratulations! Successfully installed Kimai version 2.22.0
kimai-kimai  |
kimai-kimai  | + /opt/kimai/bin/console -n kimai:update
kimai-kimai  |
kimai-kimai  | Kimai updates running ...
kimai-kimai  | =========================
kimai-kimai  |
kimai-kimai  |
kimai-kimai  |  [OK] Already at the latest version ("DoctrineMigrations\Version20240920105524")
kimai-kimai  |
kimai-kimai  |
kimai-kimai  |  Rebuilding your cache, please be patient ...
kimai-kimai  |
kimai-kimai  |  // Clearing the cache for the prod environment with debug false
kimai-kimai  |
kimai-kimai  | [2024-09-26T10:34:33.820725+00:00] deprecation.INFO: User Deprecated: Since doctrine/doctrine-bundle 2.13: Enablingthe controller resolver automapping feature has been deprecated. Symfony Mapped Route Parameters should be used as replacement. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since doctrine/doctrine-bundle 2.13: Enabling the controller resolver automapping feature has been deprecated. Symfony Mapped Route Parameters should be used as replacement. at /opt/kimai/vendor/doctrine/doctrine-bundle/src/DependencyInjection/DoctrineExtension.php:533)"} {"channel":"deprecation"}
kimai-kimai  | [2024-09-26T10:34:40.814403+00:00] deprecation.INFO: User Deprecated: Since twig/twig 3.12: Twig Filter "spaceless"is deprecated in /opt/kimai/vendor/kevinpapst/tabler-bundle/templates/components/button.html.twig at line 4. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since twig/twig 3.12: Twig Filter \"spaceless\" is deprecated in /opt/kimai/vendor/kevinpapst/tabler-bundle/templates/components/button.html.twig at line 4. at / ecated in /opt/kimai/vendor/kevinpapst/tabler-bundle/templates/components/actions.html.twig at line 19. at /opt/kimai/vendor/twig/twig/src/ExpressionParser.php:830)"} {"channel":"deprecation"}
kimai-kimai  |  [OK] Cache for the "prod" environment (debug=false) was successfully cleared.
kimai-kimai  |
kimai-kimai  |
kimai-kimai  |  // Warming up the cache for the prod environment with debug false
kimai-kimai  |
kimai-kimai  |  [OK] Cache for the "prod" environment (debug=false) was successfully warmed.
kimai-kimai  |
kimai-kimai  |
kimai-kimai  |  [OK] Kimai config was reloaded
kimai-kimai  |
kimai-kimai  | + chown -R 1944:100 /opt/kimai/var
kimai-kimai  | + '[' -e /use_apache ']'
kimai-kimai  | + '[' -e /use_fpm ']'
kimai-kimai  | + exec php-fpm
kimai-kimai  | [26-Sep-2024 12:34:54] NOTICE: fpm is running, pid 1
kimai-kimai  | [26-Sep-2024 12:34:54] NOTICE: ready to handle connections
kimai-kimai  | 127.0.0.1 -  26/Sep/2024:12:34:58 +0200 "GET /ping" 404
```

</p>
</details>

This is my docker-compose:

<details>
<p>

```yaml
services:
  mysql:
    container_name: "kimai-mysql"
    image: mysql:8
    restart: unless-stopped
    user: "1944:100"
    volumes:
      - "/home/services/kimai/volumes/mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: kimai
      MYSQL_USER: "<redacted>"
      MYSQL_PASSWORD: "<redacted>"
      MYSQL_ROOT_PASSWORD: "<redacted>"
    command: --default-storage-engine innodb
    healthcheck:
      test: "mysqladmin -p<redacted> ping -h localhost"
      interval: 60s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    container_name: "kimai-kimai"
    image: kimai/kimai2:latest
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - "/home/services/kimai/volumes/data:/opt/kimai/var/data"
      - "/home/services/kimai/volumes/plugins:/opt/kimai/var/plugins"
      - "/home/services/kimai/local.yaml:/opt/kimai/config/packages/local.yaml"
    ports:
      - "172.17.0.1:28944:8001"
    environment:
      ADMINMAIL: "<redacted>"
      ADMINPASS: "<redacted>"
      DATABASE_URL: "mysql://<redacted>:<redacted>@mysql/kimai?charset=utf8mb4&serverVersion=8.3.0"
      TRUSTED_HOSTS: "localhost,127.0.0.1,kimai.catboy.house"
      TZ: "Europe/Berlin"
      MAILER_URL: "<redacted>"
      MAILER_FROM: "<redacted>"
      USER_ID: "1944"
      GROUP_ID: "100"
      memory_limit: 1G
```

</p>
</details>

And here is my Caddy configuration:

<details>
<p>

```
kimai.catboy.house {
    reverse_proxy 172.17.0.1:28944 {
        flush_interval -1
    }
}⏎
```

</p>
</details>

Thanks for any help :)
