### DISCUSSION TITLE
Height availability and cache

### DISCUSSION THREAD

**Discussion by robjuz** [kimai/kimai#5124] [Docker]
### Describe the problem

This is more a question.

In the 2.23.0 version, the redis php plugin got removed. I was wondering, how kimai is using the caching system. In my kubernetes deployment, I added a redis container and configured the `app.cache` to point to the redis. Now I'm wondering if I should remove it?

### Describe your setup and add your Docker compose file (redact your credentials)

```yaml
apiVersion: v1
kind: ConfigMap
data:
  local.yaml: |-
   monolog:
        handlers:
            main:
                path: php://stderr
    framework:
      cache:
        app: cache.adapter.redis
        system: cache.adapter.redis
        default_redis_provider: redis://kimai-redis-master:6379/1
        pools:
          app.cache.redis:
            adapter: cache.adapter.redis
            public: false
            default_lifetime: 120
          doctrine.result_cache_pool:
            adapter: app.cache.redis
          doctrine.system_cache_pool:
            adapter: app.cache.redis
```
