### DISCUSSION TITLE
Docker Compose Web UI Corrupted

### DISCUSSION THREAD

**Discussion by MyVizDrake** [kimai/kimai#5128] [Docker]
Not sure if this is the right place, but ...

Was successfully using a docker compose deployment for weeks. Was working today and then when I needed to relogin the interface got all corrupted.

Login Screen

![image](https://github.com/user-attachments/assets/2fb3156d-8e3c-414d-b7e6-bb532917f8d1)

Timesheet

![image](https://github.com/user-attachments/assets/256fd0fe-81ba-4e2d-829d-9efa0fe1a80e)

my compose.yaml
```
services:
  sqldb:
    image: mysql:8.3
    container_name: kimai_sqldb
    networks:
      - <docker network>
    volumes:
      - /mnt/data/kimai/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=<db>
      - MYSQL_USER=<dbuser>
      - MYSQL_PASSWORD=<dbpasswd>
      - MYSQL_ROOT_PASSWORD=<rootpasswd>
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
  kimai:
    image: kimai/kimai2:apache
    container_name: kimai
    networks:
      - <docker network>
    volumes:
      - /mnt/data/kimai:/opt/kimai/var/data
      #ports:
      #- 8001:8001
    environment:
      - ADMINMAIL=<adminmail>
      - ADMINPASS=<adminpasswd>
      - DATABASE_URL=mysql://<dbuser>:<dbpasswd>@kimai_sqldb/kimai?charset=utf8mb4&serverVersion=8.3.0
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1
    restart: unless-stopped
networks:
  <docker network>:
    external: true
```
I can login to the mysql db as root ..

![image](https://github.com/user-attachments/assets/d1c2d006-f307-4ed5-9465-3a0a1b07131a)

... and as the kimai database user

```
root@docker:/opt/stacks# docker exec -it kimai_sqldb sh
sh-4.4# mysql kimai -u <dbuser>-p
Enter password:
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 49
Server version: 8.3.0 MySQL Community Server - GPL

Copyright (c) 2000, 2024, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show tables;
+---------------------------+
| Tables_in_kimai           |
+---------------------------+
| kimai2_access_token       |
| kimai2_activities         |
| kimai2_activities_meta    |
| kimai2_activities_rates   |
| kimai2_activities_teams   |
| kimai2_bookmarks          |
| kimai2_configuration      |
| kimai2_customers          |
| kimai2_customers_comments |
| kimai2_customers_meta     |
| kimai2_customers_rates    |
| kimai2_customers_teams    |
| kimai2_invoice_templates  |
| kimai2_invoices           |
| kimai2_invoices_meta      |
| kimai2_projects           |
| kimai2_projects_comments  |
| kimai2_projects_meta      |
| kimai2_projects_rates     |
| kimai2_projects_teams     |
| kimai2_roles              |
| kimai2_roles_permissions  |
| kimai2_sessions           |
| kimai2_tags               |
| kimai2_teams              |
| kimai2_timesheet          |
| kimai2_timesheet_meta     |
| kimai2_timesheet_tags     |
| kimai2_user_preferences   |
| kimai2_users              |
| kimai2_users_teams        |
| kimai2_working_times      |
| migration_versions        |
+---------------------------+
33 rows in set (0.00 sec)
```

it is looking like the db is hosed?

From the console log of the stack in dockge

```
kimai_sqldb  | 2024-10-23T13:27:31.166903Z 33 [ERROR] [MY-012592] [InnoDB] Operating system error number 13 in a file operation.
kimai_sqldb  | 2024-10-23T13:27:31.166914Z 33 [ERROR] [MY-012595] [InnoDB] The error means mysqld does not have the access rights to the directory.
kimai_sqldb  | 2024-10-23T13:27:31.166925Z 33 [Warning] [MY-012093] [InnoDB] Cannot open './kimai/kimai2_sessions.ibd'. Have you deleted .ibd files under a running mysqld server?
kimai_sqldb  | 2024-10-23T13:27:31.166938Z 33 [ERROR] [MY-012157] [InnoDB] Trying to do I/O to a tablespace which exists without an .ibd data file. I/O type: read, page: [page id: space=78, page number=4], I/O length: 16384 bytes
kimai_sqldb  | 2024-10-23T13:27:31.166952Z 33 [ERROR] [MY-011966] [InnoDB] trying to read page [page id: space=78, page number=4] in nonexisting or being-dropped tablespace
kimai_sqldb  | 2024-10-23T13:27:31.166965Z 33 [ERROR] [MY-011899] [InnoDB] [FATAL] Unable to read page [page id: space=78, page number=4] into the buffer pool after 100 attempts. The most probable cause of this error may be that the table has been corrupted. Or, the table was compressed with with an algorithm that is not supported by this instance. If it is not a decompress failure, you can try to fix this problem by using innodb_force_recovery. Please see http://dev.mysql.com/doc/refman/8.3/en/ for more details. Aborting...
kimai_sqldb  | 2024-10-23T13:27:31.166983Z 33 [ERROR] [MY-013183] [InnoDB] Assertion failure: buf0buf.cc:4081:ib::fatal triggered thread 140649046177536
kimai_sqldb  | InnoDB: We intentionally generate a memory trap.
kimai_sqldb  | InnoDB: Submit a detailed bug report to http://bugs.mysql.com.
kimai_sqldb  | InnoDB: If you get repeated assertion failures or crashes, even
kimai_sqldb  | InnoDB: immediately after the mysqld startup, there may be
kimai_sqldb  | InnoDB: corruption in the InnoDB tablespace. Please refer to
kimai_sqldb  | InnoDB: http://dev.mysql.com/doc/refman/8.3/en/forcing-innodb-recovery.html
kimai_sqldb  | InnoDB: about forcing recovery.
kimai_sqldb  | 2024-10-23T13:27:31Z UTC - mysqld got signal 6 ;
kimai_sqldb  | Most likely, you have hit a bug, but this error can also be caused by malfunctioning hardware.
kimai_sqldb  | BuildID[sha1]=1428545f217a1168928a1715e8fa851a4c11e276
kimai_sqldb  | Thread pointer: 0x7feb1800db60
kimai_sqldb  | Attempting backtrace. You can use the following information to find out
kimai_sqldb  | where mysqld died. If you see no messages after this, something went
kimai_sqldb  | terribly wrong...
kimai_sqldb  | stack_bottom = 7feb686f6c10 thread_stack 0x100000
kimai_sqldb  |  #0 0x102e831 <unknown>
kimai_sqldb  |  #1 0x102ea84 <unknown>
kimai_sqldb  |  #2 0x21c2a0d <unknown>
kimai_sqldb  |  #3 0x2425f98 <unknown>
kimai_sqldb  |  #4 0x242888e <unknown>
kimai_sqldb  |  #5 0x2481516 <unknown>
kimai_sqldb  |  #6 0x248c2d7 <unknown>
kimai_sqldb  |  #7 0x248c3b4 <unknown>
kimai_sqldb  |  #8 0x248d1e9 <unknown>
kimai_sqldb  |  #9 0x246c3b0 <unknown>
kimai_sqldb  |  #10 0x23a003c <unknown>
kimai_sqldb  |  #11 0x2236555 <unknown>
kimai_sqldb  |  #12 0x114f5e7 <unknown>
kimai_sqldb  |  #13 0xe73475 <unknown>
kimai_sqldb  |  #14 0xe735c0 <unknown>
kimai_sqldb  |  #15 0xe9748c <unknown>
kimai_sqldb  |  #16 0xeac1c5 <unknown>
kimai_sqldb  |  #17 0xeade53 <unknown>
kimai_sqldb  |  #18 0xf12bc0 <unknown>
kimai_sqldb  |  #19 0xf9190c <unknown>
kimai_sqldb  |  #20 0xf11ac3 <unknown>
kimai_sqldb  |  #21 0xf1caee <unknown>
kimai_sqldb  |  #22 0xeb7054 <unknown>
kimai_sqldb  |  #23 0xebaaca <unknown>
kimai_sqldb  |  #24 0xebc9eb <unknown>
kimai_sqldb  |  #25 0xebd42a <unknown>
kimai_sqldb  |  #26 0x101e627 <unknown>
kimai_sqldb  |  #27 0x29253e3 <unknown>
kimai_sqldb  |  #28 0x7feb9c11b1d9 <unknown>
kimai_sqldb  |  #29 0x7feb9a6c9e72 <unknown>
kimai_sqldb  |  #30 0xffffffffffffffff <unknown>
kimai_sqldb  | 
kimai_sqldb  | Trying to get some variables.
kimai_sqldb  | Some pointers may be invalid and cause the dump to abort.
kimai_sqldb  | Query (7feb18312fa0): SELECT data, lifetime FROM kimai2_sessions WHERE id = 'h2f5csuu8phh05gktods8u9i79'
kimai_sqldb  | Connection ID (thread ID): 33
kimai_sqldb  | Status: NOT_KILLED
kimai_sqldb  | 
kimai_sqldb  | The manual page at http://dev.mysql.com/doc/mysql/en/crashing.html contains
kimai_sqldb  | information that should help you find out what is causing the crash.
```
Is the db hosed and I need to just start over or ... 

Seems something is up with the DB but a DB issue wrecking the UI seems weird to me

Thoughts?
