### DISCUSSION TITLE
Receiving "An authentication exception occurred." with no errors when attempting to sign in through Azure SAML.

### DISCUSSION THREAD

**Discussion by ZacharySeebeck2020** [kimai/kimai#5239] [Questions & Answers]
Hey all. I'm attempting to set up authentication through Azure, but I'm running into a roadblock that I can't seem to get pass. I can see the "Login With Azure" button show up, it properly goes through the flow, even authentication logs in Azure show that it was successful. But when I get back to Kimai, all I can see is "An authentication exception occurred." With no logs in the console what so ever. I've included my configuration, in case there's something wrong there. Any help would be appreciated. Thanks!

```
kimai:
    saml:
        provider: microsoft
        activate: true
        title: 'Login with FCM'
        baseurl: 'https://*********.***.***/auth/saml'
        mapping:
            - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name, kimai: username }
            - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress, kimai: email }
            - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname, kimai: alias }
            - { saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/displayname, kimai: title }
        roles:
            resetOnLogin: true
            attribute: http://schemas.microsoft.com/ws/2008/06/identity/claims/groups
            mapping:
                - { saml: xxxxxxxx-yyyy-xxxx-yyyy-xxxxxxxxxxxx, kimai: ROLE_ADMIN }
                - { saml: Azure-Group-Object-Id, kimai: ROLE_TEAMLEAD }
        connection:
            idp:
                entityId: 'https://sts.windows.net/**********-****-***-****-*****/'
                singleSignOnService:
                    url: 'https://login.microsoftonline.com/**********-****-***-****-*****'
                x509cert: 'Insert the cert here. Removed for privacy.'
            sp:
                entityId: 'https://*********.***.***/auth/saml/metadata'
                assertionConsumerService:
                    url: 'https://*********.***.***/auth/saml/acs'
                singleLogoutService:
                    url: 'https://*********.***.***/auth/saml/logout'
            security:
                requestedAuthnContext: false
```
