### DISCUSSION TITLE
ErrorException: Invalid configuration for path "kimai.data_dir" when loading demo database

### DISCUSSION THREAD

**Discussion by kernie** [kimai/kimai#5271] [Docker] [answered]
Hello,

I'm applying a "standard" docker-compose file to install Kimai 2.27 in a container:

```
services:

  sqldb:
    image: mysql:8.3
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    command: --default-storage-engine innodb
    restart: unless-stopped
    # ports:
    #   - 3306:3306
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    # image: kimai/kimai2:apache
    image: kimai/kimai2:dev
    ports:
      - 8001:8001
    environment:
      - ADMINMAIL=${ADMIN_EMAIL}
      - ADMINPASS=${ADMIN_PASSWORD}
      - "DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@sqldb/${DATABASE_NAME}?charset=utf8mb4&serverVersion=8.3"
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1
    volumes:
      - public:/opt/kimai/public
      - plugins:/opt/kimai/var/plugins
      - invoices:/opt/kimai/var/invoices
      - data:/opt/kimai/var/data
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    restart: unless-stopped
    depends_on:
      - sqldb

volumes:
    public:
    mysql:
    data:
    plugins:
    invoices:
```
combined with a dotenv file:
```
DATABASE_NAME=kimai
DATABASE_USER=kimaiuser
DATABASE_PASSWORD=kimaipassword
DATABASE_ROOT_PASSWORD=changemeplease
APP_ENV=dev
ADMIN_EMAIL=admin@kimai.local
ADMIN_PASSWORD=changemeplease
```

The container builds without error and I can login in the browser.

Then, I try to load the demo database with ` docker exec -ti docker-kimai-1 /opt/kimai/bin/console kimai:reset:test --env=test --no-interaction -vvv` where "docker-kimai-1" is my kimai docker instance.

The error I get is:
```
In AppExtension.php line 30:
                                                                                                                                    
  [ErrorException]                                                                                                                  
  User Notice: Found invalid "kimai" configuration: Invalid configuration for path "kimai.data_dir": Data directory does not exist  
                                                                                                                                    

Exception trace:
  at /opt/kimai/src/DependencyInjection/AppExtension.php:30
 App\DependencyInjection\AppExtension->load() at /opt/kimai/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:76
 Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process() at /opt/kimai/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:42
 Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process() at /opt/kimai/vendor/symfony/dependency-injection/Compiler/Compiler.php:80
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /opt/kimai/vendor/symfony/dependency-injection/ContainerBuilder.php:767
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /opt/kimai/vendor/symfony/http-kernel/Kernel.php:506
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /opt/kimai/vendor/symfony/http-kernel/Kernel.php:771
 Symfony\Component\HttpKernel\Kernel->preBoot() at /opt/kimai/vendor/symfony/http-kernel/Kernel.php:126
 Symfony\Component\HttpKernel\Kernel->boot() at /opt/kimai/vendor/symfony/framework-bundle/Console/Application.php:190
 Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at /opt/kimai/vendor/symfony/framework-bundle/Console/Application.php:72
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /opt/kimai/vendor/symfony/console/Application.php:175
 Symfony\Component\Console\Application->run() at /opt/kimai/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at /opt/kimai/vendor/autoload_runtime.php:29
 require_once() at /opt/kimai/bin/console:13
```
Any idea what is going wrong?

Thanks!
