### DISCUSSION TITLE
You must configure the check path in your firewall SAML Login

### DISCUSSION THREAD

**Discussion by rn232** [kimai/kimai#5336] [Docker]
### Describe the issue

Hello,

I'm trying to configure SAML on Kimai (with Docker), but I have this error : `request.CRITICAL: Uncaught PHP Exception RuntimeException: "You must configure the check path in your firewall." at SamlController.php line 104 {"exception":"[object] (RuntimeException(code: 0): You must configure the check path in your firewall. at /opt/kimai/src/Controller/Auth/SamlController.php:104)"} {"channel":"request"`

This is my configuration file :

```yaml
# Optionally add this for docker debug-logging
monolog:
  handlers:
    main:
      path: php://stderr

kimai:
    saml:
        activate: true
        title: Login with authentik
        mapping:
            - {
                  saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress,
                  kimai: email,
              }
            - {
                  saml: $http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name,
                  kimai: alias,
              }
        roles:
            attribute: http://schemas.xmlsoap.org/claims/Group
            mapping:
                # Insert your roles here (ROLE_USER is added automatically)
                - { saml: admin.group, kimai: ROLE_ADMIN }
        connection:
            # You SAML provider
            # Your authentik instance, replace https://authentik.company with your authentik URL
            idp:
                entityId: "https://auth.REDACTED.ovh/"
                singleSignOnService:
                  url: "https://auth.REDACTED.ovh/application/saml/kimai/sso/binding/redirect/"
                  binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                # the "single logout" feature was not yet tested, if you want to help, please let me know!
                singleLogoutService:
                  url: "https://auth.REDACTED.ovh/application/saml/kimai/slo/binding/redirect/"
                  binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                # Signing certificate from *Advanced protocol settings*
                x509cert: "REDACTED"
            # Your Kimai instance, replace https://kimai.company with your Kimai URL
            sp:
                entityId: "https://kimai.REDACTED.ovh"
                assertionConsumerService:
                    url: "https://kimai.REDACTED.ovh/auth/saml/acs"
                    binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                singleLogoutService:
                    url: "https://kimai.REDACTED.ovh/auth/saml/logout"
                    binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                #privateKey: ''
            # only set baseurl, if auto-detection doesn't work
            baseurl: "https://kimai.REDACTED.ovh/auth/saml/"
            strict: false
            debug: true
            security:
                nameIdEncrypted: false
                authnRequestsSigned: false
                logoutRequestSigned: false
                logoutResponseSigned: false
                wantMessagesSigned: false
                wantAssertionsSigned: false
                wantNameIdEncrypted: false
                requestedAuthnContext: true
                signMetadata: false
                wantXMLValidation: true
                signatureAlgorithm: "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"
                digestAlgorithm: "http://www.w3.org/2001/04/xmlenc#sha256"
            contactPerson:
                technical:
                    givenName: "Kimai Admin"
                    emailAddress: "REDACTED"
            organization:
                en:
                    name: "Kimai"
                    displayname: "Kimai"
                    url: "https://kimai.REDACTED.ovh"
                      #security:
                      #firewalls:
                      #secured_area:
                      #logout:
                      #path: /auth/saml/logout
                      #target: homepage
                      #enable_csrf: false
```
If you need more information don't hesitate to ask.

Has anyone ever had this problem?

Thank you for your help and have a nice day!

### I already tried

- [x] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [x] I've searched for similar issues in this repository.
- [x] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.28.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.4

### Logfile

 [ERROR] email: This e-mail address is already in use.  (idk if it can be because of it)                        
 [ERROR] username: The username is already used. (same)

request.CRITICAL: Uncaught PHP Exception RuntimeException: "You must configure the check path in your firewall." at SamlController.php line 104 {"exception":"[object] (RuntimeException(code: 0): You must configure the check path in your firewall. at /opt/kimai/src/Controller/Auth/SamlController.php:104)"} {"channel":"request"

### Screenshots

![Image](https://github.com/user-attachments/assets/fdb0c928-c0bb-4607-a89a-8270aac4e595)
