### DISCUSSION TITLE
Need help with Kimai + Nginx Proxy Manager

### DISCUSSION THREAD

**Discussion by Marcel-Lohmann** [kimai/kimai#5380] [Docker]
Hello everyone,

Kimai works wonderfully when I call it “locally”, i.e. via http://192.168.178.20:8001.
My Docker Compose looks like this:

```
services:

  sqldb:
    image: mysql:8.3
    volumes:
      - /volume1/docker/kimai/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2:apache
    volumes:
      - /volume1/docker/kimai/data:/opt/kimai/var/data
      - /volume1/docker/kimai/plugins:/opt/kimai/var/plugins
    ports:
      - 8001:8001
    environment:
      - ADMINMAIL=MyEMail@web.de
      - ADMINPASS=SuperSecret1234
      - "DATABASE_URL=mysql://kimaiuser:kimaipassword@sqldb/kimai?charset=utf8mb4&serverVersion=8.3.0"
    restart: unless-stopped

volumes:
  data:
  mysql:
  plugins:
```

And my Nginx Proxy Manager settings look like this.

![grafik](https://github.com/user-attachments/assets/bb392a0b-2e92-4709-8afd-f3a33e487c40)
![grafik](https://github.com/user-attachments/assets/406febee-3916-42c2-a73d-8934125a5856)
![grafik](https://github.com/user-attachments/assets/69b4617b-92ca-4a18-8663-cfb24bed453a)
![grafik](https://github.com/user-attachments/assets/f455b9ae-2464-4aeb-b673-c6004f711cfc)

I've read everything I could find on the topic mentioned in the subject line, but I can't get any further.
With other tools (Vaultwarden, Immich, Docmost, Paperless,..) it was no problem to access the tools externally.

I see the following in the logs when I try to access Kimai via my domain:

> localhost:8001 127.0.0.1 - - [26/Feb/2025:19:35:47 +0100] "GET / HTTP/1.1" 302 626 "-" "curl/7.88.1"
> 
> localhost:8001 172.27.0.1 - - [26/Feb/2025:19:35:57 +0100] "GET / HTTP/1.1" 302 682 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0"
> 
> localhost:8001 172.27.0.1 - - [26/Feb/2025:19:35:57 +0100] "GET /de/homepage HTTP/1.1" 302 832 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:135.0) Gecko/20100101 Firefox/135.0"
> 
> localhost:8001 127.0.0.1 - - [26/Feb/2025:19:36:07 +0100] "GET / HTTP/1.1" 302 626 "-" "curl/7.88.1"

Can someone please help me here?
