### ISSUE TITLE
LDAP jpegphoto avatars support

### ISSUE THREAD

**Issue by vvirehead** [kimai/kimai#1405]
**Is your feature request related to a problem? Please describe.**
Built-in LDAP avatars are not supported.

**Describe the solution you'd like**
I would like to have jpegphoto LDAP attribute support for avatar purposes.

**Describe alternatives you've considered**
Alternative avatar system support (ie. gravatar, based on user email)

**Additional context**
Right now data from jpegphoto is loaded to web interface but it's not displayed properly.

local.yaml

```yaml
kimai:
    ldap:
        user:
            attributes:
                - { ldap_attr: jpegphoto, user_method: setAvatar }
```
