### ISSUE TITLE
Add Ldap support

### ISSUE THREAD

**Issue by anmol26s** [kimai/kimai#193]
Hi
It would be nice to have Ldap support for the app.

**Comment by kevinpapst** [comment]
Someone could try to configure security to authenticate against LDAP: https://symfony.com/doc/current/security/ldap.html

```
composer require symfony/ldap
```

When using this authentication method I believe its enough to create users with the same name in Kimai. Advanced functionality would be to create new users on the fly, I believe there is no built-in functionality for this in symfony/ldap.

**Comment by marquesmatheus** [comment]
Is there a guide to used LDAP on the kimai2 instead of the source of symfony?

**Comment by marquesmatheus** [comment]
I

> Hi
> It would be nice to have Ldap support for the app.

Sure it will be perfect!.

**Comment by DERanselmus** [comment]
Has anyone made progress on this issue?

I've added to config/services.yaml
```
 Symfony\Component\Ldap\Ldap:
        arguments: ['@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter']
    Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
        arguments:
                 host: 'ldap.xxxxxxx.de'
                 port: 636
                 encryption: tls
                 options:
                     protocol_version: 3
                     referrals: false
```
and to config/packages/security.yaml
```
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        ldap_users:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: 'dc=aoag,dc=local'
                default_roles: 'Users'
                uid_key: 'uid'
                filter: '(&({uid_key}={uid})(objectclass=person))'
        chain_provider:
            chain:
                providers: [fos_userbundle,ldap_users]
```
But I can't even see a request go out to the ldap server. 

I am not familiar with Symfony. Do I have to rebuilt the application upon changing yaml files?
Is there a way to log or debug this request? var/log/prod.log does not show anything, nor stdout or apache log.
