### ISSUE TITLE
kimai2 white screen

### ISSUE THREAD

**Issue by swoop124** [kimai/kimai#3839]
### Describe the issue

Hello,

i use Kimai2 since a year or so an it worked great so far. but since yesterday, when i open the kimia2 homepage there is only a white screen.

Kimai2 is installed using docker-compse:
```
version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=user
      - MYSQL_PASSWORD=PW
      - MYSQL_ROOT_PASSWORD=PPW
    volumes:
      - /daten/docker/kimai2/db_data:/var/lib/mysql
      - /daten/docker/kimai2:/db
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -pPPW ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  nginx: 
    image: tobybatch/nginx-fpm-reverse-proxy
    ports:
      - 8001:80
    volumes:
      - /daten/docker/kimai2/public:/opt/kimai/public:ro
    restart: unless-stopped
    depends_on:
      - kimai
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai: # This is the latest FPM image of kimai
    image: kimai/kimai2:fpm
    environment:
      - ADMINMAIL=office@mydomain.tld
      - ADMINPASS=PPW
      - DATABASE_URL=mysql://user:PW@sqldb/kimai
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1,docker3.mydomain.tld,192.168.251.59,kimai.mydomain.tld
    volumes:
      - /daten/docker/kimai2/public:/opt/kimai/public
      - /daten/docker/kimai2/var/invoices:/opt/kimai/var/invoices
      - /daten/docker/kimai2/var/data:/opt/kimai/var/data
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    restart: unless-stopped

  postfix:
    image: catatnight/postfix:latest
    environment:
      maildomain: mydomain.tld
      smtp_user: kimai:kimai
    restart: unless-stopped
```

As i said, it was working til yesterday afternoon, then i had to reboot the server. After the reboot this problem was present.

After this happened, i tried debian update and upgrade and moved to a second docker server i have.

Please, any help, i need to enter my tasks of today. 

thx

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2 (latest)

### How do you run Kimai?

Docker

### Which PHP version are you using?

Unknown

### Logfile

Container started
```
Creating network "kimai2_default" with the default driver
Creating kimai2_sqldb_1   ... done
Creating kimai2_postfix_1 ... done
Creating kimai2_kimai_1   ... done
Creating kimai2_nginx_1   ... done
Attaching to kimai2_postfix_1, kimai2_sqldb_1, kimai2_kimai_1, kimai2_nginx_1
kimai_1    |
kimai_1    | Wait for MySQL DB connection ...
kimai_1    | Testing DB:** new \PDO(mysql:host=sqldb;dbname=kimai;port=3306, kimaiuser, lCJW459bWOjPHQIevLflPgYs, [ \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ]);*Connection established 
kimai_1    | /startup.sh: line 41: [: : integer expression expected
kimai_1    | /startup.sh: line 44: assets/monolog.yaml: No such file or directory
kimai_1    | tar: public/touch-icon-512x512.png: Cannot open: Permission denied
kimai_1    | tar: public/apple-touch-icon-precomposed.png: Cannot open: Permission denied
kimai_1    | tar: public/.htaccess: Cannot open: File exists
kimai_1    | tar: public/favicon-16x16.png: Cannot open: Permission denied
kimai_1    | tar: public/index.php: Cannot open: File exists
kimai_1    | tar: public/manifest.json: Cannot open: File exists
kimai_1    | tar: public/favicon.ico: Cannot open: File exists
kimai_1    | tar: public/browserconfig.xml: Cannot open: File exists
kimai_1    | tar: public/touch-icon-192x192.png: Cannot open: File exists
kimai_1    | tar: public/wizard: Cannot mkdir: Permission denied
kimai_1    | tar: public/wizard: Cannot mkdir: Permission denied
kimai_1    | tar: public/wizard/time-management.png: Cannot open: No such file or directory
kimai_1    | tar: public/wizard: Cannot mkdir: Permission denied
kimai_1    | tar: public/wizard/done.png: Cannot open: No such file or directory
kimai_1    | tar: public/touch-icon-180x180.png: Cannot open: Permission denied
kimai_1    | tar: public/favicon-32x32.png: Cannot open: File exists
kimai_1    | tar: public/apple-touch-icon.png: Cannot open: File exists
kimai_1    | tar: public/robots.txt: Cannot open: File exists
kimai_1    | tar: public: Cannot utime: Operation not permitted
kimai_1    | tar: Exiting with failure status due to previous errors
kimai_1    |
kimai_1    | Kimai installation running ...
kimai_1    | ==============================
kimai_1    |
kimai_1    | Database `kimai` for connection named default already exists. Skipped.
kimai_1    |
kimai_1    |  [OK] Already at the latest version ("DoctrineMigrations\Version20230126002049")
kimai_1    |
kimai_1    |
kimai_1    |  Rebuilding your cache, please be patient ...
kimai_1    |
kimai_1    |  // Clearing the cache for the prod environment with debug false
kimai_1    |
postfix_1  | find: `/etc/postfix/certs': No such file or directory
sqldb_1    | 2023-02-10 16:07:36+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.41-1.el7 started.
postfix_1  | find: `/etc/opendkim/domainkeys': No such file or directory
sqldb_1    | 2023-02-10 16:07:36+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
postfix_1  | 2023-02-10 16:07:36,442 CRIT Supervisor running as root (no user in config file)
postfix_1  | 2023-02-10 16:07:36,442 WARN Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
postfix_1  | 2023-02-10 16:07:36,466 INFO RPC interface 'supervisor' initialized
postfix_1  | 2023-02-10 16:07:36,466 CRIT Server 'unix_http_server' running without any HTTP authentication checking
postfix_1  | 2023-02-10 16:07:36,467 INFO supervisord started with pid 24
sqldb_1    | 2023-02-10 16:07:36+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.41-1.el7 started.
postfix_1  | 2023-02-10 16:07:37,478 INFO spawned: 'postfix' with pid 34
postfix_1  | 2023-02-10 16:07:37,479 INFO spawned: 'rsyslog' with pid 35
sqldb_1    | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
sqldb_1    | 2023-02-10T16:07:36.606912Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
sqldb_1    | 2023-02-10T16:07:36.608096Z 0 [Note] mysqld (mysqld 5.7.41) starting as process 1 ...
sqldb_1    | 2023-02-10T16:07:36.611111Z 0 [Note] InnoDB: PUNCH HOLE support available
sqldb_1    | 2023-02-10T16:07:36.611130Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
sqldb_1    | 2023-02-10T16:07:36.611135Z 0 [Note] InnoDB: Uses event mutexes
sqldb_1    | 2023-02-10T16:07:36.611138Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
sqldb_1    | 2023-02-10T16:07:36.611142Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.12
sqldb_1    | 2023-02-10T16:07:36.611148Z 0 [Note] InnoDB: Using Linux native AIO
sqldb_1    | 2023-02-10T16:07:36.611361Z 0 [Note] InnoDB: Number of pools: 1
sqldb_1    | 2023-02-10T16:07:36.611447Z 0 [Note] InnoDB: Using CPU crc32 instructions
sqldb_1    | 2023-02-10T16:07:36.612800Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
sqldb_1    | 2023-02-10T16:07:36.620743Z 0 [Note] InnoDB: Completed initialization of buffer pool
sqldb_1    | 2023-02-10T16:07:36.622325Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().        
sqldb_1    | 2023-02-10T16:07:36.640375Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
sqldb_1    | 2023-02-10T16:07:36.781923Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
sqldb_1    | 2023-02-10T16:07:36.781983Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
sqldb_1    | 2023-02-10T16:07:36.896241Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
sqldb_1    | 2023-02-10T16:07:36.896826Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
sqldb_1    | 2023-02-10T16:07:36.896834Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
sqldb_1    | 2023-02-10T16:07:36.897068Z 0 [Note] InnoDB: Waiting for purge to start
sqldb_1    | 2023-02-10T16:07:36.947184Z 0 [Note] InnoDB: 5.7.41 started; log sequence number 22661149
sqldb_1    | 2023-02-10T16:07:36.947416Z 0 [Note] Plugin 'FEDERATED' is disabled.
sqldb_1    | 2023-02-10T16:07:36.947600Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
sqldb_1    | 2023-02-10T16:07:36.962646Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
sqldb_1    | 2023-02-10T16:07:36.962662Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
sqldb_1    | 2023-02-10T16:07:36.962665Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
sqldb_1    | 2023-02-10T16:07:36.962667Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.
sqldb_1    | 2023-02-10T16:07:36.963655Z 0 [Warning] CA certificate ca.pem is self signed.
sqldb_1    | 2023-02-10T16:07:36.963688Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
sqldb_1    | 2023-02-10T16:07:36.963897Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
sqldb_1    | 2023-02-10T16:07:36.963921Z 0 [Note] IPv6 is available.
sqldb_1    | 2023-02-10T16:07:36.963929Z 0 [Note]   - '::' resolves to '::';
sqldb_1    | 2023-02-10T16:07:36.963943Z 0 [Note] Server socket created on IP: '::'.
sqldb_1    | 2023-02-10T16:07:36.999992Z 0 [Note] InnoDB: Buffer pool(s) load completed at 230210 16:07:36
sqldb_1    | 2023-02-10T16:07:37.010233Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
sqldb_1    | 2023-02-10T16:07:37.065239Z 0 [Warning] Optional native table 'performance_schema'.'processlist' has the wrong structure or is missing.
sqldb_1    | 2023-02-10T16:07:37.065971Z 0 [Note] Event Scheduler: Loaded 0 events
sqldb_1    | 2023-02-10T16:07:37.066123Z 0 [Note] mysqld: ready for connections.
sqldb_1    | Version: '5.7.41'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
postfix_1  | 2023-02-10 16:07:38,544 INFO success: postfix entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix_1  | 2023-02-10 16:07:38,544 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
postfix_1  | 2023-02-10 16:07:38,578 INFO exited: postfix (exit status 1; not expected)
postfix_1  | 2023-02-10 16:07:39,580 INFO spawned: 'postfix' with pid 102
postfix_1  | 2023-02-10 16:07:40,643 INFO success: postfix entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
kimai_1    | PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /opt/kimai/var/cache/pro_/twig/60/60cede130964e7514cc23eb34d2257a4.php on line 82
kimai_1    | PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /opt/kimai/vendor/symfony/var-dumper/Dumper/CliDumper.php on line 1
kimai_1    | 
kimai_1    | Kimai updates running ...
kimai_1    | =========================
kimai_1    |
kimai_1    | 
kimai_1    |  [OK] Already at the latest version ("DoctrineMigrations\Version20230126002049")
kimai_1    |
kimai_1    |
kimai_1    |  Rebuilding your cache, please be patient ...
kimai_1    |
kimai_1    |  // Clearing the cache for the prod environment with debug false
kimai_1    |
kimai_1    | PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /opt/kimai/vendor/twig/twig/src/Node/PrintNode.php on line 27
kimai_1    | PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /opt/kimai/vendor/symfony/error-handler/Error/OutOfMemoryError.php on line 1
kimai_1    | 
kimai_1    |
kimai_1    |   The command "kimai:reset:locales" does not exist.
kimai_1    |
kimai_1    |
kimai_1    | Kimai2 ready
kimai_1    | 
kimai_1    | Reloading configurations ...
kimai_1    | ============================
kimai_1    |
kimai_1    | 
kimai_1    |  [OK] All 25 YAML files contain valid syntax.
kimai_1    |
kimai_1    |
kimai_1    | 
kimai_1    |  [OK] All 513 XLIFF files contain valid syntax.
kimai_1    |
kimai_1    |
kimai_1    |  Rebuilding your cache, please be patient ...
kimai_1    | 
kimai_1    |  // Clearing the cache for the prod environment with debug false
kimai_1    |
nginx_1    | 192.168.240.5 - - [10/Feb/2023:16:07:58 +0000] "GET /health HTTP/1.1" 200 5 "-" "Wget" "-"
kimai_1    | PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /opt/kimai/vendor/twig/twig/src/Node/Expression/ConstantExpression.php on line 21
kimai_1    | PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /opt/kimai/vendor/monolog/monolog/src/Monolog/Formatter/LineFormatter.php on line 61
kimai_1    | [10-Feb-2023 17:07:58] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
kimai_1    | [10-Feb-2023 17:07:58] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
kimai_1    | [10-Feb-2023 17:07:58] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
kimai_1    | [10-Feb-2023 17:07:58] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
kimai_1    | [10-Feb-2023 17:07:58] NOTICE: fpm is running, pid 1
kimai_1    | [10-Feb-2023 17:07:58] NOTICE: ready to handle connections
kimai_1    | 192.168.240.5 -  10/Feb/2023:17:08:13 +0100 "GET /index.php" 500
kimai_1    | NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Undefined constant Symfony\Component\HttpFoundation\Request::HEADER_X_FORWARDED_ALL in /opt/kimai/public/index.php:23    
kimai_1    | Stack trace:
kimai_1    | #0 {main}
kimai_1    |   thrown in /opt/kimai/public/index.php on line 23
nginx_1    | 2023/02/10 16:08:13 [error] 8#8: *2 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Undefined constant Symfony\Component\HttpFoundation\Request::HEADER_X_FORWARDED_ALL in /opt/kimai/public/index.php:23
nginx_1    | Stack trace:
nginx_1    | #0 {main}
nginx_1    |   thrown in /opt/kimai/public/index.php on line 23" while reading response header from upstream, client: 192.168.240.1, server: nginx, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.240.4:9000", host: "docker3.bl-its.at:8001"
nginx_1    | 192.168.240.1 - - [10/Feb/2023:16:08:13 +0000] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" "-"
nginx_1    | 192.168.240.1 - - [10/Feb/2023:16:08:13 +0000] "GET /favicon.ico HTTP/1.1" 200 1150 "http://docker3.bl-its.at:8001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0" "-"
kimai_1    | 127.0.0.1 -  10/Feb/2023:17:08:17 +0100 "GET /ping" 404
nginx_1    | 192.168.240.5 - - [10/Feb/2023:16:08:18 +0000] "GET /health HTTP/1.1" 200 5 "-" "Wget" "-"
kimai_1    | 127.0.0.1 -  10/Feb/2023:17:08:37 +0100 "GET /ping" 404
```
Container stoped
