### ISSUE TITLE
LDAP example in Documentation is not correct (not user, but username)

### ISSUE THREAD

**Issue by DunklerPhoenix** [kimai/kimai#3987]
### Describe the issue

Heho
The LDAP configuration example shows:
```
kimai:
    ldap:
        activate: true
        connection:
            host: 127.0.0.1
            useSsl: true
            port: 543
            user: kimai
            password: serverToken
```

but this will throw this error:

```
 [ERROR] Unrecognized option "user" under "kimai.ldap.connection". Available    
         options are "accountCanonicalForm", "accountDomainName",               
         "accountDomainNameShort", "accountFilterFormat", "allowEmptyPassword", 
         "baseDn", "bindRequiresDn", "host", "networkTimeout", "optReferrals",  
         "password", "port", "tryUsernameSplit", "useSsl", "useStartTls",       
         "username".       
```  

It should not be "user: kimai" instead it should be "username: kimai"

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.14

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1
