### ISSUE TITLE
LDAP - Documentation - user_method: setUsername depricated

### ISSUE THREAD

**Issue by DunklerPhoenix** [kimai/kimai#3996]
### Describe the issue

Heho
In the documentation is "user_method: setUsername" given as example, but this throws a deprication warning and need to be replaced by "user_method: setUserIdentifier".

https://www.kimai.org/documentation/ldap.html

```
       user:
            baseDn: ou=users, dc=kimai, dc=org
            filter: (&(objectClass=posixAccount))
            usernameAttribute: uid
            attributes:
                - { ldap_attr: uid, user_method: setUsername }  <---
                - { ldap_attr: cn, user_method: setAlias }
                - { ldap_attr: mail, user_method: setEmail }
```

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.14

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1
