### ISSUE TITLE
LDAP setAlias does not work

### ISSUE THREAD

**Issue by DunklerPhoenix** [kimai/kimai#3999]
### Describe the issue

Heho
This line from the documentation does not work. The name in the profile does not get filled with informations (i think this line is for that.
    `     - { ldap_attr: cn, user_method: setAlias }`

from 

 ```
       user:
            baseDn: ou=users, dc=kimai, dc=org
            filter: (&(objectClass=posixAccount))
            usernameAttribute: uid
            attributes:
                - { ldap_attr: uid, user_method: setUsername }
                - { ldap_attr: cn, user_method: setAlias }
                - { ldap_attr: mail, user_method: setEmail }
```

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.14

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1
