### ISSUE TITLE
SAML login button does not appear on login page after it is configured

### ISSUE THREAD

**Issue by brickhousewindow** [kimai/kimai#4104]
### Describe the issue

Hello,

we have installed a new kimai2 instance on our Plesk server. Afterwards the configuration was added to use SAML together with keycloak (https://www.kimai.org/documentation/saml-keycloak.html). The issue is that no button appears on the login page to use the SAML login. There is no error inside the production log. There is also no error message inside the PHP log. During a cache clear it is displayed that the local.yml is being included. No errors are reported during the cache creation.
This is the current configuration:

```yaml
kimai:
    saml:
        provider: keycloak
        activate: true
        title: Keycloak
        mapping:
            - { saml: $Email, kimai: email }
            - { saml: $FirstName $LastName, kimai: alias }
        roles:
            resetOnLogin: true
            attribute: Roles
            mapping:
                - { saml: Admins, kimai: ROLE_ADMIN }
                - { saml: Management, kimai: ROLE_TEAMLEAD }
        connection:
            # You SAML provider, here an example for Keycloak
            idp:
                entityId: 'https://<REDACTED>/auth/realms/<REDACTED>'
                singleSignOnService:
                    url: 'https://<REDACTED>/auth/realms/<REDACTED>/protocol/saml'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                #    url: 'https://127.0.0.1:8010/logout' binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                x509cert: '<REDACTED>'
           # Your Kimai instance, replace https://127.0.0.1:8010 with your base URL
            sp:
                entityId: 'Kimai2'
                assertionConsumerService:
                    url: 'https://<REDACTED>/auth/saml/acs'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
                singleLogoutService:
                    url: 'https://<REDACTED>/auth/saml/logout'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                #privateKey: ''
            # only set baseurl, if auto-detection doesn't work
            baseurl: 'https://<REDACTED>/'
            strict: true
            debug: true
            security:
                nameIdEncrypted: false
                authnRequestsSigned: false
                logoutRequestSigned: false
                logoutResponseSigned: false
                wantMessagesSigned: false
                wantAssertionsSigned: false
                wantNameIdEncrypted: false
                requestedAuthnContext: true
                signMetadata: false
                wantXMLValidation: true
                signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
                digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
            contactPerson:
                technical:
                    givenName: 'Kimai Admin'
                    emailAddress: 'kimai-tech@example.com'
                support:
                    givenName: 'Kimai Support'
                    emailAddress: 'kimai-support@example.com'
            organization:
                en:
                    name: 'Kimai'
                    displayname: 'Kimai'
                    url: 'https://www.kimai.org'
```

What was tried:

- the PHP versions 7.4, 8.1 and 8.2 were tried
- we read somewhere that it does not work when no user exists. A user was created inside the application, without success.
- the doctor tool does not report any errors
- checked the saml-php configuration options inside
- enabled baseurl parameter
- running the composer update displays no errors

A screenshot and the log output for the login page were attached. The log output was created by modifying the monolog.yml file.

One thing we would like to ask is how to debug such issue or analyze it further.

Best regards.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.24

### How do you run Kimai?

Plesk

### Which PHP version are you using?

8.1

### Logfile

[2023-06-12T14:05:56.569951+00:00] security.DEBUG: Authenticator does not sup
\LdapAuthenticator"} []
[2023-06-12T14:05:56.513404+00:00] security.DEBUG: Checking support on authen
ticator. {"firewall_name":"secured_area","authenticator":"Symfony\\Component\
\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2023-06-12T14:05:56.513434+00:00] security.DEBUG: Authenticator does not sup
port the request. {"firewall_name":"secured_area","authenticator":"Symfony\\C
omponent\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2023-06-12T14:05:56.513491+00:00] security.DEBUG: Checking support on authen
ticator. {"firewall_name":"secured_area","authenticator":"Symfony\\Component\
\Security\\Http\\Authenticator\\RememberMeAuthenticator"} []
[2023-06-12T14:05:56.513540+00:00] security.DEBUG: Authenticator does not sup
port the request. {"firewall_name":"secured_area","authenticator":"Symfony\\C
omponent\\Security\\Http\\Authenticator\\RememberMeAuthenticator"} []
[2023-06-12T14:05:56.563103+00:00] request.INFO: Matched route "{route}". {"r
oute":"homepage","route_parameters":{"_route":"homepage","_controller":"App\\
Controller\\HomepageController::indexAction","_locale":"en_US"},"request_uri"
:"https://<REDACTED>/en_US/homepage","method":"GET"} []
[2023-06-12T14:05:56.563103+00:00] request.INFO: Matched route "homepage". {"
route":"homepage","route_parameters":{"_route":"homepage","_controller":"App\
\Controller\\HomepageController::indexAction","_locale":"en_US"},"request_uri
":"https://<REDACTED>/en_US/homepage","method":"GET"} []
[2023-06-12T14:05:56.569383+00:00] security.DEBUG: Checking for authenticator
 support. {"firewall_name":"secured_area","authenticators":6} []
[2023-06-12T14:05:56.569486+00:00] security.DEBUG: Checking support on authen
ticator. {"firewall_name":"secured_area","authenticator":"App\\API\\Authentic
ation\\SessionAuthenticator"} []
[2023-06-12T14:05:56.569542+00:00] security.DEBUG: Authenticator does not sup
port the request. {"firewall_name":"secured_area","authenticator":"App\\API\\
Authentication\\SessionAuthenticator"} []
[2023-06-12T14:05:56.569591+00:00] security.DEBUG: Checking support on authen
ticator. {"firewall_name":"secured_area","authenticator":"App\\Saml\\SamlAuth
enticator"} []
[2023-06-12T14:05:56.569847+00:00] security.DEBUG: Authenticator does not sup
port the request. {"firewall_name":"secured_area","authenticator":"App\\Saml\
\SamlAuthenticator"} []
[2023-06-12T14:05:56.569899+00:00] security.DEBUG: Checking support on authen
ticator. {"firewall_name":"secured_area","authenticator":"Scheb\\TwoFactorBun
dle\\Security\\Http\\Authenticator\\TwoFactorAuthenticator"} []
[2023-06-12T14:05:56.569951+00:00] security.DEBUG: Authenticator does not sup
port the request. {"firewall_name":"secured_area","authenticator":"Scheb\\Two
FactorBundle\\Security\\Http\\Authenticator\\TwoFactorAuthenticator"} []
[2023-06-12T14:05:56.570040+00:00] security.DEBUG: Checking support on authen
ticator. {"firewall_name":"secured_area","authenticator":"App\\Ldap\\LdapAuth
enticator"} []
[2023-06-12T14:05:56.570105+00:00] security.DEBUG: Authenticator does not sup
port the request. {"firewall_name":"secured_area","authenticator":"App\\Ldap\
\LdapAuthenticator"} []
[2023-06-12T14:05:56.570148+00:00] security.DEBUG: Checking support on authen
ticator. {"firewall_name":"secured_area","authenticator":"Symfony\\Component\
\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2023-06-12T14:05:56.570189+00:00] security.DEBUG: Authenticator does not sup
port the request. {"firewall_name":"secured_area","authenticator":"Symfony\\C
omponent\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2023-06-12T14:05:56.570228+00:00] security.DEBUG: Checking support on authen
ticator. {"firewall_name":"secured_area","authenticator":"Symfony\\Component\
\Security\\Http\\Authenticator\\RememberMeAuthenticator"} []
[2023-06-12T14:05:56.570293+00:00] security.DEBUG: Authenticator does not sup
port the request. {"firewall_name":"secured_area","authenticator":"Symfony\\C
omponent\\Security\\Http\\Authenticator\\RememberMeAuthenticator"} []
[2023-06-12T14:05:56.571858+00:00] security.DEBUG: Access denied, the user is
 not fully authenticated; redirecting to authentication entry point. {"except
ion":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedEx
ception(code: 403): Access Denied. at /var/www/vhosts/<REDACTED>/<REDACTED>/kimai/vendor/symfony/security-http/Firewall/AccessListener.ph
p:87)"} []
[2023-06-12T14:05:56.572060+00:00] security.DEBUG: Calling Authentication ent
ry point. {"entry_point":{"Symfony\\Component\\Security\\Http\\Authenticator\
\FormLoginAuthenticator":[]}} []
[2023-06-12T14:05:57.367718+00:00] request.INFO: Matched route "{route}". {"r
oute":"login","route_parameters":{"_route":"login","_controller":"App\\Contro
ller\\Security\\SecurityController::loginAction","_locale":"en_US"},"request_
uri":"https://<REDACTED>/en_US/login","method":"GET"} []
[2023-06-12T14:05:57.367718+00:00] request.INFO: Matched route "login". {"rou
te":"login","route_parameters":{"_route":"login","_controller":"App\\Controll
er\\Security\\SecurityController::loginAction","_locale":"en_US"},"request_ur
i":"https://<REDACTED>/en_US/login","method":"GET"} []
[2023-06-12T14:05:57.373288+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"secured_area","authenticators":6} []
[2023-06-12T14:05:57.373348+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"secured_area","authenticator":"App\\API\\Authentication\\SessionAuthenticator"} []
[2023-06-12T14:05:57.373383+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"secured_area","authenticator":"App\\API\\Authentication\\SessionAuthenticator"} []
[2023-06-12T14:05:57.373413+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"secured_area","authenticator":"App\\Saml\\SamlAuthenticator"} []
[2023-06-12T14:05:57.373571+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"secured_area","authenticator":"App\\Saml\\SamlAuthenticator"} []
[2023-06-12T14:05:57.373607+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"secured_area","authenticator":"Scheb\\TwoFactorBundle\\Security\\Http\\Authenticator\\TwoFactorAuthenticator"} []
[2023-06-12T14:05:57.373642+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"secured_area","authenticator":"Scheb\\TwoFactorBundle\\Security\\Http\\Authenticator\\TwoFactorAuthenticator"} []
[2023-06-12T14:05:57.373670+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"secured_area","authenticator":"App\\Ldap\\LdapAuthenticator"} []
[2023-06-12T14:05:57.373708+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"secured_area","authenticator":"App\\Ldap\\LdapAuthenticator"} []
[2023-06-12T14:05:57.373753+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"secured_area","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2023-06-12T14:05:57.373784+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"secured_area","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2023-06-12T14:05:57.373811+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"secured_area","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\RememberMeAuthenticator"} []
[2023-06-12T14:05:57.373852+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"secured_area","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\RememberMeAuthenticator"} []

### Screenshots

![image](https://github.com/kimai/kimai/assets/126773458/f9be2da7-9b9c-499b-9c0f-28b40ed9e3c3)
