### ISSUE TITLE
LDAP Login error 500 -  Duplicate entry 'name' for key 'UNIQ_B9AC5BCEF85E0677'

### ISSUE THREAD

**Issue by chises** [kimai/kimai#4272]
### Describe the issue

If a LDAP User (Active Directory) logs in, every time a error 500 is shown.

It seems to me that the system does not recognize that this user already exists.
To test I deleted the user, logged in: everything is fine. 
After a logout and login again the same error shows up. In the Databae every seems to be fine. The new user does not differ to the "old" one. The ldap.dn is correct set in user_preferences table.

LDAP Config in local.yaml:
```
   ldap:
        activate: true
        connection:
            host: 10.10.x.x
            username: CN=kimai,OU=service-accounts,OU=usr,OU=x,DC=x,DC=local
            password: x
            accountDomainName: x.local
            accountDomainNameShort: x
            accountFilterFormat: (&(objectClass=organizationalPerson)(sAMAccountName=%s))
            bindRequiresDn: true
            accountCanonicalForm: 3
        user:
            baseDn: OU=usr,OU=x,DC=x,DC=local
            usernameAttribute: sAMAccountName
            filter: (&(objectClass=organizationalPerson))
            attributes:
                - { ldap_attr: displayname, user_method: setAlias }
                - { ldap_attr: mail, user_method: setEmail }
                - { ldap_attr: samaccountname,  user_method: setUsername }

```

The issue were reported today, but after some discussion it seems to exist since the upgrade tofrom 1.x to 2.x

I am sorry, but I lack of time for more troubleshooting. Perhaps I can provide more information in a few days.

Someone got a idea what is wrong here?

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.26 and 2.0.32 tested

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

### Logfile

[2023-09-04T08:08:50.559059+00:00] security.INFO: Authenticator successful! {"token":{"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken":"UsernamePasswordToken(user=\"michael.weber\", roles=\"ROLE_USER\")"},"authenticator":"App\\Ldap\\LdapAuthenticator"} []
[2023-09-04T08:08:50.575987+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'michael.weber' for key 'UNIQ_B9AC5BCEF85E0677'" at /var/www/kimai2/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 62 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 1062): An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'michael.weber' for key 'UNIQ_B9AC5BCEF85E0677' at /var/www/kimai2/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:62)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1062): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'michael.weber' for key 'UNIQ_B9AC5BCEF85E0677' at /var/www/kimai2/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'michael.weber' for key 'UNIQ_B9AC5BCEF85E0677' at /var/www/kimai2/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:121)"}

### Screenshots

![image](https://github.com/kimai/kimai/assets/10805806/fd7f979a-00cc-4fa4-9a10-64e65b7db319)
