### ISSUE TITLE
LDAP login not workin anymore for some users after upgradng from 1.3 to 2.33

### ISSUE THREAD

**Issue by Mikesch-mp** [kimai/kimai#4291]
### Describe the issue

After upgrrading Kimai to 2.33, some user could not login any more. The installation uses LDAP as authentication backend before and it worked for all users without a problem. My testuser worked and i did not see any error in the log, also new created users in the AD could login without problems.
After digging around, sadly i found no option to enable debug logging for LDAP, i found out the the users that cant login missing the 'ldap.dn' entry in the 'kimai2_user_preferences' table. So first test was to rename the username and email of one user that could not login, so he gets recreated. Doing that the authentication via LDAP worked, user got created and login was successfull.
Next test was to add that entry to the initial user account that could not login, after adding it, the user could login and use Kimai2 normaly.
So for some users there must be a problem to read or write the dn information into the database.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.33

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.2

### Logfile

no log entries are generated

**Comment by kevinpapst** [comment]
You can read all LDAP issues:
https://github.com/kimai/kimai/discussions?discussions_q=ldap
https://github.com/kimai/kimai/issues?q=is%3Aissue+LDAP+is%3Aclosed

AFAIR all of them come to the conclusion, that the bug is in the configuration.

**Comment by Mikesch-mp** [comment]
Configuration worked fine for 1.3 and also for some users in 2.33. Only few users get all the time password wrong message without the added ldap_dn entry. If yo have a way to enable debug logging for ldap i will try to find the cause.

The LDAP configuration
```
kimai:
    user:
        registration: false
        password_reset: false
    ldap:
        activate: true
        connection:
            host: 10.1.20.2
            port: 389
            useSsl: false
            useStartTls: false
            username: 'CN=monitoring,CN=Users,DC=company,DC=global'
            password: 'supersecret'
            accountDomainName: company.global
            accountDomainNameShort: COMPANY
            accountFilterFormat: (&(objectClass=person)(sAMAccountName=%s))
            bindRequiresDn: false
        user:
            baseDn: CN=Users,DC=company,DC=global
            filter: (&(objectClass=person))
            usernameAttribute: samaccountname
            attributesFilter: (objectClass=person)
            attributes:
                - { ldap_attr: mail, user_method: setEmail }
                - { ldap_attr: description, user_method: setAlias }
                - { ldap_attr: sammacountname, user_method: setUsername }
        role:
            baseDn: 'CN=Users,DC=company,DC=global'
            filter: (&(objectClass=group))
            nameAttribute: cn
            userDnAttribute: member
            groups:
                - { ldap_value: 'Domain Admins', role: ROLE_SUPER_ADMIN }
                - { ldap_value: KimaiAdmins, role: ROLE_ADMIN }
                - { ldap_value: Mitarbeiter, role: ROLE_USER }
                - { ldap_value: kimai_extern, role: ROLE_USER }

```
