### ISSUE TITLE
How to setup LDAP module/extension?

### ISSUE THREAD

**Issue by acseven** [kimai/kimai#4405]
### Describe the problem

What is the expect way to configure LDAP when using Docker?
I've tried mapping a local.conf file with edited settings from the examples in the documentation, but that doesn't seem to load the config file. PHP extensions also don't show LDAP. 

### Describe your setup (OS, Docker versions)

Debain 11

### Docker compose file (redact your credentials)

    volumes:
      - /docker/kimai/v/public:/opt/kimai/public
      - /docker/kimai/v/var:/opt/kimai/var
      - /docker/kimai/v/conf/ldap.conf:/etc/openldap/ldap.conf:z
      #- /docker/kimai/v/conf/local.conf:/opt/kimai/config/packages/local.conf
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z

**Comment by kevinpapst** [comment]
Why do you think the file should be called local.conf ? https://www.kimai.org/documentation/local-yaml.html

**Comment by acseven** [comment]
I was trying to replicate the documentation here: https://www.kimai.org/documentation/ldap.html

When mapping this:

`  - /docker/kimai/v/conf/local.conf:/opt/kimai/config/packages/local.conf`

With a `local.conf` file that contais the settings below,  nothing appears to happen:

```
kimai:
    user:
        registration: false
        password_reset: false
    ldap:
        activate: true
        connection:
            host: "ldap://server1.company.local ldap://server2.company.local"
            username: CN=UserA,CN=Users,DC=company,DC=local
            password: (password)
            accountFilterFormat: (&(objectClass=Person)(sAMAccountName=%s))
            accountDomainName: company.local
            accountDomainNameShort: company
        user:
            baseDn: ou=users, dc=company, dc=local
            usernameAttribute: uid
            filter: (&(objectClass=Person))
            attributes:
                - { ldap_attr: mail, user_method: setEmail }
                - { ldap_attr: displayname, user_method: setAlias }
                - { ldap_attr: samaccountname,  user_method: setUsername }
        role:
            baseDn: ou=groups, dc=company, dc=local
            filter: (&(objectClass=group))
                - { ldap_value: Leads, role: ROLE_TEAMLEAD }
                - { ldap_value: Domain Admins, role: ROLE_SUPER_ADMIN }
                - { ldap_value: Domain Users, role: ROLE_USER }
```
