### ISSUE TITLE
The characters are broken in the export preview PDF.

### ISSUE THREAD

**Issue by Hansanghyeon** [kimai/kimai#4436]
### Describe the issue

Preview in PDF, export encoding does not appear again.

All other export types except PDF are not broken characters

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.3.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

### Screenshots

<img width="760" alt="image" src="https://github.com/kimai/kimai/assets/42893446/e80a31dd-1039-4831-bbcb-52ddea4a858d">
<img width="888" alt="image" src="https://github.com/kimai/kimai/assets/42893446/8f624789-34b1-4908-afa2-a16351dec888">
<img width="1306" alt="image" src="https://github.com/kimai/kimai/assets/42893446/690a1d55-24c2-438d-8aa2-edbc943d7f5d">

**Comment by Hansanghyeon** [comment]
I think it's a font problem when exporting to PDF. Can I get most languages exported to a supported system font?

**Comment by Hansanghyeon** [comment]
I thought it was a Korean problem, but it was a font problem. I found a way to specify fonts here and I think I can solve this problem.

나는 한국어 문제인줄 알았지만 폰트문제였다. 여기서 폰트를 지정하는 방법을 찾았고 이 문제를 해결할 수 있을 것같다.

REF - https://www.kimai.org/blog/2022/kimai-release-1-24/
REF - https://www.kimai.org/documentation/export.html
REF - https://github.com/kimai/kimai/issues/1433

**Comment by kevinpapst** [comment]
Do you think it would make sense to create a dedicated documentation page that talks about the necessary changes to support (not sure if that is the right term) "non-latin based" (e.g. Korean, Chinese, Farsi, Hebrew ...) languages?

**Comment by Hansanghyeon** [comment]
I'm not sure if there should be a separate document.

What about using a font that supports both Latin and non-Latin characters?

**Comment by kevinpapst** [comment]
Is there such a font available in the default MPDF installation?
Which one are you using now?

**Comment by Hansanghyeon** [comment]
I am currently using the kimai/kimai2 Docker image, and I haven't configured MPDF yet. I have placed `{custom_font}.ttf` in `/opt/kiami/var/data/fonts/` in the `docker-compose.yaml` file. I am looking for guidance on how to apply custom fonts.

> 저는 지금 kimai/kimai2 docker 이미지를 사용하고있습니다. 그래서 MPDF를 설정하지는 못했습니다.
`docker-compose.yaml`이고 `/opt/kiami/var/data/fonts/{custom_font}.ttf`를 넣었습니다. 커스텀 폰트를 어떻게 적용해야하는지 찾고있습니다.

```yaml
version: '3.9'


services:
  sqldb:
    image: mysql
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    #ports:
    #  - 3336:3306
    volumes:
      - ./volume/db:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai: # This is the latest FPM image of kimai
    image: kimai/kimai2:apache
    environment:
      - DATABASE_URL=mysql://kimaiuser:kimaipassword@sqldb/kimai?charset=utf8&serverVersion=5.7.40
      - MAILER_URL=smtp://mailer:1025
      - MAILER_FROM=no-replay@beeclover.pro
    volumes:
      - ./volume/kimai/public:/opt/kimai/public
      - ./volume/kimai/var:/opt/kimai/var
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    restart: unless-stopped

  # swagger:
  #   image: swaggerapi/swagger-ui
  #   ports:
  #     - 8082:8080
  #   # volumes:
  #   #   - ./swagger.json:/swagger.json
  #   environment:
  #     - SWAGGER_JSON=/swagger.json

  mailer:
    image: schickling/mailcatcher
    ports:
      - "${MAILER_SMTP_PORT:-1025}:1025"
      - "${MAILER_ADMIN_PORT:-1080}:1080"

```
