### ISSUE TITLE
Add flat rate increase for weekends

### ISSUE THREAD

**Issue by bryan065** [kimai/kimai#4459]
### Describe the problem

Currently, it's possible to add rules in the config file to have a multiplicative increase to rates on specific days.

Example, will increase by 50% on weekends:
```
kimai:
    timesheet:
        rates:
            workdays:
                days: ['monday','tuesday','wednesday','thursday','friday']
                factor: 1
            weekend:
                days: ['saturday','sunday']
                factor: 1.5
```

### Describe the solution you'd like

Is it possible to add a flat rate increase as well?
Example, will increase rate by 5 (currency) on weekends:
```
kimai:
    timesheet:
        rates:
            workdays:
                days: ['monday','tuesday','wednesday','thursday','friday']
                flat_increase: 0
            weekend:
                days: ['saturday','sunday']
                flat_increase: 5
```

As a side note, would it be possible/difficult/time consuming to add filters for projects to these rules?

### Describe alternatives you've considered

Currently, our employees are using an activity with the `(Weekend)` label on it and manually changing the rate in extended settings.
