### ISSUE TITLE
Cannot autowire service "App\Command\UserLoginLinkCommand" (DefinitionErrorExceptionPass.php line 49)

### ISSUE THREAD

**Issue by PentaPaetzold** [kimai/kimai#4489]
### Describe the problem

Starting Kimai i get
```
2023-12-07T16:59:01.502568552Z  [ERROR] Failed to clear cache: Cannot autowire service                         
2023-12-07T16:59:01.502785459Z          "App\Command\UserLoginLinkCommand": argument "$loginLink" of method    
2023-12-07T16:59:01.502920523Z          "__construct()" references interface                                   
2023-12-07T16:59:01.503038474Z          "Symfony\Component\Security\Http\LoginLink\LoginLinkHandlerInterface"  
2023-12-07T16:59:01.503123123Z          but no such service exists. Did you create a class that implements this
2023-12-07T16:59:01.503219314Z          interface?

2023-12-07T17:02:47.598224091Z  [WARNING] Cache could not be rebuilt.                                          
2023-12-07T17:02:47.598291147Z                                                                                 
2023-12-07T17:02:47.598300705Z            Please run these commands to rebuild the cache manually:             
2023-12-07T17:02:47.598304542Z                                                                                 
2023-12-07T17:02:47.598308349Z            rm -r var/cache/*                                                    
2023-12-07T17:02:47.598312097Z            bin/console cache:clear --env=prod                                   
2023-12-07T17:02:47.598315753Z            bin/console cache:warmup --env=prod

```

i am doing the steps, but:
```
885bbe071f69:/var/www/html# /opt/kimai/bin/console cache:clear --env=prod

 // Clearing the cache for the prod environment with debug false                                                        


In DefinitionErrorExceptionPass.php line 49:
                                                                                                                                                                              
  Cannot autowire service "App\Command\UserLoginLinkCommand": argument "$loginLink" of method "__construct()" references interface "Symfony\Component\Security\Http\LoginLin  
  k\LoginLinkHandlerInterface" but no such service exists. Did you create a class that implements this interface?                                                             
                                                                                                                                                                              

cache:clear [--no-warmup] [--no-optional-warmers]

885bbe071f69:/var/www/html# /opt/kimai/bin/console cache:warmup --env=prod

 // Warming up the cache for the prod environment with debug false                                                      

                                                                                                                        
 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.                                           
                                                                                                                        

885bbe071f69:/var/www/html# /opt/kimai/bin/console kimai:reload --env=prod
 Validating config file syntax ...

                                                                                                                        
 [OK] All 26 YAML files contain valid syntax.                                                                           
                                                                                                                        
 [OK] All 629 XLIFF files contain valid syntax.                                                                         

 Rebuilding your cache, please be patient ...

 // Clearing the cache for the prod environment with debug false                                                        
                                                                                                                        
 [ERROR] Cannot autowire service "App\Command\UserLoginLinkCommand": argument "$loginLink" of method "__construct()"    
         references interface "Symfony\Component\Security\Http\LoginLink\LoginLinkHandlerInterface" but no such service 
         exists. Did you create a class that implements this interface?                                                 
                                                                                                                        
 [WARNING] Cache could not be rebuilt.                                                                                  
                                                                                                                        
           Please run these commands to rebuild the cache manually:                                                     
                                                                                                                        
           rm -r var/cache/*                                                                                            
           bin/console cache:clear --env=prod                                                                           
           bin/console cache:warmup --env=prod
```
i read about not mounting /var, but i already set up a new volume, so i don't know what to do. Please help.

### Describe your setup and add your Docker compose file (redact your credentials)

Docker version 24.0.2, build cb74dfc

Docker Compose-File:
```
version: '3.8'
#
services:
  kimai:
    image: kimai/kimai2:fpm-2.4.0-prod
    platform: linux/amd64
    environment:
      ADMINMAIL: *hidden*
      ADMINPASS: *hidden*
      DATABASE_URL: "mysql://kimaiuser:*hidden*/kimai?charset=utf8&serverVersion=${MARIADB_TAG}"
      TRUSTED_HOSTS: "proxy,localhost,127.0.0.1"
      memory_limit: 1024M
# User+Passwort encodiert - z.b. mit: php -r "echo urlencode('VeryVerdämmtK@mplexeßPazw@rt');"
      MAILER_URL: "smtps://*hidden*:*hidden*@mailer.de:465"
      MAILER_FROM: "*hidden*"
      APP_SECRET: "*hidden*"
    volumes:
      - kimai_public:/opt/kimai/public
      - kimai_var2:/opt/kimai/var
      - kimai_conf:/opt/kimai/config/packages:z
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    restart: always
    depends_on:
      - mariadb
    networks:
      - default

# reverse proxy
  kimai_nginx:
    image: tobybatch/nginx-fpm-reverse-proxy
    platform: linux/amd64
    environment:
# Parameter für den nginx- Proxy vhost
      - VIRTUAL_HOST=*hidden*
      - LETSENCRYPT_HOST=*hidden*
      - LETSENCRYPT_EMAIL=*hidden*
      - VIRTUAL_PORT=80
    volumes:
      - kimai_public:/opt/kimai/public:ro
      - kimai_var2:/opt/kimai/var
    restart: always
    depends_on:
      - kimai
    healthcheck:
      test:  wget --spider http://kimai_nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    networks:
      - default
      - proxy-tier

volumes:
    kimai_var2:
    kimai_public:
    kimai_mysql:
    kimai_conf:

networks:
    proxy-tier:
```

### Command used to run the container

_No response_
