### ISSUE TITLE
Clockify to Kimai data migration issue with two chars usernames

### ISSUE THREAD

**Issue by acseven** [kimai/kimai#4502]
### Describe the issue

I've setup a Kimai installation running on docker while also authenticating users to a local Active Directory server. It mostly works, with a couple of issues. 

Given I found no working way to simply login and have kimai appoint the old user (same email) to the migrated data, I decided on modifying the imported email addresses and after the user logs into to kimai, I would delete the old user and selecting the new one as recipient of migrated time entries. 

The issue I found is that, given I'm using `sAMAccountName` for kimai, I have a couple of high level users that have usernames with two characters only. When deleting their imported accounts the search selector never searches for these users (search dropdown is probably limited to 3 or more characters, check screenshot below).

On the other hand, I tried to modify the LDAP settings in order to have `userPrincipalName` instead of `sAMAccountName` as the username (i.e. the email), but I couldn't figure out how to make that work .

So I'm stuck with how to migrate these users' old data, is there anything else to try or any additional help with what I've done so far?

Working configuration with `sAMAccountName`:

```
kimai:
    ldap:
        activate: true
        connection:
            host: "ldap://server1.mycompany.local ldap://server1.mycompany.local"
            username: "CN=The LDAP List User,CN=Users,DC=MYCOMPANY,DC=local"
            password: ++++++++++++
            accountFilterFormat: (&(objectClass=person)(sAMAccountName=%s))
            #accountFilterFormat: (&(userPrincipalName=%s))
            bindRequiresDn: true 
            allowEmptyPassword: false
            tryUsernameSplit: true
            #accountCanonicalForm: 4 # 3 for backslash-style names (e.g., FOO\alice) or 4 for principal style usernames (e.g., alice@foo.net)
            accountDomainName: mycompany.local
            accountDomainNameShort: MYCOMPANY
        user:
            baseDn: cn=Users, dc=mycompany, dc=local
            #usernameAttribute: userPrincipalName
            usernameAttribute: samaccountname
            filter: (&(objectClass=Person))
            attributesFilter: (objectClass=Person)
            attributes:
                - { ldap_attr: mail, user_method: setEmail } 
                - { ldap_attr: displayname, user_method: setAlias }
                - { ldap_attr: samaccountname,  user_method: setUserIdentifier }
        role:
            baseDn: cn=Users, dc=mycompany, dc=local
            filter: (&(objectClass=group))
            groups:
                - { ldap_value: "Group_APPS_TIMETRACK_TEAMLEAD", role: ROLE_TEAMLEAD }
                - { ldap_value: "Group_IT_Admin", role: ROLE_SUPER_ADMIN }
                - { ldap_value: "Group_APPS_TIMETRACK_USER", role: ROLE_USER }
```

_PS: I was using docker with kimai2:apache but that image in particular hasn't been updated to the latest version (2.6.0), I can't say if it's expected or not. Moved to kimai2:apache-prod which did update._ 

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.6.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

### Screenshots

There is a username `tw`:

![image](https://github.com/kimai/kimai/assets/1176371/f0495ae7-faae-41d2-a8f9-31e184694611)
