### ISSUE TITLE
Unable to enable LDAP with Docker Apache prod image fresh install

### ISSUE THREAD

**Issue by luketanti** [kimai/kimai#4543]
### Describe the problem

I can not get Docker image kimai/kimai2:apache to enable LDAP.
Local login with admin works but LDAP does not.
It is never mentioned in the logs anywhere.
I get no errors.

![image](https://github.com/kimai/kimai/assets/23320513/eeec85db-34e2-4dfc-879a-ddca9e448fe4)

![image](https://github.com/kimai/kimai/assets/23320513/3f1950a2-3987-4b06-9ff1-62fccbcdc92b)

![image](https://github.com/kimai/kimai/assets/23320513/741256af-cacb-4c8c-96a5-43ef0457c631)

I have followed the docs to add the local.yaml file to /opt/kimai/config/packages/ using bind mount

Below is my Docker compose file

I am using podman version 4.6.1 on RHEL

This is my local.yaml file: (removed actual domain data)

```
security:
    providers:
        chain_provider:
            chain:
                providers: [kimai_ldap]           

framework:
    session:
        gc_maxlifetime: 36000
        cookie_lifetime: 36000
        
kimai:
    user:
        registration: false
        password_reset: false
        
    ldap:
        activate: true
        connection:
            host: ad.domain.com
            username: Kimai_ldap@ad.domain.com
            password: pass
            accountDomainName: ad.domain.com
            accountDomainNameShort: ad
            accountFilterFormat: (&(objectClass=Person)(sAMAccountName=%s))
            bindRequiresDn: false
        user:
            baseDn: cn=ou=Manufacturing,dc=AD,dc=DOMAIN,dc=COM
            filter: (&(objectClass=Person))
            usernameAttribute: samaccountname
            attributesFilter: (objectClass=Person)
            attributes:
                - { ldap_attr: mail, user_method: setEmail }
                - { ldap_attr: displayname, user_method: setAlias }
                - { ldap_attr: samaccountname,  user_method: setUsername }
```

### Describe your setup and add your Docker compose file (redact your credentials)

```
version: '3.5'
services:

  # MySQL Database
  sqldb:

    image: mariadb:11.2.2
    volumes:
      - /data/app/mysql:/var/lib/mysql:Z
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=kimai2
      - MYSQL_USER=KimaiDbUser
      - MYSQL_PASSWORD=[redacted]
      - MYSQL_ROOT_PASSWORD=[redacted]
    command: --default-storage-engine innodb
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - sqldb
    image: phpmyadmin
    ports:
      - "8090:80"
    environment:
      PMA_HOST: sqldb
      MYSQL_ROOT_PASSWORD: [redacted]
      
  # Kimai
  kimai:
    image: kimai/kimai2:apache
    volumes:
      - /data/app/kimai/data:/opt/kimai/var:Z
      - /data/app/kimai/local.yaml:/opt/kimai/config/packages/local.yaml:z
    ports:
      - 80:8001
    environment:
      - ADMINMAIL=superadmin@kimai.local
      - ADMINPASS=[redacted]
      - "DATABASE_URL=mysql://KimaiDbUser:[redacted]@sqldb/kimai2?charset=utf8&serverVersion=11.2.2-mariadb"
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1
```
