### ISSUE TITLE
LDAP authentication saves password hash to database

### ISSUE THREAD

**Issue by paul1278** [kimai/kimai#4755]
### Describe the issue

The [documentation](https://www.kimai.org/documentation/ldap.html#user-synchronization) states, that kimai does not save the password when using LDAP authentication. After a look into the database I noticed, that it does save the password hash to the database when logging in using LDAP.

When I clear the hashes and simply login using my LDAP-account, it saves the hash again. I also checked the hash with my password, it is indeed derived from my password. Also if I delete my LDAP-settings, login with the password hash is possible.

I don't know if there is something wrong with my setup or a database migration not working, the ldap user has the following attributes on `kimai2_users`-table:

```
[kimai]> select * from kimai2_users;
+----+----------+------------------------+--------------------------------------------------------------+-------+---------+---------------------+-------+--------+------------------------------------+---------------------+--------------------+-----------------------+-----------+------+-------+---------+------------------------------------------------------+--------------+----------------+---------------+
| id | username | email                  | password                                                     | alias | enabled | registration_date   | title | avatar | roles                              | last_login          | confirmation_token | password_requested_at | api_token | auth | color | account | totp_secret                                          | totp_enabled | system_account | supervisor_id |
+----+----------+------------------------+--------------------------------------------------------------+-------+---------+---------------------+-------+--------+------------------------------------+---------------------+--------------------+-----------------------+-----------+------+-------+---------+------------------------------------------------------+--------------+----------------+---------------+
|  5 | REDACTED | REDACTED               | REDACTED                                                     | -     |       1 | 2023-04-REDACTED    | NULL  | NULL   | a:1:{i:0;s:16:"ROLE_SUPER_ADMIN";} | 2024-04-REDACTED    | NULL               | NULL                  | NULL      | ldap | NULL  | NULL    | REDACTED                                             |            0 |              0 |          NULL |

```

LDAP config `local.yaml`:
```yaml
kimai:
    ldap:
        activate: true
        connection:
            ....
        user:
            baseDn: ou=...
            attributes:
                - { ldap_attr: "usernameAttribute", user_method: setUsername }
                - { ldap_attr: "mail", user_method: setEmail }
                - { ldap_attr: "cn", user_method: setAlias }
```

https://github.com/kimai/kimai/discussions/4182 someone mentions, that there are no hashes on the database. So it must be a quite new bug.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.14.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.2
