### ISSUE TITLE
LDAP login not working since 2.15

### ISSUE THREAD

**Issue by Plyrolith** [kimai/kimai#4817]
### Describe the issue

The exact same (Active Directory) LDAP config which works with 2.14 does not work in 2.15 for us.
`local.yaml`:
```yaml
kimai:
  ldap:
    activate: true
    connection:
      host: ad.domain.local
      port: 389
      useStartTls: true
      username: cn=read,ou=Services,dc=domain,dc=local
      password: REDACTED
      accountFilterFormat: (&(objectClass=Person)(sAMAccountName=%s))
      accountDomainName: domain.local
      accountDomainNameShort: DOMAIN
    user:
        baseDn: cn=Users,dc=domain,dc=local
        filter: (&(objectClass=Person))
        usernameAttribute: samaccountname
        attributesFilter: (objectClass=Person)
        attributes:
          - { ldap_attr: samaccountname, user_method: setUserIdentifier }
          - { ldap_attr: mail, user_method: setEmail }
          - { ldap_attr: displayname, user_method: setAlias }
    role:
      baseDn: ou=Groups,dc=domain,dc=local
      filter: (&(objectClass=Group))
      groups:
        - { ldap_value: internal.admins, role: ROLE_SUPER_ADMIN }
        - { ldap_value: internal.managers, role: ROLE_ADMIN }
        - { ldap_value: internal.producers, role: ROLE_TEAMLEAD }
```

Running Kimai on Docker, image from Dockerhub. Tag: `apache-latest`.
LDAP server is Synology Directory Server. Results are the same using SSL (636) and STARTTLS (389).
We authenticate many other applications against the server without any issues.

- `apache-2.14.0-prod`: Login works flawlessly
- `apache-2.15.0-prod`: Wrong credentials
 ```
2024-04-26T07:49:09.224385+00:00] security.INFO: Authenticator failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): The presented password is invalid. at /opt/kimai/src/Ldap/LdapCredentialsSubscriber.php:71)","authenticator":"App\\Ldap\\LdapAuthenticator"} {"channel":"security"}
```

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.15.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

### Logfile

[2024-04-26T07:48:34.293641+00:00] deprecation.INFO: User Deprecated: Method "ArrayAccess::offsetUnset()" might add "void" as a native return type declaration in the future. Do the same in implementation "Laminas\Ldap\Dn" now to avoid errors or add an explicit @return annotation to suppress this message. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Method \"ArrayAccess::offsetUnset()\" might add \"void\" as a native return type declaration in the future. Do the same in implementation \"Laminas\\Ldap\\Dn\" now to avoid errors or add an explicit @return annotation to suppress this message. at /opt/kimai/vendor/symfony/error-handler/DebugClassLoader.php:337)"} {"channel":"deprecation"}
[2024-04-26T07:48:34.402980+00:00] security.INFO: Authenticator failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException(code: 0): The presented password is invalid. at /opt/kimai/src/Ldap/LdapCredentialsSubscriber.php:71)","authenticator":"App\\Ldap\\LdapAuthenticator"} {"channel":"security"}
[2024-04-26T07:48:34.529001+00:00] doctrine.INFO: Disconnecting [] {"channel":"doctrine"}
localhost:8001 10.11.13.1 - - [26/Apr/2024:08:48:33 +0100] "POST /en/login_check HTTP/1.1" 302 1421 "https://kimai.domain.local.de/en/login" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
[2024-04-26T07:48:34.644205+00:00] request.INFO: Matched route "login". {"route":"login","route_parameters":{"_route":"login","_controller":"App\\Controller\\Security\\SecurityController::loginAction","_locale":"en"},"request_uri":"http://kimai.domain.local/en/login","method":"GET"} {"channel":"request"}
[2024-04-26T07:48:34.648146+00:00] doctrine.INFO: Connecting with parameters array{"driver":"pdo_mysql","charset":"utf8","host":"mysql","port":3306,"user":"kimaiuser","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"charset":"utf8mb4","collation":"utf8mb4_unicode_ci"},"dbname":"kimaidb","serverVersion":"8.1"} {"params":{"driver":"pdo_mysql","charset":"utf8","host":"mysql","port":3306,"user":"kimaiuser","password":"<redacted>","driverOptions":[],"defaultTableOptions":{"charset":"utf8mb4","collation":"utf8mb4_unicode_ci"},"dbname":"kimaidb","serverVersion":"8.1"}} {"channel":"doctrine"}
[2024-04-26T07:48:34.689722+00:00] doctrine.INFO: Disconnecting [] {"channel":"doctrine"}

### Screenshots

![image](https://github.com/kimai/kimai/assets/49444317/6c9c5645-235f-4763-82ba-21884edef42a)
