### ISSUE TITLE
Tiny change in admin panel

### ISSUE THREAD

**Issue by cloudeasy** [kimai/kimai#495]
Hello,
admin panel: cursor: hover over headers: change to finger to open section.

here's the modification
file extensions/ki_adminpanel/css/subtabs.css.php
code:
```css
.adminPanel_extension_panel_header a {
  background-image: url('<?php echo $table_header_lighter; ?>');
  height: 19px;
  text-align: left;
  color: #333333;
  font-size: 11px;
  display: block;
  padding: 3px;
  height: 19px;
  cursor: pointer;
}
div.active .adminPanel_extension_panel_header a {
  background-image: url('<?php echo $table_header; ?>');
  color: #ffffff !important;
  font-weight: bold;
  cursor: default;
}
```

Thank you for this very well done software.

regards

Claude.
