### ISSUE TITLE
An exception has been thrown during the rendering of a template

### ISSUE THREAD

**Issue by gerroon** [kimai/kimai#5050]
### Describe the problem

Hi

I just did a docker pull, the container starts but I cant access the page. Unfortunately I don't remember the previous version number

![image](https://github.com/user-attachments/assets/a5947c80-ec74-4346-a11e-aee551beca42)

```
kimai_1  | [2024-09-05T19:05:11.086045+00:00] request.INFO: Matched route "timesheet". {"route":"timesheet","route_parameters":{"_route":"timesheet","page":1,"_controller":"App\\Controller\
\TimesheetController::indexAction","_locale":"en"},"request_uri":"http://192.168.2.2:18000/en/timesheet/","method":"GET"} {"channel":"request"}
kimai_1  | [2024-09-05T19:05:17.787083+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("An excepti
on occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'k0_.number' in 'field list'")." at datatable.html.twig line 14 {"exception":"[object] (Twig\\Err
or\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown
column 'k0_.number' in 'field list'\"). at /opt/kimai/templates/datatable.html.twig:14)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 1054): An
exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'k0_.number' in 'field list' at /opt/kimai/vendor/doctrine/dbal/src/Driver/API/MySQL/Excep
tionConverter.php:67)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1054): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'k0_.number' in 'field list'
 at /opt/kimai/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'k0_.n
umber' in 'field list' at /opt/kimai/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:130)"} {"channel":"request"}
kimai_1  | localhost:8001 192.168.2.113 - - [05/Sep/2024:20:05:11 +0100] "GET /en/timesheet/ HTTP/1.1" 500 1920 "http://192.168.2.2:18000/en/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x
64; rv:129.0) Gecko/20100101 Firefox/129.0"

```

### Describe your setup and add your Docker compose file (redact your credentials)

Docker compose 3.5, Debian  bookworm/sid

```
services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=upward-subpanel-splashy
      - MYSQL_ROOT_PASSWORD=xxxxxxxxxxxxxxx
    volumes:
      - /media/kimai2/mysql:/var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped


  kimai: # This is the latest FPM image of kimai
    image: kimai/kimai2:apache
    environment:
      - ADMINMAIL=admin@kimai.local
      - ADMINPASS=xxxxxxxx
      - DATABASE_URL=mysql://kimaiuser:xxxxxxx@sqldb/kimai
    volumes:
      - /media/kimai2/public:/opt/kimai/public
      - /media/kimai2/var:/opt/kimai/var
  
    ports:
      - 18000:8001
    restart: unless-stopped

volumes:
    var:
    public:
    mysql:
```
