### ISSUE TITLE
Reload LDAP password setting failed

### ISSUE THREAD

**Issue by argonmist** [kimai/kimai#5081]
### Describe the issue

Here is my docker compose file
```
services:

  sqldb:
    image: mysql:8.3
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2:apache
    volumes:
      - data:/opt/kimai/var/data
      - plugins:/opt/kimai/var/plugins
    ports:
      - 8080:8001
    environment:
      - ADMINMAIL=admin@example.com
      - ADMINPASS=11111111
      - "DATABASE_URL=mysql://kimaiuser:kimaipassword@sqldb/kimai?charset=utf8mb4&serverVersion=8.3.0"
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1
    restart: unless-stopped

volumes:
  data:
  mysql:
  plugins:
```
Here is my local.yaml
```
kimai:
  ldap:
    activate: true
    connection:
 ...
      username: myusername
      password: "i#1234%5678%"
...
```
And after I executed the command  
```
bin/console kimai:reload --env=prod
```
It shows
```
In ParameterBag.php line 93:

  You have requested a non-existent parameter "5678".
```

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.22.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

Unknown
