### ISSUE TITLE
Lots of log entries in Docker due to healthcheck 404

### ISSUE THREAD

**Issue by liayn** [kimai/kimai#5085]
### Describe the problem

Using the FPM image, the docker logs show load of errors like

> 127.0.0.1 -  26/Sep/2024:15:24:34 +0100 "GET /ping" 404

This is due to the health check in 
https://github.com/kimai/kimai/blob/40154be8f9354b185d6595249c421051d545f64d/.docker/Dockerfile.kimai-base#L127

Obviously this does not work as intended.

### Describe your setup and add your Docker compose file (redact your credentials)

- OS: Ubuntu 22.04 LTS
- Docker version 24.0.7, build 24.0.7-0ubuntu2~22.04.1

Kimai Version 2.22.0

```yaml
  time:
    image: kimai/kimai2:latest
    depends_on:
      - mysql81
    ports:
      - "127.0.0.1:9016:9000"
    environment:
      - DATABASE_URL=mysql://kimai:redacted@mysql81/kimai?charset=utf8mb4&serverVersion=8.1
      - TRUSTED_PROXIES=172.18.0.0/24
      - TRUSTED_HOSTS=*
      - MAILER_URL=smtp://mail.example.com
      - MAILER_FROM=webmaster@example.com
      - APP_SECRET=redacted
      - memory_limit=512M
    volumes:
      - /var/www/redacted/public:/opt/kimai/public
      - /opt/kimai/data:/opt/kimai/var/data
      - /opt/kimai/plugins:/opt/kimai/var/plugins
    restart: always
```

**Comment by kevinpapst** [comment]
Thanks for your report!

Would you mind sharing your entire docker-compose.yaml ? I am currently updating the Docker docs and I have no example of a running FPM installation. The original maintainer left and now I a stuck with something I never used myself...

If you have any idea of how to improve the reported issue, I would be happy to discuss it.

**Comment by liayn** [comment]
Sure, but I can only add our mysql-service. We are running apache as reverse proxy natively, so this is not a pure docker-only setup.

If I had a solution ready, I would have pushed a PR; but I need to figure out how the healthcheck here is supposed to work.

```yaml
services:
  mysql84:
    image: mysql:8.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somepassword
    volumes:
      - /opt/mysql/mysqlcustom.cnf:/etc/mysql/conf.d/mysqlcustom.cnf
      - /opt/mysql/data:/var/lib/mysql
  time:
    image: kimai/kimai2:latest
    restart: always
    depends_on:
      - mysql84
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      - DATABASE_URL=mysql://kimai:redacted@mysql84/kimai?charset=utf8mb4&serverVersion=8.4
      - TRUSTED_PROXIES=172.18.0.0/24
      - TRUSTED_HOSTS=*
      - MAILER_URL=smtp://mail.example.com
      - MAILER_FROM=webmaster@example.com
      - APP_SECRET=secret
    volumes:
      - /var/www/kimai/public:/opt/kimai/public
      - /opt/kimai/data:/opt/kimai/var/data
      - /opt/kimai/plugins:/opt/kimai/var/plugins
```

(If we would run the proxy in docker too, we would most likely either use "trafik" or "nginx" as proxy-service.)
