### ISSUE TITLE
Error after installing plugin: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted 

### ISSUE THREAD

**Issue by marktolson** [kimai/kimai#5107]
After installing the CSV and JSON importer plugin I'm receiving the following issue when trying to restart the cache. I used the docker compose method to install on Ubuntu. I can see the plugin files in the plugin directory as per the installation instructions but the plugin is not available from the UI. I also ran the following commands to no avail.

```
chown -R :www-data .
chmod -R g+r .
chmod -R g+rw var/
```

**Error:**

PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 192512 bytes) in /opt/kimai/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherDumper.php on line 407
[2024-10-10T23:54:52.671062+00:00] deprecation.INFO: User Deprecated: Since doctrine/doctrine-bundle 2.13: Enabling the controller resolver automapping feature has been deprecated. Symfony Mapped Route Parameters should be used as replacement. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since doctrine/doctrine-bundle 2.13: Enabling the controller resolver automapping feature has been deprecated. Symfony Mapped Route Parameters should be used as replacement. at /opt/kimai/vendor/doctrine/doctrine-bundle/src/DependencyInjection/DoctrineExtension.php:533)"} {"channel":"deprecation"}
[2024-10-10T23:55:01.516994+00:00] deprecation.INFO: User Deprecated: Since twig/twig 3.12: Twig Filter "spaceless" is deprecated in /opt/kimai/vendor/kevinpapst/tabler-bundle/templates/components/actions.html.twig at line 19. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since twig/twig 3.12: Twig Filter \"spaceless\" is deprecated in /opt/kimai/vendor/kevinpapst/tabler-bundle/templates/components/actions.html.twig at line 19. at /opt/kimai/vendor/twig/twig/src/ExpressionParser.php:830)"} {"channel":"deprecation"}
[2024-10-10T23:55:01.578918+00:00] deprecation.INFO: User Deprecated: Since twig/twig 3.12: Twig Filter "spaceless" is deprecated in /opt/kimai/vendor/kevinpapst/tabler-bundle/templates/components/button.html.twig at line 4. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since twig/twig 3.12: Twig Filter \"spaceless\" is deprecated in /opt/kimai/vendor/kevinpapst/tabler-bundle/templates/components/button.html.twig at line 4. at /opt/kimai/vendor/twig/twig/src/ExpressionParser.php:830)"} {"channel":"deprecation"}
[2024-10-10T23:55:02.398761+00:00] php.CRITICAL: Fatal Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 192512 bytes) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\OutOfMemoryError(code: 0): Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 192512 bytes) at /opt/kimai/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherDumper.php:407)"} {"channel":"php"}
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 32768 bytes) in /opt/kimai/vendor/symfony/var-dumper/Caster/ExceptionCaster.php on line 221

### Describe your setup and add your Docker compose file (redact your credentials)

```
# The following line is only required for old installations
# version: "3.7"

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - ${DATA_FOLDER}/caddy_config:/config
      - ${DATA_FOLDER}/caddy_config/Caddyfile:/etc/caddy/Caddyfile

  sqldb:
      image: mysql:8.3
      volumes:
          - mysql_data:/var/lib/mysql
      environment:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      command: --default-storage-engine innodb
      restart: unless-stopped
      healthcheck:
          test: mysqladmin -p${MYSQL_ROOT_PASSWORD} ping -h localhost
          interval: 20s
          start_period: 10s
          timeout: 10s
          retries: 3

  kimai:
      image: kimai/kimai2:apache
      volumes:
          - kimai_data:/opt/kimai/var/data
          - kimai_plugins:/opt/kimai/var/plugins
          - ${DATA_FOLDER}/kimai_config/local.yaml:/opt/kimai/config/packages/local.yaml
      ports:
          - 8001:8001
      environment:
          - ADMINMAIL=${KIMAI_USER}
          - ADMINPASS=${KIMAI_PASSWORD}
          - "DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@sqldb/${MYSQL_DATABASE}?charset=utf8mb4&serverVersion=8.3.0"
          - TRUSTED_HOSTS=localhost,127.0.0.1,${SUBDOMAIN}.${DOMAIN_NAME}
          - TZ=${TIMEZONE}
      restart: unless-stopped

volumes:
  caddy_data:
    external: true
  kimai_data:
    external: true
  kimai_plugins:
    external: true
  mysql_data:
    external: true

```
