### ISSUE TITLE
Container not starting after update

### ISSUE THREAD

**Issue by felixlabrot** [kimai/kimai#5129]
### Describe the problem

After updating to the latest Docker image, the container doesn't start anymore. This error message is shown: `/usr/local/bin/docker-php-entrypoint: 9: exec: /startup.sh: not found`

### Describe your setup and add your Docker compose file (redact your credentials)

OS: Ubuntu 20.04.6 LTS
Docker version 27.3.1, build ce12230
Docker Compose version v2.29.7

```
version: '3.5'
services:

  sqldb:
    image: mysql:8.3
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimai
      - MYSQL_PASSWORD=*****
      - MYSQL_ROOT_PASSWORD=*****
    command: --default-storage-engine innodb
    restart: always
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2:apache
    volumes:
      - data:/opt/kimai/var/data
    ports:
      - 8001:8001
    environment:
      - ADMINMAIL=admin@*****
      - ADMINPASS=*****
      - "DATABASE_URL=mysql://kimai:*****@sqldb/kimai?charset=utf8mb4&serverVersion=8.3.0"
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1
    restart: always

volumes:
  data:
  mysql:
```
