### ISSUE TITLE
Mail not working

### ISSUE THREAD

**Issue by mxxmxn** [kimai/kimai#5151]
### Describe the issue

When I test the email with `bin/console mailer:test to@domain.de`, I get an error: `550-From header sender domain not verified (example.org)`. Obviously the mailer is trying to use an `example.org` domain. It works when I try `bin/console mailer:test --from kimai@mydomain.de to@domain.de`.
When I check the environment variable with `echo $MAILER_FROM`, I get the correct mail address.

I have configured the env variable in the docker compose file:
```
services:
  kimai:
    environment:
      - ADMINMAIL=kimai@mydomain.de
      - ADMINPASS=password
      - MAILER_URL=smtp://kimai@mydomain.de:password@mail.smtp2go.com:2525?encryption=ssl
      - MAILER_FROM=kimai@mydomain.de
```

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.24.0

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.2
