### ISSUE TITLE
Missing demo data in docker dev environment

### ISSUE THREAD

**Issue by kernie** [kimai/kimai#5272]
Hello,

I'm applying a "standard" docker-compose file to install Kimai 2.27 in a container:

```
services:

  sqldb:
    image: mysql:8.3
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    command: --default-storage-engine innodb
    restart: unless-stopped
    # ports:
    #   - 3306:3306
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai/kimai2:dev
    ports:
      - 8001:8001
    environment:
      - ADMINMAIL=${ADMIN_EMAIL}
      - ADMINPASS=${ADMIN_PASSWORD}
      - "DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@sqldb/${DATABASE_NAME}?charset=utf8mb4&serverVersion=8.3"
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1
    volumes:
      - public:/opt/kimai/public
      - plugins:/opt/kimai/var/plugins
      - invoices:/opt/kimai/var/invoices
      - data:/opt/kimai/var/data
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    restart: unless-stopped
    depends_on:
      - sqldb

volumes:
    public:
    mysql:
    data:
    plugins:
    invoices:
```
combined with a dotenv file:
```
DATABASE_NAME=kimai
DATABASE_USER=kimaiuser
DATABASE_PASSWORD=kimaipassword
DATABASE_ROOT_PASSWORD=changemeplease
APP_ENV=dev
ADMIN_EMAIL=admin@kimai.local
ADMIN_PASSWORD=changemeplease
```

The container builds without error and I can login in the browser.

Then, I  load the demo database with ` docker exec -ti docker-kimai-1 /opt/kimai/bin/console kimai:reset:test --no-interaction` where "docker-kimai-1" is my kimai docker instance.

Afterwards, all new users (susan_super, etc) are in the system, but it exists only one project "Test" and one activity "Test". The timesheets are missing.

Any idea what is going wrong?

Thanks!
