### ISSUE TITLE
Customer administration error 500

### ISSUE THREAD

**Issue by danielvandenberg95** [kimai/kimai#5544]
### Describe the problem

I'm running the latest fpm version behind NGINX, and am getting the following error when requesting customer administration, all other pages work fine:
```
10.0.15.11 -  18/Jun/2025:22:15:23 +0200 "GET /index.php" 500
[2025-06-18T20:15:23.125575+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Intl\Exception\MissingResourceException: "Couldn't read the indices [Names][de] for the locale "en" in "/opt/kimai/vendor/symfony/intl/Resources/data/regions". The indices also couldn't be found for the fallback locale(s) "root"." at BundleEntryReader.php line 169 {"exception":"[object] (Symfony\\Component\\Intl\\Exception\\MissingResourceException(code: 0): Couldn't read the indices [Names][de] for the locale \"en\" in \"/opt/kimai/vendor/symfony/intl/Resources/data/regions\". The indices also couldn't be found for the fallback locale(s) \"root\". at /opt/kimai/vendor/symfony/intl/Data/Bundle/Reader/BundleEntryReader.php:169)\n[previous exception] [object] (Symfony\\Component\\Intl\\Exception\\ResourceBundleNotFoundException(code: 0): The resource bundle \"/opt/kimai/vendor/symfony/intl/Resources/data/regions/root.php\" does not exist. at /opt/kimai/vendor/symfony/intl/Data/Bundle/Reader/PhpBundleReader.php:40)"} {"channel":"request"}
```

### Describe your setup and add your Docker compose file (redact your credentials)

Docker (swarm) config:
```
  kimai:
    image: kimai/kimai2:fpm-2.36.1
    hostname: "kimai"
    environment:
      - ADMINMAIL=admin@kimai.local
      - ADMINPASS=changemeplease
      - DATABASE_URL=mysql://kimai:xxxxx@db/kimai?charset=utf8&serverVersion=10.11.5
      #- DATABASE_URL=sqlite:///opt/kimai/var/data/kimai.sqlite
      - TRUSTED_HOSTS=kimai2.dmvandenberg.nl
      - APP_ENV=prod
      - APP_DEBUG=0
    volumes:
      - /mnt/DockerData/kimai/public:/opt/kimai/public
      - /mnt/DockerData/kimai/var/data:/opt/kimai/var/data

      - run_vol:/opt/kimai/var/cache,mode:01777
      - log_vol:/opt/kimai/var/log,mode:01777
    restart: unless-stopped
    healthcheck:
      disable: true
      #  test: exit 0
      # start_period: 30s
      timeout: 10s
      retries: 9
    networks:
      - nginx-ingress
      - mysql
 ```
Nginx config:

server {
  listen 443 ssl;
  http2 on;
  server_name myurl;
  include ssl.incl;
  ssl_certificate      /mine;
  ssl_certificate_key  /mykey;
  
  location / {
    #proxy_pass https://192.168.0.2:444;
	  #proxy_pass http://nginx-kimai:80;
	  root /opt/kimai/public;
	  try_files $uri $uri/ /index.php$is_args$args;
  }
  location ~ ^/index\.php(/|$) {
    resolver 127.0.0.11 ipv6=off;
    root /opt/kimai/public;
    # proxy_pass http://kimai:8001/index.php?is_args$args;

    # fastcgi_hide_header X-Powered-By;
    fastcgi_pass kimai:9000;
    fastcgi_split_path_info ^(.+\.php)(/.*)$;
    add_header X-Filename $document_root$fastcgi_script_name always;
    add_header X-DocRoot $realpath_root always;
    # fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    # fastcgi_param DOCUMENT_ROOT $realpath_root;
    fastcgi_param SCRIPT_NAME index.php;
    fastcgi_param SCRIPT_FILENAME /opt/kimai/public/index.php;
    fastcgi_param SERVER_PORT "443";
    fastcgi_param HTTPS "on";
    internal;

fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;

fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;

fastcgi_param  HTTPS              $https if_not_empty;

fastcgi_param  REDIRECT_STATUS    200;

  }
}
```

### Command used to run the container

_No response_

**Comment by kevinpapst** [comment]
I have seen this error at some point in the past. Unfortunately I can't remember what it was, not a direct Kimai bug, but more of an environment / Symfony or outdated cache or package issue. 

Maybe its best if you remove these three mounts first and restart:
      - /mnt/DockerData/kimai/public:/opt/kimai/public
      - run_vol:/opt/kimai/var/cache,mode:01777
      - log_vol:/opt/kimai/var/log,mode:01777

Public is just wrong and causes bugs, because you will use old Javascript and CSS.
Cache is likely wrong, but I have never tried what happens. I strongly suggest to get rid of it, maybe that is what's causing the problem in the first place.
Kimai logs to Docker out and should not write any log file to the last mount.

**Comment by danielvandenberg95** [comment]
Unfortunately that did not help. Also, I just figured I forgot to add part of the config:
```
  run_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  log_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
```
I saw considerable startup speedups with that in the past, but for now for debugging I'll keep the. Disabled.

I've tried running with APP_ENV=dev and APP_DEBUG=1, but that only seemed to add errors. I've tried a previous docker image, also did not work.
