### ISSUE TITLE
Google SAML fails with Docker apache image but works with dev image

### ISSUE THREAD

**Issue by JoelBowring-Hover** [kimai/kimai#5549]
### Describe the issue

I have followed the [official DigitalOcean install instructions](https://www.kimai.org/documentation/hosting-digital-ocean.html) to install Kimai on Ubuntu 22.04 LTS and I have configured Google SAML authentication according to the [documentation](https://www.kimai.org/documentation/saml-google.html).

When using the default `docker-compose.yml` (i.e. the `kimai/kimai2:apache` image), logging in with Google SAML results in an authentication error on the Kimai login screen ("An authentication exception error occurred"). However, changing the image to `kimai/kimai2:dev` results in a successful login.

This is the contents of my `local.yaml`:
```yaml
# You can add custom Kimai configurations in this file
# see https://www.kimai.org/documentation/local-yaml.html
kimai:
    saml:
        provider: google
        activate: true
        title: Login with Google
        mapping:
            - { saml: $Email, kimai: email }
            - { saml: $FirstName $LastName, kimai: alias }
            - { saml: $Title, kimai: title }
            - { saml: $AccountNumber, kimai: accountNumber }
        roles:
            resetOnLogin: true
            attribute: Groups
            mapping:
                - { saml: KIMAI SYSTEM, kimai: ROLE_SUPER_ADMIN }
                - { saml: KIMAI ADMIN, kimai: ROLE_ADMIN }
                - { saml: KIMAI TEAMLEAD, kimai: ROLE_TEAMLEAD }
        connection:
            idp:
                entityId: 'https://accounts.google.com/o/saml2?idpid=redacted'
                singleSignOnService:
                    url: 'https://accounts.google.com/o/saml2/idp?idpid=redacted'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
                x509cert: 'redacted'
            # Your Kimai: replace https://www.example.com with your base URL
            sp:
                entityId: 'https://redacted/auth/saml/metadata'
                assertionConsumerService:
                    url: 'https://redacted/auth/saml/acs'
                    binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
            # only set baseurl, if auto-detection doesn't work
            baseurl: 'https://redacted'
            strict: true
            debug: true
            security:
                nameIdEncrypted: false
                authnRequestsSigned: false
                logoutRequestSigned: false
                logoutResponseSigned: false
                wantMessagesSigned: false
                wantAssertionsSigned: false
                wantNameIdEncrypted: false
                requestedAuthnContext: true
                signMetadata: false
                wantXMLValidation: true
                signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
                digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
            contactPerson:
                technical:
                    givenName: 'redacted'
                    emailAddress: 'redacted'
            organization:
                en:
                    name: 'redacted'
                    displayname: 'redacted'
                    url: 'redacted'
                    
```

### I already tried

- [x] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [x] I've searched for similar issues in this repository.
- [x] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.36.1

### How do you run Kimai?

Virtual Server or alike

### Which PHP version are you using?

8.3

### Logfile

Complete output of `docker compose logs`:
```
++ cat /opt/kimai/version.txt
+ KIMAI=2.35.1
+ echo 2.35.1
+ waitForDB
2.35.1
++ awk -F '[/:@]' '{print $4}'
+ DATABASE_USER=kimai
++ awk -F '[/:@]' '{print $5}'
+ DATABASE_PASS=kimai
++ awk -F '[/:@]' '{print $6}'
+ DATABASE_HOST=sqldb
++ awk -F '[/:@]' '{print $7}'
+ DATABASE_PORT='kimai?charset=utf8mb4&serverVersion=8.3.0'
++ awk -F '[/?]' '{print $4}'
+ DATABASE_BASE=kimai
+ re='^[0-9]+$'
+ [[ kimai?charset=utf8mb4&serverVersion=8.3.0 =~ ^[0-9]+$ ]]
+ DATABASE_PORT=3306
+ echo 'Wait for database connection ...'
Wait for database connection ...
+ php /dbtest.php sqldb kimai 3306 kimai kimai
+ echo Checking DB: 10
+ sleep 3
Testing DB:SQLSTATE[HY000] [2002] Connection refused (?)Checking DB: 10
+ php /dbtest.php sqldb kimai 3306 kimai kimai
+ echo 'Connection established'
+ handleStartup
+ '[' -z 512M ']'
Testing DB:Connection established
+ sed -i 's/memory_limit.*/memory_limit=512M/g' /usr/local/etc/php/php.ini
+ cp /assets/monolog.yaml /opt/kimai/config/packages/monolog.yaml
+ '[' -z '' ']'
++ id -u www-data
+ USER_ID=33
+ '[' -z '' ']'
++ id -g www-data
+ GROUP_ID=33
+ grep -w 33 /etc/group
Group already exists
+ echo Group already exists
+ id 33
User already exists
+ echo User already exists
+ '[' -e /use_apache ']'
++ id -nu 33
+ export APACHE_RUN_USER=www-data
+ APACHE_RUN_USER=www-data
++ id -ng 33
+ export APACHE_RUN_GROUP=www-data
+ APACHE_RUN_GROUP=www-data
+ export APACHE_PID_FILE=/var/run/apache2/apache2.pid
+ APACHE_PID_FILE=/var/run/apache2/apache2.pid
+ export APACHE_RUN_DIR=/var/run/apache2
+ APACHE_RUN_DIR=/var/run/apache2
+ export APACHE_LOCK_DIR=/var/lock/apache2
+ APACHE_LOCK_DIR=/var/lock/apache2
+ export APACHE_LOG_DIR=/var/log/apache2
+ APACHE_LOG_DIR=/var/log/apache2
+ export LANG=C
+ LANG=C
+ prepareKimai
+ /opt/kimai/bin/console -n kimai:install
 Start installation ...
Database `kimai` for connection named default already exists. Skipped.
 Creating database ...

 [WARNING] You have 1 previously executed migrations in the database that are
           not registered migrations.

 >> 2025-06-16 13:23:27 (DoctrineMigrations\Version20250608143244)

 [OK] Already at the latest version ("DoctrineMigrations\Version20250608143244")

 Rebuilding cache ...

 // Clearing the cache for the prod environment with debug false

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.


 // Warming up the cache for the prod environment with debug false

 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.


 [OK] Successfully installed Kimai version 2.35.1 🎉

+ '[' '!' -z redacted ']'
+ '[' '!' -a redacted ']'
+ /opt/kimai/bin/console kimai:user:create admin redacted ROLE_SUPER_ADMIN redacted

 [ERROR] email: This e-mail address is already in use.

 [ERROR] email: An equal username is already used.

+ echo 2.35.1
+ echo 'Kimai is ready'
+ runServer
Kimai is ready
+ /opt/kimai/bin/console kimai:reload --env=prod
 Validating config file syntax ...

 [OK] All 27 YAML files contain valid syntax.



 [OK] All 600 XLIFF files contain valid syntax.


 Rebuilding your cache, please be patient ...

 // Clearing the cache for the prod environment with debug false

[2025-06-23T16:15:59.627023+00:00] deprecation.INFO: User Deprecated: Since doctrine/doctrine-bundle 2.13: Enabling the controller resolver automapping feature has been deprecated. Symfony Mapped Route Parameters should be used as replacement. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Since doctrine/doctrine-bundle 2.13: Enabling the controller resolver automapping feature has been deprecated. Symfony Mapped Route Parameters should be used as replacement. at /opt/kimai/vendor/doctrine/doctrine-bundle/src/DependencyInjection/DoctrineExtension.php:509)"} {"channel":"deprecation"}
 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.


 // Warming up the cache for the prod environment with debug false

 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.


 [OK] Kimai config was reloaded

+ chown -R 33:33 /opt/kimai/var
+ '[' -e /use_apache ']'
+ exec /usr/sbin/apache2 -D FOREGROUND
[Mon Jun 23 18:16:10.623160 2025] [mpm_prefork:notice] [pid 1:tid 1] AH00163: Apache/2.4.62 (Debian) configured -- resuming normal operations
[Mon Jun 23 18:16:10.623238 2025] [core:notice] [pid 1:tid 1] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
localhost:8001 127.0.0.1 - - [23/Jun/2025:18:16:19 +0200] "GET / HTTP/1.1" 302 626 "-" "curl/7.88.1"
localhost:8001 127.0.0.1 - - [23/Jun/2025:18:16:39 +0200] "GET / HTTP/1.1" 302 626 "-" "curl/7.88.1"
localhost:8001 172.18.0.3 - - [23/Jun/2025:18:16:57 +0200] "GET /en/logout HTTP/1.1" 302 1008 "https://redacted/en/doctor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 Edg/137.0.0.0"
localhost:8001 172.18.0.3 - - [23/Jun/2025:18:16:58 +0200] "GET /en/homepage HTTP/1.1" 302 848 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 Edg/137.0.0.0"
localhost:8001 172.18.0.3 - - [23/Jun/2025:18:16:58 +0200] "GET /en/login HTTP/1.1" 200 1622 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 Edg/137.0.0.0"
localhost:8001 127.0.0.1 - - [23/Jun/2025:18:16:59 +0200] "GET / HTTP/1.1" 302 626 "-" "curl/7.88.1"
localhost:8001 172.18.0.3 - - [23/Jun/2025:18:17:01 +0200] "GET /auth/saml/login HTTP/1.1" 302 4663 "https://redacted/en/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 Edg/137.0.0.0"
localhost:8001 172.18.0.3 - - [23/Jun/2025:18:17:02 +0200] "POST /auth/saml/acs HTTP/1.1" 302 1085 "https://accounts.google.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 Edg/137.0.0.0"
localhost:8001 172.18.0.3 - - [23/Jun/2025:18:17:02 +0200] "GET /en/login HTTP/1.1" 200 1622 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36 Edg/137.0.0.0"
```
